homeassistant:
  customize: {}

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: "[security|presence_simulation]Turn Off Presence Simulation When House is Occupied"
    description: "Turns off the presence simulation when the house becomes occupied."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.house_occupied
        to: "on"
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.presence_simulation

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
