##########################################  HERE BEGINS THE SECURITY TAB  ##########################################
title: Security
icon: mdi:security
panel: false
badges: []
cards:
  - type: vertical-stack
    cards:
    - type: horizontal-stack
      cards:
        - type: button
          entity: switch.presence_simulation
          name: Presence Simulation
          icon: mdi:shield-home
          state_color: true
          show_state: true
          tap_action:
            action: toggle
        - type: button
          entity: group.security_alert_notifications
          name: Security Notifications
          icon: mdi:shield-home
          state_color: true
          show_state: true
          tap_action:
            action: toggle
        - type: button
          entity: switch.doorbell_do_not_disturb_mode
          name: Doorbell DND
          icon: mdi:bell-off-outline
          state_color: true
          show_state: true
          tap_action:
            action: toggle

    - title: Active motion sensors
      type: entity-filter
      conditions:
        - condition: or
          conditions:
            - condition: state
              state: "on"
            - condition: state
              state: "open"
      entities:
        - entity: binary_sensor.bedroom_motion_1
          name: Bedroom
          secondary_info: last-changed
        - entity: binary_sensor.entry_motion_1
          name: Entry 1
          secondary_info: last-changed
        - entity: binary_sensor.entry_motion_2
          name: Entry 2
          secondary_info: last-changed
        - entity: binary_sensor.hallway_1st_floor_motion_1
          name: 1st Floor 1
          secondary_info: last-changed
        - entity: binary_sensor.hallway_1st_floor_motion_2
          name: 1st Floor 2
          secondary_info: last-changed
        - entity: binary_sensor.stairs_lower_motion_1
          name: Stairs Lower
          secondary_info: last-changed
        - entity: binary_sensor.hallway_2nd_floor_motion_1
          name: 2nd Floor 1
          secondary_info: last-changed
        - entity: binary_sensor.hallway_2nd_floor_motion_2
          name: 2nd Floor 2
          secondary_info: last-changed
        - entity: binary_sensor.stairs_upper_motion_1
          name: Stairs Upper
          secondary_info: last-changed
        - entity: binary_sensor.livingroom_motion_1
          name: Livingroom 1
          secondary_info: last-changed
        - entity: binary_sensor.livingroom_motion_2
          name: Livingroom 2
          secondary_info: last-changed
        - entity: binary_sensor.livingroom_motion_3
          name: Livingroom 3
          secondary_info: last-changed
        - entity: binary_sensor.kitchen_motion_1
          name: Kitchen
          secondary_info: last-changed
        - entity: binary_sensor.kitchen_motion_2
          name: Kitchen 2
          secondary_info: last-changed
        - entity: binary_sensor.study_motion_1
          name: Study 1
          secondary_info: last-changed
        - entity: binary_sensor.study_motion_2
          name: Study 2
          secondary_info: last-changed
        - entity: binary_sensor.bathroom_motion_1
          name: Bathroom
          secondary_info: last-changed
        - entity: binary_sensor.babyroom_motion_1
          name: Baby Room
          secondary_info: last-changed
        - entity: binary_sensor.babycam_motion
          name: Baby Cam Motion
          secondary_info: last-changed
        - entity: binary_sensor.outside_motion_1
          name: Outside
          secondary_info: last-changed
        - entity: binary_sensor.back_door_sensor
          name: Back door
          secondary_info: last-changed
        - entity: binary_sensor.front_door_sensor
          name: Front door
          secondary_info: last-changed
        - entity: binary_sensor.shed_door
          name: Shed Door
          secondary_info: last-changed
        - entity: binary_sensor.stairs_cabinet_door_sensor
          name: Cabinet door
          secondary_info: last-changed
        - entity: binary_sensor.washroom_door_sensor
          name: Washroom door
          secondary_info: last-changed
        - entity: binary_sensor.meterkast_door_sensor
          name: Utility Cabinet door
          secondary_info: last-changed

# Use template below to find all motion and door sensors. For a full list of device classes, seee: https://www.home-assistant.io/integrations/binary_sensor/
# - {{ states | selectattr('attributes.device_class', 'eq', 'motion') | map(attribute='entity_id') | list | join('\n- ') }}
# - {{ states | selectattr('attributes.device_class', 'eq', 'door') | map(attribute='entity_id') | list | join('\n- ') }}

  - type: history-graph
    title: Motion sensors
    hours_to_show: 12
    entities:
      - entity: binary_sensor.entry_motion_1
        name: Entry 1
      - entity: binary_sensor.entry_motion_2
        name: Entry 2
      - entity: binary_sensor.hallway_1st_floor_motion_1
        name: 1st Floor 1
      - entity: binary_sensor.hallway_1st_floor_motion_2
        name: 1st Floor 2
      - entity: binary_sensor.stairs_lower_motion_1
        name: Stairs Lower
      - entity: binary_sensor.hallway_2nd_floor_motion_1
        name: 2nd Floor 1
      - entity: binary_sensor.hallway_2nd_floor_motion_2
        name: 2nd Floor 2
      - entity: binary_sensor.stairs_upper_motion_1
        name: Stairs Upper
      - entity: binary_sensor.livingroom_motion_1
        name: Livingroom 1
      - entity: binary_sensor.livingroom_motion_2
        name: Livingroom 2
      - entity: binary_sensor.livingroom_motion_3
        name: Livingroom 3
      - entity: binary_sensor.kitchen_motion_1
        name: Kitchen
      - entity: binary_sensor.kitchen_motion_2
        name: Kitchen 2
      - entity: binary_sensor.bathroom_motion_1
        name: Bathroom
      - entity: binary_sensor.bedroom_motion_1
        name: Bedroom
      - entity: binary_sensor.babyroom_motion_1
        name: Baby Room
      - entity: binary_sensor.study_motion_1
        name: Study 1
      - entity: binary_sensor.study_motion_2
        name: Study 2
      - entity: binary_sensor.babycam_motion
        name: Baby Cam Motion
      - entity: binary_sensor.outside_motion_1
        name: Outside
      - entity: binary_sensor.vibration_sensor_desk_chair
        name: Study Chair
      - entity: binary_sensor.vibration_sensor_new_desk_chair
        name: Study Chair New
      - entity: binary_sensor.vibration_sensor_mailbox
        name: Mailbox
      - entity: binary_sensor.litterbox_vibration
        name: Litter Box
      - entity: binary_sensor.washroom_door_sensor
        name: Washroom door
      - entity: binary_sensor.stairs_cabinet_door_sensor
        name: Cabinet door
      - entity: binary_sensor.shed_door
        name: Shed Door
      - entity: binary_sensor.front_door_sensor
        name: Front door
      - entity: binary_sensor.back_door_sensor
        name: Back Door
      - entity: binary_sensor.shed_door
        name: Shed Door
      - entity: binary_sensor.washroom_door_sensor
        name: Washroom door
      - entity: binary_sensor.meterkast_door_sensor
        name: Utility Cabinet
      - entity: binary_sensor.bedroom_closet_door_sensor
        name: Bedroom Cabinet

  - type: custom:collapsable-cards
    title: All Presence Sensors
    cards:
      - type: entities
        #title: Presence Detectors
        show_header_toggle: false
        entities:
          - entity: binary_sensor.entry_motion_1
            name: Entry 1
            secondary_info: last-changed
          - entity: binary_sensor.entry_motion_2
            name: Entry 2
            secondary_info: last-changed
          - entity: binary_sensor.hallway_1st_floor_motion_1
            name: 1st Floor 1
            secondary_info: last-changed
          - entity: binary_sensor.hallway_1st_floor_motion_2
            name: 1st Floor 2
            secondary_info: last-changed
          - entity: binary_sensor.stairs_lower_motion_1
            name: Stairs Lower
            secondary_info: last-changed
          - entity: binary_sensor.hallway_2nd_floor_motion_1
            name: 2nd Floor 1
            secondary_info: last-changed
          - entity: binary_sensor.hallway_2nd_floor_motion_2
            name: 2nd Floor 2
            secondary_info: last-changed
          - entity: binary_sensor.stairs_upper_motion_1
            name: Stairs Upper
            secondary_info: last-changed
          - entity: binary_sensor.livingroom_motion_1
            name: Livingroom 1
            secondary_info: last-changed
          - entity: binary_sensor.livingroom_motion_2
            name: Livingroom 2
            secondary_info: last-changed
          - entity: binary_sensor.livingroom_motion_3
            name: Livingroom 3
            secondary_info: last-changed
          - entity: binary_sensor.kitchen_motion_1
            name: Kitchen
            secondary_info: last-changed
          - entity: binary_sensor.kitchen_motion_2
            name: Kitchen 2
            secondary_info: last-changed
          - entity: binary_sensor.bedroom_motion_1
            name: Bedroom
            secondary_info: last-changed
          - entity: binary_sensor.study_motion_1
            name: Study 1
            secondary_info: last-changed
          - entity: binary_sensor.study_motion_2
            name: Study 2
            secondary_info: last-changed
          - entity: binary_sensor.bathroom_motion_1
            name: Bathroom
            secondary_info: last-changed
          - entity: binary_sensor.babyroom_motion_1
            name: Baby Room
            secondary_info: last-changed
          - entity: binary_sensor.babycam_motion
            name: Baby Cam Motion
            secondary_info: last-changed
          - entity: binary_sensor.outside_motion_1
            name: Outside
            secondary_info: last-changed
          - entity: binary_sensor.back_door_sensor
            name: Back door
            secondary_info: last-changed
          - entity: binary_sensor.front_door_sensor
            name: Front door
            secondary_info: last-changed
          - entity: binary_sensor.shed_door
            name: Shed Door
            secondary_info: last-changed
          - entity: binary_sensor.stairs_cabinet_door_sensor
            name: Cabinet door
            secondary_info: last-changed
          - entity: binary_sensor.washroom_door_sensor
            name: Washroom door
            secondary_info: last-changed
          - entity: binary_sensor.meterkast_door_sensor
            name: Utility Cabinet door
            secondary_info: last-changed
