##########################################  HERE BEGINS THE SECURITY TAB  ##########################################
title: Security
icon: mdi:security
panel: false
badges: []
cards:
  - cards:
      - type: entities
        entities:
          - entity: sensor.last_triggered_motion_sensor
          - entity: sensor.last_triggered_motion_sensor
            type: attribute
            attribute: timestamp
            format: relative
            name: Detection time
            icon: mdi:history
          - type: divider
      - entities:
          - entity: binary_sensor.motion_sensor_bathroom
            name: Bathroom
          - entity: binary_sensor.motion_sensor_entry
            name: Entry 1
          - entity: binary_sensor.motion_sensor_entry2
            name: Entry 2
          - entity: binary_sensor.motion_sensor_livingroom
            name: Livingroom 1
          - entity: binary_sensor.motion_sensor_livingroom2
            name: Livingroom 2
          - entity: binary_sensor.motion_sensor_livingroom3
            name: Livingroom 3
          - entity: binary_sensor.tapo_camera_d6d4_motion
            name: Livingroom Camera
          - entity: binary_sensor.motion_sensor_bedroom
            name: Bedroom
          - entity: binary_sensor.motion_sensor_study
            name: Study 1
          - entity: binary_sensor.motion_sensor_study2
            name: Study 2
          - entity: binary_sensor.motion_sensor_kitchen
            name: Kitchen
          - entity: binary_sensor.motion_sensor_balcony
            name: Balcony
          - entity: binary_sensor.vibration_sensor
            name: Study Chair
          - entity: binary_sensor.kitchen_door_window_sensor
            name: Kitchen door
          - entity: binary_sensor.door_window_sensor_frontdoor
            name: Front door
          - entity: binary_sensor.door_window_sensor_cabinet
            name: Cabinet door
        hours_to_show: 24
        title: Motion sensors
        type: history-graph
    type: vertical-stack
  - entities:
      - entity: binary_sensor.motion_sensor_bedroom
        name: Bedroom
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_entry
        name: Entry 1
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_entry2
        name: Entry 2

      - entity: binary_sensor.motion_sensor_livingroom
        name: Livingroom 1
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_livingroom2
        name: Livingroom 2
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_livingroom3
        name: Livingroom 3
        secondary_info: last-changed
      - entity: binary_sensor.tapo_camera_d6d4_motion
        name: Livingroom Camera
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_bedroom
        name: Bedroom
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_study
        name: Study 1
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_study2
        name: Study 2
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_kitchen
        name: Kitchen
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_balcony
        name: Balcony
        secondary_info: last-changed
      - entity: binary_sensor.kitchen_door_window_sensor
        name: Kitchen door
        secondary_info: last-changed
      - entity: binary_sensor.door_window_sensor_frontdoor
        name: Front door
        secondary_info: last-changed
      - entity: binary_sensor.door_window_sensor_cabinet
        name: Cabinet door
        secondary_info: last-changed
    title: Active motion sensors
    type: entity-filter
    state_filter:
      - operator: "=="
        value: "on"
  - type: picture-glance
    title: Living Room
    camera_image: camera.tapo_camera_d6d4_hd
    camera_view: live
    entities:
      - entity: light.livingroom_lights
        icon: 'mdi:lightbulb-group'
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.toggle_lights_for_camera
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:arrow-left-drop-circle-outline'
        tap_action:
          action: call-service
          service: tapo_control.ptz
          service_data:
            entity_id: camera.tapo_camera_d6d4_hd
            pan: LEFT
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:arrow-up-drop-circle-outline'
        tap_action:
          action: call-service
          service: tapo_control.ptz
          service_data:
            entity_id: camera.tapo_camera_d6d4_hd
            tilt: UP
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:arrow-down-drop-circle-outline'
        tap_action:
          action: call-service
          service: tapo_control.ptz
          service_data:
            entity_id: camera.tapo_camera_d6d4_hd
            tilt: DOWN
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:arrow-right-drop-circle-outline'
        tap_action:
          action: call-service
          service: tapo_control.ptz
          service_data:
            entity_id: camera.tapo_camera_d6d4_hd
            pan: RIGHT
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:eye-outline'
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.deactivate_livingroom_camera_privacy_mode
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:eye-off-outline'
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.activate_livingroom_camera_privacy_mode
      - entity: camera.tapo_camera_d6d4_hd
        icon: 'mdi:power'
        tap_action:
          action: call-service
          service: tapo_control.reboot
          service_data:
            entity_id: camera.tapo_camera_d6d4_hd
    hold_action:
      action: more-info
