##########################################  HERE BEGINS THE SECURITY TAB  ##########################################
title: Security
icon: mdi:security
panel: false
badges: []
cards:
  - cards:
      - entities:
          - entity: binary_sensor.motion_sensor_bedroom
            name: Bedroom
          - entity: binary_sensor.motion_sensor_hallway
            name: Hallway
          - entity: binary_sensor.motion_sensor_livingroom
            name: Livingroom
          - entity: binary_sensor.motion_sensor_livingroom2
            name: Livingroom 2
          - entity: binary_sensor.motion_sensor_livingroomnew
            name: Livingroom new
          - entity: binary_sensor.motion_sensor_bedroom
            name: Bedroom
          - entity: binary_sensor.motion_sensor_study
            name: Study
          - entity: binary_sensor.motion_sensor_study2
            name: Study2 new
          - entity: binary_sensor.motion_sensor_kitchen
            name: Kitchen
          - entity: binary_sensor.motion_sensor_balcony
            name: Balcony
          - entity: binary_sensor.door_window_sensor_kitchen
            name: Kitchen door
          - entity: binary_sensor.door_window_sensor_frontdoor
            name: Front door
          - entity: binary_sensor.door_window_sensor_cabinet
            name: Cabinet door
        hours_to_show: 24
        title: Motion sensors
        type: history-graph
    type: vertical-stack