decluttering_templates: !include decluttering-templates.yaml

title: Home
views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_vacuums.yaml
  - !include /config/lovelace/view_climate.yaml
  - !include /config/lovelace/view_mediacenter.yaml
  #- !include /config/lovelace/view_floorplan.yaml
  - !include /config/lovelace/view_security.yaml
  - !include /config/lovelace/view_network.yaml
  - !include /config/lovelace/view_server.yaml
  - !include /config/lovelace/view_hassmonitor.yaml
  - !include /config/lovelace/view_3dprinter.yaml
  - !include /config/lovelace/view_power.yaml
  - !include /config/lovelace/view_lights.yaml
  - !include /config/lovelace/view_weather.yaml
  #- !include /config/lovelace/view_plants.yaml
  - !include /config/lovelace/view_misc.yaml
  - !include /config/lovelace/view_finance.yaml #Not included in Git repo
  - !include /config/lovelace/view_main_power_entities.yaml
  - !include /config/lovelace/view_power_diagnostics.yaml
  - !include /config/lovelace/view_electricity_cost.yaml
  - !include /config/lovelace/view_epaper_diagnostics.yaml
  - !include /config/lovelace/view_medication.yaml
  #- !include /config/lovelace/view_mobile_data.yaml
  - !include /config/lovelace/view_diagnostics.yaml
