title: Home

resources:
  - url: "/local/community/apexcharts-card/apexcharts-card.js?v=2.0.4"
    type: module
  - url: "/local/community/mini-graph-card/mini-graph-card-bundle.js?v=0.9.3"
    type: module
    #see https://github.com/kalkih/mini-graph-card
  # - url: "/local/custom_lovelace/floorplan_card/floorplan-card.js?v=1.1.14"
  #   type: module
  #   #see https://github.com/pkozul/lovelace-floorplan
  - url: "/local/community/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js?v=3.0.1"
    type: js
    #see https://github.com/benct/lovelace-xiaomi-vacuum-card
  - url: "/local/custom_lovelace/monster_card/monster-card.js"
    type: module
    #see https://github.com/custom-cards/monster-card/blob/master/README.md
  - url: "/local/community/lovelace-card-mod/card-mod.js?v=13"
    type: module
    #see https://github.com/thomasloven/lovelace-card-mod
  # - url: "/local/community/lovelace-postnl-card/postnl-card.js?v=0.12.2"
  #   type: module
  #   #see https://github.com/peternijssen/lovelace-postnl-card
  - url: "/local/community/lovelace-slider-entity-row/slider-entity-row.js?v=11"
    type: module
    #see https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /local/community/custom-ui/custom-ui.js?v=20200528
    type: module
    #see https://github.com/Mariusthvdb/custom-ui
  - url: /local/community/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
    #see https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_vacuums.yaml
  #- !include /config/lovelace/view_floorplan.yaml
  - !include /config/lovelace/view_security.yaml
  - !include /config/lovelace/view_server.yaml
  - !include /config/lovelace/view_hassmonitor.yaml
  - !include /config/lovelace/view_3dprinter.yaml
  - !include /config/lovelace/view_power.yaml
  - !include /config/lovelace/view_lights.yaml
  - !include /config/lovelace/view_weather.yaml
  #- !include /config/lovelace/view_plants.yaml
  - !include /config/lovelace/view_misc.yaml
  - !include /config/lovelace/view_finance.yaml #Not included in Git repo
