title: Limited
views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_vacuums.yaml
  - !include /config/lovelace/view_climate.yaml
  - !include /config/lovelace/view_mediacenter.yaml
  - !include /config/lovelace/view_lights.yaml
  - !include /config/lovelace/view_weather.yaml
  #- !include /config/lovelace/view_plants.yaml
  - !include /config/lovelace/view_misc.yaml
  - !include /config/lovelace/view_main_power_entities.yaml
  - !include /config/lovelace/view_power_diagnostics.yaml
  - !include /config/lovelace/view_electricity_cost.yaml
