homeassistant:
  customize:
    sensor.ender3_time_elapsed:
      device_class: timestamp
    sensor.ender3_time_remaining:
      device_class: timestamp

camera:
  - platform: mjpeg
    name: Ender3
    still_image_url: !secret octoprint_camera_snapshot_url
    mjpeg_url: !secret octoprint_camera_stream_url
  - platform: proxy
    name: ender3_360p
    entity_id: camera.ender3
    max_stream_height: 360
  - platform: proxy
    name: ender3_480p
    entity_id: camera.ender3
    max_stream_height: 480
  - platform: proxy
    name: ender3_720p
    entity_id: camera.ender3
    max_stream_height: 720

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      print_time_remaining_human_readable:
        entity_id: sensor.octoprint_print_time_left
        friendly_name: "Print time remaining"
        icon_template: mdi:clock-end
        value_template: >
          {{ ( states( 'octoprint_print_time_left.state' )|int - 3600) |timestamp_custom(('%H:%M:%S')) }}
      print_elapsed_human_readable:
        entity_id: sensor.octoprint_print_estimated_time
        friendly_name: "Print time elapsed"
        icon_template: mdi:clock-start
        value_template: >
          {{ ( states( 'sensor.octoprint_print_estimated_time' )|int - 3600) |timestamp_custom(('%H:%M:%S')) }}

  - platform: command_line
    name: 'OctoPi CPU temp'
    unit_of_measurement: '°C'
    scan_interval: 60
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      pi@192.168.1.206
      cat /sys/class/thermal/thermal_zone0/temp

  - platform: command_line
    name: 'OctoPi CPU frequency'
    unit_of_measurement: 'MHz'
    scan_interval: 60
    value_template: '{{ value | multiply(0.001) | round(0) }}'
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      pi@192.168.1.206
      cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
- alias: '[ender3|notify]Notify 3D printer done'
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
  action:
      - delay: '00:01:00'
      - service: notify.mobile_app_blokmeister_op6
        data:
          title: Printer done
          message: 'Ender 3 print is done'
          data:
            icon: http://192.168.1.252:8123/local/icons/printer-3d-nozzle.png
            image: !secret octoprint_camera_snapshot_url

- alias: '[ender3|notify] update printer progress'
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_tracking_on
      to: 'off'
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      to: 'on'
    - platform: state
      entity_id: person.sander_blok
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.octoprint_printing
      state: 'on'
    - condition: state
      entity_id: person.sander_blok
      state: 'not_home'
  action:
    repeat:
      sequence:
        - service: notify.mobile_app_blokmeister_op6
          data_template:
            title: Printer progress
            message: "Ender 3 print is at {{ states( 'sensor.octoprint_print_progress' ) }}%. Estimated time remaining: {{ states( 'sensor.octoprint_print_time_left' ) }}"
            data:
              icon: http://192.168.1.252:8123/local/icons/printer-3d-nozzle.png
              image: !secret octoprint_camera_snapshot_url
        - delay: 00:30:00
      until:
        condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.sleep_tracking_on
            state: 'on'
          - condition: state
            entity_id: binary_sensor.octoprint_printing
            state: 'off'
          - condition: state
            entity_id: person.sander_blok
            state: 'home'

- alias: '[ender3|notify] printer overtemp warning'
  trigger:
    - platform: numeric_state
      entity_id: sensor.octoprint_tool_0_temperature
      above: 240
    - platform: numeric_state
      entity_id: sensor.octoprint_bed_temperature
      above: 120
  action:
      - service: notify.mobile_app_blokmeister_op6
        data_template:
          title: Printer temperature warning
          message: "Ender 3 temperature is too high! Nozzle temperature: {{ states( 'sensor.octoprint_tool_0_temperature') }}. Bed temperature: {{ states( 'sensor.octoprint_bed_temperature') }}"
          data:
            icon: http://192.168.1.252:8123/local/icons/printer-3d-nozzle-alert.png
            image: !secret octoprint_camera_snapshot_url

- alias: '[ender3|lights] turn on light when printer is on'
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.average_illumination_study
      below: 50
    - platform: state
      entity_id: light.study_2
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.average_illumination_study
      below: 80
    - condition: state
      entity_id: binary_sensor.octoprint_printing
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.study_2
        brightness: 255
    - wait_template: "{{ is_state('binary_sensor.octoprint_printing', 'off') }}"
    - service: light.turn_off
      data:
        entity_id: light.study_2

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: