homeassistant:
  customize:


octoprint:
  host: 192.168.1.206
  api_key: !secret octoprint_api_key
  name: Ender3
  bed: true
  number_of_tools: 2

camera:
  - platform: mjpeg
    name: Ender3
    still_image_url: !secret octoprint_camera_snapshot_url
    mjpeg_url: !secret octoprint_camera_stream_url
  - platform: proxy
    name: ender3_360p
    entity_id: camera.ender3
    max_stream_width: 360
  - platform: proxy
    name: ender3_480p
    entity_id: camera.ender3
    max_stream_width: 480
  - platform: proxy
    name: ender3_720p
    entity_id: camera.ender3
    max_stream_width: 720

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      print_time_remaining_human_readable:
        entity_id: sensor.ender3_time_remaining
        friendly_name: "Print time remaining"
        value_template: >
          {{ (states.sensor.ender3_time_remaining.state|int - 3600) |timestamp_custom(('%H:%M:%S')) }}
      print_elapsed_human_readable:
        entity_id: sensor.ender3_time_elapsed
        friendly_name: "Print time elapsed"
        value_template: >
          {{ (states.sensor.ender3_time_elapsed.state|int - 3600) |timestamp_custom(('%H:%M:%S')) }}
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
- alias: Notify 3D printer done
  trigger:
    - platform: state
      entity_id: binary_sensor.ender3_printing
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
  action:
      - delay: '00:01:00'
      - service: notify.mobile_app_blokmeister_op6
        data:
          title: Printer done
          message: 'Ender 3 print is done'
          data:
            icon: https://b3n.org/wp-content/uploads/2019/11/noun_3D-Printer_2071174-2.png
            image: !secret octoprint_camera_snapshot_url

- alias: Update printer progress
  trigger:
    - platform: time_pattern
      minutes: "0"
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.ender3_printing
      state: 'on'
  action:
      - service: notify.mobile_app_blokmeister_op6
        data_template:
          title: Printer progress
          message: 'Ender 3 print is at {{ states.sensor.ender3_job_percentage.state }}%. Estimated time remaining: {{ states.sensor.ender3_time_remaining.state }}'
          data:
            icon: https://b3n.org/wp-content/uploads/2019/11/noun_3D-Printer_2071174-2.png
            image: !secret octoprint_camera_snapshot_url
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: