homeassistant:
  customize:
    sensor.ender3_time_elapsed:
      device_class: timestamp
    sensor.ender3_time_remaining:
      device_class: timestamp

octoprint:
  host: 192.168.1.206
  api_key: !secret octoprint_api_key
  name: Ender3
  bed: true
  number_of_tools: 2

camera:
  - platform: mjpeg
    name: Ender3
    still_image_url: !secret octoprint_camera_snapshot_url
    mjpeg_url: !secret octoprint_camera_stream_url
  - platform: proxy
    name: ender3_360p
    entity_id: camera.ender3
    max_stream_width: 360
  - platform: proxy
    name: ender3_480p
    entity_id: camera.ender3
    max_stream_width: 480
  - platform: proxy
    name: ender3_720p
    entity_id: camera.ender3
    max_stream_width: 720

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      print_time_remaining_human_readable:
        entity_id: sensor.ender3_time_remaining
        friendly_name: "Print time remaining"
        icon_template: mdi:clock-end
        value_template: >
          {{ (states.sensor.ender3_time_remaining.state|int - 3600) |timestamp_custom(('%H:%M:%S')) }}
      print_elapsed_human_readable:
        entity_id: sensor.ender3_time_elapsed
        friendly_name: "Print time elapsed"
        icon_template: mdi:clock-start
        value_template: >
          {{ (states.sensor.ender3_time_elapsed.state|int - 3600) |timestamp_custom(('%H:%M:%S')) }}
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
- alias: '[ender3|notify]Notify 3D printer done'
  trigger:
    - platform: state
      entity_id: sensor.ender3_current_state
      from: 'printing'
      to: 'operational'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
  action:
      - delay: '00:01:00'
      - service: notify.mobile_app_blokmeister_op6
        data:
          title: Printer done
          message: 'Ender 3 print is done'
          data:
            icon: http://192.168.1.252:8123/local/icons/printer-3d-nozzle.png
            image: !secret octoprint_camera_snapshot_url

- alias: '[ender3|notify] update printer progress'
  trigger:
    - platform: time_pattern
      minutes: "0"
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
    - condition: state
      entity_id: sensor.ender3_current_state
      state: 'printing'
    - condition: state
      entity_id: person.sander_blok
      state: 'not_home'
  action:
      - service: notify.mobile_app_blokmeister_op6
        data_template:
          title: Printer progress
          message: 'Ender 3 print is at {{ states.sensor.ender3_job_percentage.state }}%. Estimated time remaining: {{ states.sensor.ender3_time_remaining.state }}'
          data:
            icon: http://192.168.1.252:8123/local/icons/printer-3d-nozzle.png
            image: !secret octoprint_camera_snapshot_url

- alias: '[ender3|notify] printer overtemp warning'
  trigger:
    - platform: numeric_state
      entity_id: sensor.ender3_actual_tool0_temp
      above: 240
    - platform: numeric_state
      entity_id: sensor.ender3_actual_bed_temp
      above: 120
  action:
      - service: notify.mobile_app_blokmeister_op6
        data_template:
          title: Printer temperature warning
          message: 'Ender 3 temperature is too high! Nozzle temperature: {{ states.sensor.ender3_actual_tool0_temp.state }}. Bed temperature: {{ states.sensor.ender3_actual_bed_temp.state }}'
          data:
            icon: http://192.168.1.252:8123/local/icons/printer-3d-nozzle-alert.png
            image: !secret octoprint_camera_snapshot_url

- alias: '[ender3|lights] turn on light when printer is on'
  trigger:
    - platform: state
      entity_id: sensor.ender3_current_state
      to: 'printing'
    - platform: numeric_state
      entity_id: sensor.average_illumination_study_stats
      below: 80
    - platform: state
      entity_id: light.study_2
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.average_illumination_study_stats
      below: 80
    - condition: state
      entity_id: sensor.ender3_current_state
      state: 'printing'
    - condition: state
      entity_id: light.study_2
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.study_2
        brightness: 255
    - service: switch.flux_study_update

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: