homeassistant:
  customize:
    sensor.ender3_time_elapsed:
      device_class: timestamp
    sensor.ender3_time_remaining:
      device_class: timestamp

camera:
  - platform: mjpeg
    name: Ender3
    still_image_url: !secret octoprint_camera_snapshot_url
    mjpeg_url: !secret octoprint_camera_stream_url
  - platform: proxy
    name: ender3_360p
    entity_id: camera.ender3
    max_stream_height: 360
  - platform: proxy
    name: ender3_480p
    entity_id: camera.ender3
    max_stream_height: 480
  - platform: proxy
    name: ender3_720p
    entity_id: camera.ender3
    max_stream_height: 720

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      print_time_remaining_human_readable:
        friendly_name: "Print time remaining"
        icon_template: mdi:clock-end
        value_template: "{{ ( states( 'sensor.octoprint_print_time_left' )|int - 3600) |timestamp_custom(('%H:%M:%S')) }}"
        availability_template: "{{ states('sensor.octoprint_print_time_left')|is_number }}"
      print_elapsed_human_readable:
        friendly_name: "Print time elapsed"
        icon_template: mdi:clock-start
        value_template: "{{ ( states( 'sensor.octoprint_print_estimated_time' )|int - 3600) |timestamp_custom(('%H:%M:%S')) }}"
        availability_template: "{{ states('sensor.octoprint_print_estimated_time')|is_number }}"

  - platform: command_line
    name: 'OctoPi CPU temp'
    unit_of_measurement: '°C'
    scan_interval: 60
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      pi@octopi.local
      cat /sys/class/thermal/thermal_zone0/temp

  - platform: command_line
    name: 'OctoPi CPU frequency'
    unit_of_measurement: 'MHz'
    scan_interval: 60
    value_template: '{{ value | multiply(0.001) | round(0) }}'
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      pi@octopi.local
      cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
- alias: '[ender3|notify]Notify 3D printer done'
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
  action:
      - delay: '00:01:00'
      - service: notify.mobile_app_blokmeisters21u
        data:
          title: Printer done
          message: 'Ender 3 print is done'
          data:
            image: !secret octoprint_camera_snapshot_url
            group: info
            tag: 3dprinter
            icon_url: local/icons/printer-3d-nozzle.png
            timeout: 1800

- alias: '[ender3|notify] update printer progress'
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_tracking_on
      to: 'off'
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      to: 'on'
    - platform: state
      entity_id: person.sander_blok
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.sleep_tracking_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.octoprint_printing
      state: 'on'
    - condition: state
      entity_id: person.sander_blok
      state: 'not_home'
  action:
    repeat:
      sequence:
        - service: notify.mobile_app_blokmeisters21u
          data:
            title: Printer progress
            message: "Ender 3 print is at {{ states( 'sensor.octoprint_print_progress' ) }}%. Estimated time remaining: {{ states( 'sensor.octoprint_print_time_left' ) }}"
            data:
              image: !secret octoprint_camera_snapshot_url
              group: info
              tag: 3dprinter
              icon_url: local/icons/printer-3d-nozzle.png
              timeout: 1800
        - delay: 00:30:00
      until:
        condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.sleep_tracking_on
            state: 'on'
          - condition: state
            entity_id: binary_sensor.octoprint_printing
            state: 'off'
          - condition: state
            entity_id: person.sander_blok
            state: 'home'

- alias: '[ender3|notify] printer overtemp warning'
  trigger:
    - platform: numeric_state
      entity_id: sensor.octoprint_tool_0_temperature
      above: 240
    - platform: numeric_state
      entity_id: sensor.octoprint_bed_temperature
      above: 120
  action:
      - service: notify.mobile_app_blokmeister_op6_haapp
        data:
          title: Printer temperature warning
          message: "Ender 3 temperature is too high! Nozzle temperature: {{ states( 'sensor.octoprint_tool_0_temperature') }}. Bed temperature: {{ states( 'sensor.octoprint_bed_temperature') }}"
          data:
            image: !secret octoprint_camera_snapshot_url
            group: warning
            tag: 3dprinterovertemp
            icon_url: local/icons/printer-3d-nozzle-alert.png


- alias: '[ender3|lights] turn on light when printer is on'
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.average_illumination_study_2
      below: 50
    - platform: state
      entity_id: light.study_lights
  condition:
    - condition: numeric_state
      entity_id: sensor.average_illumination_study_2
      below: 50
    - condition: state
      entity_id: binary_sensor.octoprint_printing
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.study_2
        brightness: 255
        color_temp: 300
    - wait_template: "{{ is_state('binary_sensor.octoprint_printing', 'off') }}"
    - service: light.turn_on
      data:
        entity_id: light.study_2
        brightness: "{{ state_attr('light.study_1','brightness') }}"
        color_temp: "{{ state_attr('light.study_1','color_temp') }}"


################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  3dprinter_entities:
    entities:
      - binary_sensor.octoprint_connected
      - binary_sensor.octoprint_printing
      - sensor.octoprint_bed_target
      - sensor.octoprint_bed_temperature
      - sensor.octoprint_current_z
      - sensor.octoprint_last_event
      - sensor.octoprint_print_estimated_time
      - sensor.octoprint_print_file
      - sensor.octoprint_print_progress
      - sensor.octoprint_print_status
      - sensor.octoprint_print_time
      - sensor.octoprint_print_time_left
      - sensor.octoprint_slicing_file
      - sensor.octoprint_slicing_progress
      - sensor.octoprint_soc_temperature
      - sensor.octoprint_tool_0_target
      - sensor.octoprint_tool_0_temperature
      - switch.octoprint_cancel_print
      - switch.octoprint_emergency_stop
      - switch.octoprint_pause_print
      - switch.octoprint_shutdown_system
#################
#    SCRIPTS    #
#################
script:
