automation:
  - alias: '[notifications|calendar] Morning Agenda After Wakeup'
    id: yaml_automation_misc_morning_brief_morning_agenda_after_wakeup
    mode: single
    trigger:
      - platform: template
        value_template: >
          {{ is_state('sensor.sleepasandroid_sander', 'sleep_tracking_stopped') or
            is_state('sensor.sleepasandroid_sander', 'alarm_alert_dismiss') or
            is_state('sensor.sleepasandroid_sander', 'alarm_rescheduled')}}
        for:
          minutes: 10

    action:
      - alias: 'Fetch calendar events for next 48h'
        service: calendar.get_events
        target:
          entity_id:
            - calendar.sander_blok_gmail_com
            - calendar.feestdagen_in_nederland
            - calendar.theater
            - calendar.optredens_in_bandsintown
        data:
          duration:
            hours: 48
        response_variable: calendar_events
      - alias: 'Generate ChatGPT agenda summary'
        service: conversation.process
        response_variable: gpt_calendar_response
        data:
          agent_id: conversation.chatgpt_4o_mini
          text: >
            You are a friendly assistant preparing a concise morning briefing based on the user's calendar for the next 48 hours. The user just woke up, and it's currently {{ states('sensor.time') }} local time.

            Create a short, informal summary (max 2 sentences, under 250 chars) for today's and tomorrow's key events.

            Instructions:
            - Clearly state today's earliest event and its start time, emphasizing if it's early (before 11:00 AM).
            - Distinguish clearly between important appointments (meetings, social events, travel) and casual reminders (FYI or all-day events).
            - Prioritize events from calendar.sander_blok_gmail_com.
            - Feel free to translate Dutch event titles to English and interpret them naturally to clearly convey the event's purpose.
            - Mention event titles naturally without awkward wording.
            - Do not use markdown or special formatting—plain text only.
            - Briefly mention if there are no important appointments today.
            - End on a friendly note with a suitable emoji (📅, ☀️, 😄).

            Calendar data:
            {{ calendar_events }}
      - alias: 'Send notification to phone'
        service: notify.mobile_app_blokmeisterp9pro
        data:
          title: "Morning Briefing"
          message: "{{ gpt_calendar_response.response.speech.plain.speech }}"
          data:
            sticky: true
