homeassistant:
  customize:
    automation.asml_badge_reminder:
      icon: mdi:account-badge-alert-outline
#################
#    SENSORS    #
#################
sensor:
- platform: template
  sensors:
    minutes_until_work_starts:
      friendly_name: "Minutes until work starts"
      entity_id: sensor.time
      icon_template: mdi:calendar
      value_template: > 
        {% set e = strptime(states.calendar.asml_werkschema.attributes.start_time,'%Y-%m-%d %H:%M:%S') %}
        {{ ((as_timestamp(e)-as_timestamp(now()))/60) | round(2)}}
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[misc|badge]ASML_badge_reminder'
    trigger: 
      - platform: numeric_state
        entity_id: sensor.minutes_until_work_starts
        below: 40
    condition:
      - condition: state
        entity_id: person.sander_blok
        state: 'home'
      - condition: state
        entity_id: input_boolean.sleep_tracking_on
        state: 'off'
    action:
    - service: tts.google_say
      entity_id: media_player.living_room_speaker
      data:
        message: "Don't forget your ASML badge!."
    - service: notify.mobile_app_blokmeister_op6
      data:
        message: "Don't forget your badge!"
        title: "Reminder"
        data:
          icon: mdi:account-badge-alert-outline
    
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: