#### Shelly defaults: ####
#
# Shelly Plus 2PM
# GPIO_pin: GPIO12 #Relay 1
# GPIO_pin: GPIO13 #Relay 2

defaults:
  relay_id: 'shelly_relay'
  restore_mode: "ALWAYS_ON"
  detached_mode_id: "detach_mode"
  relay_device_name: "${device_name}"

switch:
  - platform: template
    name: "${relay_device_name} Detached Mode"
    icon: mdi:link-variant-off
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: "config"
    id: ${detached_mode_id}
    # turn_on_action:
    #   - lambda: |-
    #       id(${detached_mode_id}).set_icon("mdi:link-variant-off");
    # turn_off_action:
    #   - lambda: |-
    #       id(${detached_mode_id}).set_icon("mdi:link-variant");
  - platform: gpio
    name: "${relay_device_name}"
    pin: ${GPIO_pin} #GPIO4
    id: ${relay_id}
    # After reboot, restore to ON
    restore_mode: ${restore_mode}
