DOMAIN = "open_epaper_link"
SIGNAL_TAG_UPDATE = f"{DOMAIN}_tag_update"
SIGNAL_TAG_IMAGE_UPDATE = f"{DOMAIN}_tag_image_update"
SIGNAL_AP_UPDATE = f"{DOMAIN}_ap_update"
SIGNAL_EXTERNAL_HUB_DISCOVERED = f"{DOMAIN}_external_hub_discovered"
