dlimg:
  name: Download Image
  description: Downloads an image from the web and sends it to an ESL. If it does not fit, the image will be resized
  target:
    entity:
      domain: open_epaper_link
  fields:
    url:
      name: Url
      description: Url of the image to download
      required: true
      example: https://morgenwirdes.de/api/v3/esl1.php?plz=84051
    rotation:
      name: Rotation
      description: Rotation to be applied to the image in degrees
      required: false
      example: 0
    dither:
      name: Dither
      description: Whether the AP should dither the image or not
      required: false
      example: true
      
setled:
  name: Set led color
  description: Sets the led color
  target:
    entity:
      domain: open_epaper_link
  fields:
    color:
      name: Color
      description: color of the led
      required: true
      example: blue
      selector:
        select:
          options:
            - "off"
            - "red"
            - "green"
            - "blue"
            - "yellow"
            - "cyan"
            - "magenta"
            - "white"

drawcustom:
  name: Draw Custom Image
  description: Draws a custom image
  target:
    entity:
      domain: open_epaper_link
  fields:
    payload:
      name: Payload
      description: payload to draw
      required: true
      example: look into supported_types.md for examples
    background:
      name: Backgroundcolor
      description: black, white, red
      required: true
      example: white
    rotate:
      name: rotate
      description: 0, 90, 180, 270
      required: false
      example: 90
    dry-run:
      name: Dry-run
      description: Generate image, but don't send it to the AP.
      required: false
      example: true

lines5:
  name: 5 Line Display
  description: Sets an ESL to display 5 lines of text, only for 1.54", you can double a line by adding a newline char to your text
  target:
    entity:
      domain: open_epaper_link
  fields:
    line1:
      name: Line 1
      description: Line 1 of text to display, 1 new line is allowed
      required: true
      example: Test
    line2:
      name: Line 2
      description: Line 2 of text to display, 1 new line is allowed
      required: true
      example: waylongertext
    line3:
      name: Line 3
      description: Line 3 of text to display, 1 new line is allowed
      required: true
      example: '"Test Text"'
    line4:
      name: Line 4
      description: Line 4 of text to display, 1 new line is allowed
      required: true
      example: left
    line5:
      name: Line 5
      description: Line 5 of text to display, 1 new line is allowed
      required: true
      example: right
    border:
      name: Border
      description: Color of the border
      required: false
      example: r
    format1:
      name: Format string 1
      description: Format string for the first row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: mbbw
    format2:
      name: Format string 2
      description: Format string for the second row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: mwwb
    format3:
      name: Format string 3
      description: Format string for the third row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: mbbw
    format4:
      name: Format string 4
      description: Format string for the fourth row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: lrwb
    format5:
      name: Format string 5
      description: Format string for the fifth row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: rbrr

lines4:
  name: 4 Line Display
  description: Sets an ESL to display 4 lines of text, only for 2.9", you can double a line by adding a newline char to your text
  target:
    entity:
      domain: open_epaper_link
  fields:
    line1:
      name: Line 1
      description: Line 1 of text to display, 1 new line is allowed
      required: true
      example: Test
    line2:
      name: Line 2
      description: Line 2 of text to display, 1 new line is allowed
      required: true
      example: waylongertext
    line3:
      name: Line 3
      description: Line 3 of text to display, 1 new line is allowed
      required: true
      example: '"Test Text"'
    line4:
      name: Line 4
      description: Line 4 of text to display, 1 new line is allowed
      required: true
      example: left
    border:
      name: Border
      description: Color of the border
      required: false
      example: r
    format1:
      name: Format string 1
      description: Format string for the first row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: mbbw
    format2:
      name: Format string 2
      description: Format string for the second row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: mwwb
    format3:
      name: Format string 3
      description: Format string for the third row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: mbbw
    format4:
      name: Format string 4
      description: Format string for the fourth row. Char 1 is for the text alignment, char 2 is for the background color, char 3 is for the border color and char 4 is for the text color
      required: false
      example: lrwb
