homeassistant:
  customize: {}

#################
#    SENSORS    #
#################
sensor:
  # - platform: group
  #   name: "Babyroom Average Illuminance"
  #   unique_id: yaml_sensor_group_babyroom_average_illuminance
  #   type: mean
  #   ignore_non_numeric: true
  #   state_class: measurement
  #   device_class: illuminance
  #   unit_of_measurement: lx
  #   entities:
  #     - sensor.babyroom_motion_1_illuminance
  #     - sensor.babyroom_light_1
  #     - sensor.babyroom_light_1
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[babyroom|light]Toggle lights when switch is pressed'
    id: babyroom_light_toggle_lights_when_switch_is_pressed
    mode: queued
    trigger:
      - platform: event
        event_type: esphome.button_pressed
        event_data:
          device_name: "Shelly Baby Room"
        variables:
          click_count: "{{ trigger.event.data.click_count }}"
    action:
      - service: script.toggle_lights_with_adaptive_brightness
        data:
          light_entity: light.babyroom
          transition_time: 0.5
          click_count: "{{ click_count }}"
      # service: light.toggle
      # data:
      #   entity_id: light.babyroom
      #   brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
      #   color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"

  - alias: "[babyroom|lights]Babyroom Rotary Knob Control"
    mode: queued
    description: Controls the lights in the baby room based on rotary knob actions.
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: babyroom_tap_dial
      - platform: event
        event_type: deconz_relative_rotary_event
        event_data:
          id: hue_tap_dial_switch
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ trigger.event_type == deconz_event }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.event == 1000 }}" #single press
            sequence:
              - service: light.toggle
                data:
                  entity_id: light.babyroom
                  brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
                  color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
          - conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ trigger.event_type == deconz_relative_rotary_event }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.babyroom
                  transition: 0.4
                  brightness_step_pct: "{{ trigger.event.data.rotation/10 }}"
          # - conditions:
          #     - condition: and
          #       conditions:
          #         - condition: template
          #           value_template: "{{ trigger.event_type == deconz_relative_rotary_event }}"
          #   sequence:
          #     - service: light.turn_on
          #       data:
          #         entity_id: light.babyroom
          #         transition: 0.1
          #         brightness_step_pct: "{{ trigger.event.data.rotation/1.5 }}"

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
