homeassistant:
  customize:

input_number:
  bathroom_light_timeout: #in minutes
    name: Bathroom light timeout
    step: 1
    min: 0
    max: 30
    mode: box

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[bathroom|light] turn on light through motion'
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_bathroom
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.sleep_tracking_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.house_occupied
        state: 'on'
    action:
      - choose:
        - conditions:
            - condition: time
              after: '07:00:00'
              before: '21:00:00'
          sequence:
            - service: light.turn_on
              entity_id:
                - light.bathroom_light_bright
                - light.bathroom_light_dim
        - conditions:
            - condition: time
              after: '21:00:00'
              before: '07:00:00'
          sequence:
            - service: light.turn_on
              entity_id:
                - light.bathroom_light_dim
      - wait_for_trigger:
          - platform: template
            value_template: "{{ is_state('binary_sensor.motion_sensor_bathroom', 'off') and states('binary_sensor.hot_water_on')|float == 0 }}"
            for:
              minutes: "{{ states('input_number.bathroom_light_timeout')|int }}"
      - condition: state
        entity_id: light.bathroom_light_dim
        state: 'on'
      - service: light.turn_off
        entity_id: light.bathroom_light_dim
      - delay:
          milliseconds: 300
      - service: light.turn_on
        entity_id: light.bathroom_light_dim
      - delay:
          milliseconds: 300
      - service: light.turn_off
        entity_id: light.bathroom_light_dim
      - delay:
          milliseconds: 300
      - service: light.turn_on
        entity_id: light.bathroom_light_dim
      - delay:
          seconds: 15
      - service: light.turn_off
        entity_id:
          - light.bathroom_light_bright
          - light.bathroom_light_dim

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

################
#    LIGHTS    #
################
light:
  - platform: template
    lights:
      bathroom_light_bright:
        #friendly name: "Bathroom light bright"
        entity_id: switch.shelly_bathroom_1
        value_template: "{{ states.switch.shelly_bathroom_1.state }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.shelly_bathroom_1
        turn_off:
          service: switch.turn_off
          entity_id: switch.shelly_bathroom_1
      bathroom_light_dim:
        #friendly name: "Bathroom light dim"
        entity_id: switch.shelly_bathroom_2
        value_template: "{{ states.switch.shelly_bathroom_2.state }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.shelly_bathroom_2
        turn_off:
          service: switch.turn_off
          entity_id: switch.shelly_bathroom_2


#################
#    SCRIPTS    #
#################
script:

