homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

################
#    LIGHTS    #
################
light:
  - platform: template
    lights:
      bathroom_light_bright:
        #friendly name: "Bathroom light bright"
        entity_id: switch.shelly_bathroom_1
        value_template: "{{ states.switch.shelly_bathroom_1.state }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: switch.shelly_bathroom_1
        turn_off:
          service: homeassistant.turn_off
          entity_id: switch.shelly_bathroom_1
      bathroom_light_dim:
        #friendly name: "Bathroom light dim"
        entity_id: switch.shelly_bathroom_2
        value_template: "{{ states.switch.shelly_bathroom_2.state }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: switch.shelly_bathroom_2
        turn_off:
          service: homeassistant.turn_off
          entity_id: switch.shelly_bathroom_2


#################
#    SCRIPTS    #
#################
script: