homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: turn on closet light when door opens
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_cabinet
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.shelly_closet
  - alias: turn off closet light when door closes
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_cabinet
      to: 'off'
    action:
      service: light.turn_off
      entity_id: light.shelly_closet

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
