homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: "[closet|light] Turn on light when door is opened"
    id: 'closet_light_turn_on_light_when_door_is_opened'
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_cabinet
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.shelly_closet
                  brightness_pct: "{% if is_state('input_boolean.sleep_tracking_on', 'on') %}20{% else %}{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}{% endif %}"
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - service: light.turn_off
                entity_id: light.shelly_closet

  - alias: "[closet|light] Containment turn off light when door is closed"
    id: 'closet_light_containment_turn_off_light_when_door_is_closed'
    mode: restart
    trigger:
      - platform: state
        entity_id: light.shelly_closet
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_cabinet
        state:
          - "off"
          - "unknown"
          - "unavailable"
        for:
          minutes: 5
    action:
      - service: light.turn_off
        entity_id: light.shelly_closet

  # - alias: turn on closet light when door opens
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.door_window_sensor_cabinet
  #     to: 'on'
  #   action:
  #     service: light.turn_on
  #     entity_id: light.shelly_closet

  # - alias: turn off closet light when door closes
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.door_window_sensor_cabinet
  #     to: 'off'
  #   action:
  #     service: light.turn_off
  #     entity_id:
  #       - light.shelly_closet
  #       - light.gateway_light_34ce008c0f6f

  - alias: '[closet|alarm] Alert when closet is open too long'
    mode: restart
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_cabinet
      to: 'on'
      for: 00:05:00
    action:
      repeat:
        sequence:
          # - service: light.turn_on
          #   data:
          #     entity_id: light.gateway_light_34ce008c0f6f
          #     brightness: 255
          #     color_name: red
          - service: tts.cloud_say
            entity_id: media_player.living_room_speaker
            data:
              message: "Closet door is still open. Please close the closet door."
              language: en-IE
          - delay: 00:00:30
        until:
          condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.door_window_sensor_cabinet
              state: 'on'
            - condition: state
              entity_id: automation.closet_alarm_alert_when_closet_is_open_too_long
              state: 'off'

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
