homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: turn on closet light when door opens
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_cabinet
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.shelly_closet

  - alias: turn off closet light when door closes
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_cabinet
      to: 'off'
    action:
      service: light.turn_off
      entity_id: 
        - light.shelly_closet
        - light.gateway_light_34ce008c0f6f

  - alias: '[closet|alarm] Alert when closet is open too long'
    mode: restart
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_cabinet
      to: 'on'
      for: 00:05:00
    action:
      repeat:
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.gateway_light_34ce008c0f6f
              brightness: 255
              color_name: red
          - service: tts.google_say
            entity_id: media_player.living_room_speaker
            data:
              message: "Closet door is still open. Please close the closet door."
          - delay: 00:00:30
        until:
          condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.door_window_sensor_cabinet
              state: 'on'
            - condition: state
              entity_id: automation.closet_alarm_alert_when_closet_is_open_too_long
              state: 'on'

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
