homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: Turn on entry lights through switch press
    trigger:
      platform: state
      entity_id: switch.shelly_entry
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.hallway

  - alias: Turn off entry lights through switch press
    trigger:
      platform: state
      entity_id: switch.shelly_entry
      to: 'off'
    action:
      service: light.turn_off
      entity_id: light.hallway

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: