homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      entry_motion_combined:
        device_class: motion
        value_template: >-
          {{
            is_state('binary_sensor.motion_sensor_entry', 'on') or
            is_state('binary_sensor.motion_sensor_entry2', 'on')
          }}
########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[entry|light]Turn on entry lights through switch press'
    trigger:
      platform: state
      entity_id: switch.shelly_entry
      to: 'on'
    action:
      service: light.turn_on
      data:
        entity_id: light.entry_lights
        brightness: 255

  - alias: '[entry|light]Turn off entry lights through switch press'
    trigger:
      platform: state
      entity_id: switch.shelly_entry
      to: 'off'
    action:
      service: light.turn_off
      entity_id: light.entry_lights

  - alias: '[entry|light] Turn on light through motion'
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.entry_motion_combined
        to: 'on'
    condition:
      condition: sun
      after: sunset
      after_offset: "-01:00:00"
    action:
      - service: light.turn_on
        data:
          entity_id: light.entry_lights
          brightness: 255
      - delay:
          minutes: 5
      - service: light.turn_off
        entity_id: light.entry_lights

  - alias: '[entry|light] Turn off light when no motion is detected'
    trigger:
      # - platform: state
      #   entity_id: binary_sensor.entry_motion_combined
      #   to: 'off'
      #   for: 00:02:00
      - platform: sun
        event: sunrise
        offset: '01:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.entry_motion_combined
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.entry_lights

################
#    SCENES    #
################
scene:

################
#    LIGHTS    #
################
light:
  - platform: template
    lights:
      shelly_entry_light:
        entity_id: switch.shelly_entry
        value_template: "{{ states.switch.shelly_entry.state }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: switch.shelly_entry
        turn_off:
          service: homeassistant.turn_off
          entity_id: switch.shelly_entry
  - platform: group
    name: Entry Lights
    entities:
      - light.shelly_entry_light
      - light.entry_spotlight

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: