homeassistant:
  customize: {}

input_number:
  hallway_1st_floor_illumination_limit:
    name: Hallway 1st Floor illumination limit
    step: 1
    min: 0
    max: 200
    mode: box
  hallway_1st_floor_illumination_limit_lightson:
    name: Hallway 1st Floor illumination limit
    step: 1
    min: 0
    max: 200
    mode: box
  hallway_1st_floor_light_timeout: #in minutes
    name: Hallway 1st Floor light timeout
    step: 1
    min: 0
    max: 30
    mode: box

#################
#    SENSORS    #
#################
sensor:
  - platform: group
    name: "Hallway 1st Floor Average Illuminance"
    unique_id: yaml_sensor_group_hallway_1st_floor_average_illuminance
    type: mean
    ignore_non_numeric: true
    state_class: measurement
    device_class: illuminance
    unit_of_measurement: lx
    entities:
      - sensor.hallway_1st_floor_motion_1_illuminance
      - sensor.hallway_1st_floor_motion_2_illuminance
      - sensor.hallway_1st_floor_light_1
      - sensor.hallway_1st_floor_light_1
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[hallway1stfloor|lights]Toggle lights when switch is pressed'
    id: 'hallway1stfloor_lights_toggle_lights_when_switch_is_pressed'
    mode: restart
    trigger:
      - platform: event
        event_type: esphome.button_pressed
        event_data:
          device_name: "Shelly Hallway 1st Floor"
    condition:
    action:
      - service: light.toggle
        data:
          entity_id: light.hallway_1st_floor
          brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
          kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"

  - alias: '[hallway1stfloor|lights] Turn on lights when motion is detected'
    id: hallway1stfloor_lights_turn_on_lights_when_motion_is_detected
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.hallway_1st_floor_motion_1
          - binary_sensor.hallway_1st_floor_motion_2
        to: 'on'
      - platform: template #going up first stairs
        id: going_up_first_stairs
        value_template: >-
          {{
            (is_state('binary_sensor.entry_motion_1', 'on') or is_state('binary_sensor.entry_motion_2', 'on')) and
            (is_state('binary_sensor.hallway_1st_floor_motion_1', 'off') and is_state('binary_sensor.hallway_1st_floor_motion_2', 'off')) and
            is_state('binary_sensor.stairs_lower_motion_1', 'on')
          }}
      - platform: template #Going down second stairs
        id: going_down_second_stairs
        value_template: >-
          {{
            (is_state('binary_sensor.hallway_2nd_floor_motion_1', 'on') or is_state('binary_sensor.hallway_2nd_floor_motion_2', 'on')) and
            (is_state('binary_sensor.hallway_1st_floor_motion_1', 'off') and is_state('binary_sensor.hallway_1st_floor_motion_2', 'off')) and
            is_state('binary_sensor.stairs_upper_motion_1', 'on')
          }}
    condition:
      - condition: template
        value_template: "{{ states('sensor.hallway_1st_floor_average_illuminance')|int < states('input_number.hallway_1st_floor_illumination_limit')|int }}"
      - condition: state
        entity_id: binary_sensor.house_occupied
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hallway_1st_floor
          brightness: 255
          kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
      - wait_for_trigger:
          - platform: state
            entity_id:
              - binary_sensor.hallway_1st_floor_motion_1
              - binary_sensor.hallway_1st_floor_motion_2
            to: 'off'
            for:
              minutes: "{{ states('input_number.hallway_1st_floor_light_timeout')|int }}"
          - platform: template
            value_template: "{{ states('sensor.hallway_1st_floor_average_illuminance')|int > states('input_number.hallway_1st_floor_illumination_limit_lightson')|int }}"
            for:
              minutes: "{{ states('input_number.hallway_1st_floor_light_timeout')|int }}"
        timeout:
          minutes: "{{ states('input_number.hallway_1st_floor_light_timeout')|int * 2}}"
      - service: light.turn_on
        data:
          entity_id: light.hallway_1st_floor
          brightness_step: -120
          transition: 0.5
      - delay:
          seconds: 15
      - service: light.turn_off
        entity_id: light.hallway_1st_floor
