homeassistant:
  customize:

input_number:
  kitchen_illumination_limit:
    name: Kitchen illumination limit
    step: 1
    min: 0
    max: 200
    mode: box
  kitchen_light_timeout: #in minutes
    name: Kitchen light timeout
    step: 1
    min: 0
    max: 30
    mode: box
#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  # - platform: template
  #   sensors:
  #     scene_kitchen_bright_cool:
  #       device_class: light
  #       value_template: >-
  #         {{ 
  #           states.light.kitchen_lights.attributes.brightness == 254 and 
  #           states.light.kitchen_lights.attributes.color_temp == 320
  #         }}
  #     scene_kitchen_bright_warm:
  #       device_class: light
  #       value_template: >-
  #         {{ 
  #           states.light.kitchen_lights.attributes.brightness == 254 and 
  #           states.light.kitchen_lights.attributes.color_temp == 454 
  #         }}

##################
#    SWITCHES    #
##################
switch:
  # - platform: template
  #   switches:
  #     scene_kitchen_bright_cool:
  #       icon_template: mdi:lightbulb-outline
  #       value_template: "{{ states.binary_sensor.scene_kitchen_bright_cool.state }}"
  #       turn_on:
  #         service: scene.turn_on
  #         entity_id: scene.kitchen_bright_cool
  #       turn_off:
  #         service: light.turn_off
  #         data:
  #           entity_id: light.kitchen_lights
  #           transition: 2
  #     scene_kitchen_bright_warm:
  #       icon_template: mdi:lightbulb-outline
  #       value_template: "{{ states.binary_sensor.scene_kitchen_bright_warm.state }}"
  #       turn_on:
  #         service: scene.turn_on
  #         entity_id: scene.kitchen_bright_warm
  #       turn_off:
  #         service: light.turn_off
  #         data:
  #           entity_id: light.kitchen_lights
  #           transition: 2
  - platform: flux
    name: flux_kitchen
    mode: mired
    disable_brightness_adjust: True
    lights:
      - light.kitchen_lights
#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[kitchen|lights] Turn on lights when motion is detected'
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'on'
    condition:
      # - condition: numeric_state
      #   entity_id: sensor.illumination_kitchen
      #   below: 30
      - condition: template
        value_template: "{{ states('sensor.illumination_kitchen')|int < states('input_number.kitchen_illumination_limit')|int }}"
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights
          brightness: 255
      - service: switch.flux_kitchen_update
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.motion_sensor_kitchen
            to: 'off'
            for:
              minutes: "{{ states('input_number.kitchen_light_timeout')|int }}"
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights
          brightness_step: -120
          transition: 0.5            
      - delay:
          seconds: 15
      - service: light.turn_off
        entity_id: light.kitchen_lights

  # #Turn off kitchen lights if no motion has been detected for 10 minutes
  # - alias: '[kitchen|lights] Turn off when no motion'
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.motion_sensor_kitchen
  #     from: 'on'
  #     to: 'off'
  #     for: 00:10:00
  #   action:
  #     service: light.turn_off
  #     entity_id: light.kitchen

  - alias: '[kitchen|lights]Toggle kitchen lights through switch press'
    mode: restart
    trigger:
      - platform: state
        entity_id: switch.shelly_kitchen
    condition:
      - condition: state
        entity_id: switch.shelly_kitchen
        state:
          - 'on'
          - 'off'
        for:
          seconds: 5
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_lights
          brightness: 255
      - service: switch.flux_study_update
      - service: automation.turn_off
        entity_id:
          - automation.kitchen_lights_turn_on_lights_when_motion_is_detected
      - delay:
          seconds: 30
      - service: automation.turn_on
        entity_id:
          - automation.kitchen_lights_turn_on_lights_when_motion_is_detected

  - alias: '[kitchen|notify] fridge overtemp warning'
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_fridge
        above: 15
    action:
      - service: notify.mobile_app_blokmeister_op6
        data_template:
          title: Fridge temperature warning
          message: 'Fridge temperature too high! Current temperature: {{ states.sensor.temperature_fridge.state }}.'
          icon: http://192.168.1.252:8123/local/icons/thermometer-alert.png
      - service: notify.mobile_app_blokmeister_op6_haapp
        data_template:
          title: Fridge temperature warning
          message: 'Fridge temperature too high! Current temperature: {{ states.sensor.temperature_fridge.state }}.'
          data:
            group: Warning
            tag: fridgetempwarning
            clickAction: '/lovelace/8'
            icon_url: /local/icons/thermometer-alert.png

  - alias: '[kitchen|light] Update illumination limit'
    mode: single
    trigger:
      - platform: state
        entity_id: switch.shelly_kitchen
    condition:
      - condition: state
        entity_id: switch.shelly_kitchen
        state:
          - 'on'
          - 'off'
        for:
          seconds: 5
    action:
      - delay:
          seconds: 1
      - choose:
          - conditions:
              - condition: state
                entity_id: light.kitchen_lights
                state: 'on'
            sequence:
              - service: input_number.increment
                entity_id: input_number.kitchen_illumination_limit
          - conditions:
              - condition: state
                entity_id: light.kitchen_lights
                state: 'off'
            sequence:
              - service: input_number.decrement
                entity_id: input_number.kitchen_illumination_limit
################
#    SCENES    #
################
scene:
  - name: kitchen_bright_cool
    entities:
      light.kitchen_lights:
        state: 'on'
        brightness: 254 
        color_temp: 320 
        transition: 2
  - name: kitchen_bright_warm
    entities:
      light.kitchen_lights:
        state: 'on'
        brightness: 254 
        color_temp: 454 
        transition: 2

################
#    GROUPS    #
################
group:
  kitchen_lighting_automations:
    entities:
      - automation.kitchen_lights_turn_on_lights_when_motion_is_detected
      - automation.kitchen_lights_turn_off_when_no_motion

################
#    LIGHTS    #
################
light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_1
      - light.kitchen_2
      - light.kitchen_3
