homeassistant:
  customize_glob:
    scene.livingroom_*:
      icon: mdi:lightbulb-outline
    automation.livingroom*:
      icon: mdi:lightbulb-outline
    light.*led_strip*:
      icon: mdi:led-strip-variant

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      average_illumination_livingroom:
        device_class: illuminance
        unit_of_measurement: 'lx'
        value_template: "{{ (states('sensor.illumination_livingroom')|int+states('sensor.illumination_livingroom2')|int)/2 }}"
  - platform: statistics
    name: average_illumination_livingroom_stats
    entity_id: sensor.average_illumination_livingroom
    max_age:
      minutes: 30
########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      # scene_livingroom_bright_cool:
      #   device_class: light
      #   value_template: >-
      #     {{
      #       states.light.tvarea_lights.attributes.brightness == 254 and 
      #       states.light.rgb_led_strip_living_room.attributes.brightness == 254 and
      #       states.light.white_led_strip_living_room.attributes.brightness == 254 and
      #       states.light.tvarea_lights.attributes.color_temp == 281 and
      #       states.light.rgb_led_strip_living_room.attributes.color_temp == 342 
      #     }}
      # scene_livingroom_bright_warm:
      #   device_class: light
      #   value_template: >-
      #     {{ 
      #       states.light.tvarea_lights.attributes.brightness == 254 and 
      #       states.light.rgb_led_strip_living_room.attributes.brightness == 254 and
      #       states.light.white_led_strip_living_room.attributes.brightness == 254 and
      #       states.light.tvarea_lights.attributes.color_temp == 399 and
      #       states.light.rgb_led_strip_living_room.attributes.color_temp == 389 
      #     }}
      # scene_livingroom_warm_atmosphere:
      #   device_class: light
      #   value_template: >-
      #     {{
      #       states.light.tvarea_lights.attributes.brightness == 115 and 
      #       states.light.rgb_led_strip_living_room.attributes.brightness > 39 and
      #       states.light.rgb_led_strip_living_room.attributes.brightness < 45 and
      #       states.light.white_led_strip_living_room.attributes.brightness == 28 and
      #       states.light.tvarea_lights.attributes.color_temp == 500 and
      #       states.light.rgb_led_strip_living_room.attributes.xy_color == (0.598, 0.386) 
      #     }}
      # scene_movie_time:
      #   device_class: light
      #   value_template: >-
      #     {{ 
      #       states.light.tvarea_lights.state == 'off' and 
      #       states.light.rgb_led_strip_living_room.attributes.brightness > 39 and
      #       states.light.rgb_led_strip_living_room.attributes.brightness < 45 and
      #       states.light.white_led_strip_living_room.attributes.brightness == 28 and
      #       states.light.tvarea_lights.attributes.color_temp == 500 and
      #       states.light.rgb_led_strip_living_room.attributes.xy_color == (0.598, 0.386) 
      #     }}
      livingroom_motion_combined:
        device_class: motion
        value_template: >-
          {{
            is_state('binary_sensor.motion_sensor_livingroom', 'on') or
            is_state('binary_sensor.motion_sensor_livingroom2', 'on') or
            is_state('binary_sensor.motion_sensor_livingroom3', 'on')
          }}

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:
  # - platform: template
  #   switches:
  #     scene_livingroom_bright_cool:
  #       icon_template: mdi:lightbulb-outline
  #       value_template: "{{ states.binary_sensor.scene_livingroom_bright_cool.state }}"
  #       turn_on:
  #         service: scene.turn_on
  #         entity_id: scene.livingroom_bright_cool
  #       turn_off:
  #         service: light.turn_off
  #         data:
  #           entity_id: light.living_room
  #           transition: 2
  #     scene_livingroom_bright_warm:
  #       icon_template: mdi:lightbulb-outline
  #       value_template: "{{ states.binary_sensor.scene_livingroom_bright_warm.state }}"
  #       turn_on:
  #         service: scene.turn_on
  #         entity_id: scene.livingroom_bright_warm
  #       turn_off:
  #         service: light.turn_off
  #         data:
  #           entity_id: light.living_room
  #           transition: 2
  #     scene_livingroom_warm_atmosphere:
  #       icon_template: mdi:lightbulb-outline
  #       value_template: "{{ states.binary_sensor.scene_livingroom_warm_atmosphere.state }}"
  #       turn_on:
  #         service: scene.turn_on
  #         entity_id: scene.livingroom_warm_atmosphere
  #       turn_off:
  #         service: light.turn_off
  #         data:
  #           entity_id: light.living_room
  #           transition: 2
  #     scene_movie_time:
  #       icon_template: mdi:lightbulb-outline
  #       value_template: "{{ states.binary_sensor.scene_movie_time.state }}"
  #       turn_on:
  #         service: scene.turn_on
  #         entity_id: scene.movie_time
  #       turn_off:
  #         service: light.turn_off
  #         data:
  #           entity_id: light.living_room
  #           transition: 2
  - platform: flux
    name: flux_livingroom
    mode: mired
    disable_brightness_adjust: True
    transition: 30
    lights:
      - light.tvarea_and_ledstrips

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[livingroom|light] Flux light through motion'
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_motion_combined
        to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.average_illumination_livingroom
        below: 30
    action:
      - service: light.turn_on
        data:
          entity_id: 
            - light.tvarea_and_ledstrips
          brightness: 255
      - service: switch.flux_livingroom_update
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.livingroom_motion_combined
            to: 'off'
            for:
              minutes: 10
      - service: light.turn_on
        data:
          entity_id:
            - light.tvarea_and_ledstrips
          brightness: 140
          transition: 0.5
      - delay:
          seconds: 30
      - service: light.turn_off
        entity_id:
          - light.tvarea_and_ledstrips

  - alias: '[livingroom|light] Shelly toggle lights'
    mode: restart
    trigger:
      - platform: state
        entity_id: switch.shelly_mediacenter
    condition:
      - condition: state
        entity_id: switch.shelly_mediacenter
        state:
          - 'on'
          - 'off'
        for:
          seconds: 5
    action:
      - service: light.toggle
        data:
          entity_id: light.tvarea_and_ledstrips
          brightness: 255
      - service: switch.flux_livingroom_update
      - service: automation.turn_off
        entity_id:
          - automation.livingroom_light_flux_light_through_motion
      - delay:
          seconds: 30
      - service: automation.turn_on
        entity_id:
          - automation.livingroom_light_flux_light_through_motion

################
#    SCENES    #
################
scene:
  - name: livingroom_bright_cool
    entities:
      light.tvarea_lights:
        state: 'on'
        brightness: 254 
        color_temp: 281 
        transition: 2
      light.rgb_led_strip_living_room:
        state: 'on'
        brightness: 254
        color_temp: 342
        transition: 2
      light.white_led_strip_living_room:
        state: 'on'
        brightness: 254
        transition: 2
  - name: livingroom_bright_warm
    entities:
      light.tvarea_lights:
        state: 'on'
        brightness: 254 
        color_temp: 399 
        transition: 2
      light.rgb_led_strip_living_room:
        state: 'on'
        brightness: 254
        color_temp: 389
        transition: 2
      light.white_led_strip_living_room:
        state: 'on'
        brightness: 254
        transition: 2
  - name: livingroom_warm_atmosphere
    entities:
      light.tvarea_lights:
        state: 'on'
        brightness: 115 
        color_temp: 500 
        transition: 2
      light.rgb_led_strip_living_room:
        state: 'on'
        brightness: 42
        xy_color: [0.598,0.386]
        transition: 2
      light.white_led_strip_living_room:
        state: 'on'
        brightness: 28
        transition: 2
  - name: movie_time
    entities:
      light.tvarea_lights:
        state: 'off'
        transition: 2
      light.rgb_led_strip_living_room:
        state: 'on'
        brightness: 42
        xy_color: [0.598,0.386]
        transition: 2
      light.white_led_strip_living_room:
        state: 'on'
        brightness: 28
        transition: 2

################
#    GROUPS    #
################
group:
  livingroom_lighting_automations:
    entities:
      - automation.livingroom_light_flux_light_through_motion
  livingroom_scenes:
    entities:
      - scene.livingroom_bright_cool
      - scene.livingroom_bright_warm
      - scene.livingroom_warm_atmosphere
      - scene.movie_time
  livingroom_motion_sensors:
    entities:
      - binary_sensor.motion_sensor_livingroom
      - binary_sensor.motion_sensor_livingroom2
      - binary_sensor.motion_sensor_livingroom3

################
#    LIGHTS    #
################
light:
  - platform: group
    name: TVarea_Lights
    entities:
      - light.hue_color_spot_1
      - light.hue_color_spot_2
      - light.hue_color_spot_3
      - light.hue_color_spot_4
      - light.hue_color_spot_5
  - platform: group
    name: TVarea_and_LEDstrips
    entities:
      - light.tvarea_lights
      - light.livingroom_led_strip
  - platform: group
    name: Livingroom lights noplants
    entities:
      - light.tvarea_lights
      - light.shelly_dinner_table
  - platform: group
    name: Livingroom lights
    entities:
      - light.livingroom_lights_noplants
      - light.plants

#################
#    SCRIPTS    #
#################
script:
