homeassistant:
  customize_glob:
    scene.livingroom_*:
      icon: mdi:lightbulb-outline
    automation.livingroom*:
      icon: mdi:lightbulb-outline
    light.*led_strip*:
      icon: mdi:led-strip-variant

input_number:
  livingroom_illumination_limit:
    name: Livingroom illumination limit
    step: 1
    min: 0
    max: 200
    mode: box
  livingroom_light_timeout: #in minutes
    name: Livingroom light timeout
    step: 1
    min: 0
    max: 30
    mode: box
  living_room_light_illumination_difference:
    name: Living Room Light Illumination Difference
    min: 0
    max: 500
    step: 1
    unit_of_measurement: "lx"
    mode: box
    icon: mdi:brightness-auto

input_select:
  livingroom_scenes:
    options:
      - bright_cool
      - bright_warm
      - warm_atmosphere
    initial: bright_warm
    icon: mdi:lightbulb-on-outline

#################
#    SENSORS    #
#################
sensor:
  # - platform: group
  #   name: "Livingroom Average Illuminance"
  #   unique_id: yaml_sensor_group_livingroom_average_illuminance
  #   type: mean
  #   ignore_non_numeric: true
  #   state_class: measurement
  #   device_class: illuminance
  #   unit_of_measurement: lx
  #   entities:
  #     - sensor.livingroom_motion_1_illuminance
  #     - sensor.livingroom_motion_2_illuminance
  #     - sensor.livingroom_light_1
  #     - sensor.livingroom_light_1

  # - platform: min_max
  #   type: mean
  #   name: "Livingroom Average Illuminance MinMax"
  #   round_digits: 0
  #   entity_ids:
  #     - sensor.livingroom_motion_1_illuminance
  #     - sensor.livingroom_motion_2_illuminance
  #     - sensor.livingroom_light_1
  #     - sensor.livingroom_light_1
########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      livingroom_motion_combined:
        friendly_name: "Living Room Combined Motion"
        unique_id: yaml_template_binary_sensor_livingroom_motion_combined
        device_class: motion
        icon_template: mdi:motion-sensor
        value_template: >-
          {{
            is_state('binary_sensor.livingroom_motion_1', 'on') or
            is_state('binary_sensor.livingroom_motion_2', 'on') or
            is_state('binary_sensor.livingroom_motion_3', 'on')
          }}
        availability_template: >-
          {{
            (states('binary_sensor.livingroom_motion_1') in ['on', 'off']) and
            (states('binary_sensor.livingroom_motion_2') in ['on', 'off']) and
            (states('binary_sensor.livingroom_motion_3') in ['on', 'off'])
          }}

########################
#    INPUT BOOLEANS    #
########################
input_boolean:
  livingroom_light_level_calibration_switch:
    name: Livingroom Light Level Calibration
    initial: off
    icon: mdi:lightbulb-on-outline  # Just a nice icon for the UI

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[livingroom|lights] Turn on lights when motion is detected'
    id: livingroom_lights_turn_on_lights_when_motion_is_detected
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.livingroom_motion_1
          - binary_sensor.livingroom_motion_2
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ states('sensor.livingroom_light_1')|int(1000) < states('input_number.livingroom_illumination_limit')|int }}"
      - condition: state
        entity_id: binary_sensor.house_occupied
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room
          brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
          color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
      - wait_for_trigger:
          - platform: state
            entity_id:
              - binary_sensor.livingroom_motion_1
              - binary_sensor.livingroom_motion_2
            to: 'off'
            for:
              minutes: "{{ states('input_number.livingroom_light_timeout')|int }}"
          - platform: template
            value_template: "{{ (states('sensor.livingroom_light_1')|int(0) - states('input_number.living_room_light_illumination_difference')|int(0)) > states('input_number.livingroom_illumination_limit')|int }}"
            for:
              minutes: "{{ states('input_number.livingroom_light_timeout')|int }}"
      - service: light.turn_on
        data:
          entity_id: light.living_room
          brightness_step: -120
          transition: 0.5
      - delay:
          seconds: 15
      - service: light.turn_off
        entity_id: light.living_room

  - alias: '[livingroom|light] Toggle lights when switch is pressed'
    id: livingroom_light_toggle_lights_when_switch_is_pressed
    mode: restart
    trigger:
      - platform: event
        event_type: esphome.button_pressed
        event_data:
          device_name: "Shelly Living Room"
        variables:
          click_count: "{{ trigger.event.data.click_count }}"
    action:
      - service: script.toggle_lights_with_adaptive_brightness
        data:
          light_entity: light.living_room
          transition_time: 0.5
          click_count: "{{ click_count }}"

  - alias: '[livingroom|light]Automate light string based on sunset'
    id: livingroom_light_automate_light_string_based_on_sunset
    mode: single
    trigger:
      - platform: sun
        event: sunset
        id: "turn_on"
      - platform: time
        at: "22:45"
        id: "turn_off"
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'turn_on' }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.livingroom_light_string
                  brightness: 255
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'turn_off' }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: light.livingroom_light_string

  - alias: '[areas|livingroom] Light Calibration Automation'
    id: yaml_automation_areas_livingroom_light_calibration_automation
    description: Automates light on/off cycle for calibration and resets input boolean
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.livingroom_light_level_calibration_switch
        to: 'on'  # Starts the automation when the boolean is turned on
    variables:
      repeat_count: 20  # Number of on/off cycles
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_adapt_brightness_adaptive_lighting
          manual_control: true
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_adapt_color_adaptive_lighting
          manual_control: true
      - repeat:
          count: '{{ repeat_count }}'
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.living_room
              data_template:
                brightness_pct: "{{ range(20, 101) | random }}"  # Random brightness between 20% and 100%
                color_temp: "{{ range(2000, 6536) | random }}"  # Random color temperature between 2000K and 6535K
            - delay:
                minutes: 15  # Wait 15 minutes with the lights on
            - service: light.turn_off
              target:
                entity_id: light.living_room
            - delay:
                minutes: 15  # Wait 15 minutes with the lights off
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_adapt_brightness_adaptive_lighting
          manual_control: false
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_adapt_color_adaptive_lighting
          manual_control: false
      - service: input_boolean.turn_off  # Turn off the boolean to reset
        target:
          entity_id: input_boolean.livingroom_light_level_calibration_switch

  - alias: "[livingroom|lights] Sync ledstrip_falcon state with livingroom light"
    id: yaml_automation_livingroom_lights_sync_ledstrip_falcon_state_with_livingroom_light
    description: >
      Whenever light.livingroom is turned on or off, mirror its state to light.ledstrip_falcon,
      but only if its effect is NOT 'E1.31'. Uses adaptive lighting settings when turning on.
    mode: restart
    trigger:
      - platform: state
        entity_id: light.living_room
        to:
          - 'on'
          - 'off'
    condition:
      - condition: template
        value_template: >
          {{ not is_state_attr('light.ledstrip_falcon', 'effect', 'E1.31') }}
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.ledstrip_falcon
                data:
                  brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
                  color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.ledstrip_falcon


  # - alias: '[livingroom|light] Update illumination limit'
  #   mode: single
  #   trigger:
  #     - platform: state
  #       entity_id: switch.shelly_mediacenter
  #   condition:
  #     - condition: state
  #       entity_id: switch.shelly_mediacenter
  #       state:
  #         - 'on'
  #         - 'off'
  #       for:
  #         seconds: 5
  #   action:
  #     - delay:
  #         seconds: 1
  #     - choose:
  #         - conditions:
  #             - condition: state
  #               entity_id: light.tvarea_and_ledstrips
  #               state: 'on'
  #           sequence:
  #             - service: input_number.increment
  #               entity_id: input_number.livingroom_illumination_limit
  #         - conditions:
  #             - condition: state
  #               entity_id: light.tvarea_and_ledstrips
  #               state: 'off'
  #           sequence:
  #             - service: input_number.decrement
  #               entity_id: input_number.livingroom_illumination_limit

################
#    SCENES    #
################
scene:
  - name: livingroom_bright_cool
    entities:
      light.living_room:
        state: 'on'
        brightness: 254
        color_temp: 281
        transition: 2
      # light.rgb_led_strip_living_room:
      #   state: 'on'
      #   brightness: 254
      #   color_temp: 342
      #   transition: 2
      # light.white_led_strip_living_room:
      #   state: 'on'
      #   brightness: 254
      #   transition: 2
  - name: livingroom_bright_warm
    entities:
      light.living_room:
        state: 'on'
        brightness: 254
        color_temp: 399
        transition: 2
      # light.rgb_led_strip_living_room:
      #   state: 'on'
      #   brightness: 254
      #   color_temp: 389
      #   transition: 2
      # light.white_led_strip_living_room:
      #   state: 'on'
      #   brightness: 254
      #   transition: 2
  - name: livingroom_warm_atmosphere
    entities:
      light.living_room:
        state: 'on'
        brightness: 115
        color_temp: 500
        transition: 2
      # light.rgb_led_strip_living_room:
      #   state: 'on'
      #   brightness: 42
      #   xy_color: [0.598,0.386]
      #   transition: 2
      # light.white_led_strip_living_room:
      #   state: 'on'
      #   brightness: 28
      #   transition: 2
  # - name: movie_time
  #   entities:
  #     light.living_room:
  #       state: 'off'
  #       transition: 2
      # light.rgb_led_strip_living_room:
      #   state: 'on'
      #   brightness: 42
      #   xy_color: [0.598,0.386]
      #   transition: 2
      # light.white_led_strip_living_room:
      #   state: 'on'
      #   brightness: 28
      #   transition: 2

################
#    GROUPS    #
################
group:
  # livingroom_lighting_automations:
  #   entities:
  #     - automation.livingroom_light_flux_light_through_motion
  # livingroom_scenes:
  #   entities:
  #     - scene.livingroom_bright_cool
  #     - scene.livingroom_bright_warm
  #     - scene.livingroom_warm_atmosphere
  #     - scene.movie_time
  # livingroom_motion_sensors:
  #   entities:
  #     - binary_sensor.motion_sensor_livingroom
  #     - binary_sensor.motion_sensor_livingroom2
  #     - binary_sensor.motion_sensor_livingroom3
  #     - binary_sensor.tapo_camera_d6d4_motion

################
#    LIGHTS    #
################
light:
  # - platform: group
  #   name: TVarea_Lights
  #   entities:
  #     - light.tvarea_1
  #     - light.tvarea_2
  #     - light.tvarea_3
  #     - light.tvarea_4
  #     - light.tvarea_5
  # - platform: group
  #   name: TVarea_and_LEDstrips
  #   entities:
  #     - light.tvarea_lights
  #     - light.livingroom_a_rgb_ledstrip
  # - platform: group
  #   name: Livingroom lights noplants
  #   entities:
  #     - light.tvarea_and_ledstrips
  #     - light.shelly_dinner_table
  # - platform: group
  #   name: Livingroom lights
  #   entities:
  #     - light.livingroom_lights_noplants
  #     - light.plants

#################
#    SCRIPTS    #
#################
script:
