homeassistant:
  customize:

media_player:
  - platform: plex
    entity_namespace: 'plex'
    scan_interval: 5
    show_all_controls: true
    use_episode_art: true
    remove_unavailable_clients: true
    client_remove_interval: 600
  - platform: kodi
    host: 192.168.1.50
    name: CoreELEC
    # username: !secret coreelec_user
    # password: !secret coreelec_pass
    turn_on_action:
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate
    turn_off_action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: standby
  - platform: kodi
    host: 192.168.1.51
    name: Ambilight_RPI

#################
#    SENSORS    #
#################
sensor:
  - platform: command_line
    name: 'CoreELEC CPU temp'
    # friendly_name: 'CoreELEC CPU temp'
    unit_of_measurement: '°C'
    scan_interval: 60
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      root@coreelec
      cputemp | awk '{print $1}'

  - platform: command_line
    name: 'CoreELEC GPU temp'
    # friendly_name: 'CoreELEC GPU temp'
    unit_of_measurement: '°C'
    scan_interval: 60
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      root@coreelec
      gputemp | awk '{print $1}'

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      mediacenter_on:
        device_class: power
        value_template: >-
          {{
            states.sensor.blitzwolf_mediacenter_energy_power.state|float > 200
          }}
##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:

################
#    LIGHTS    #
################
light: