homeassistant:
  customize: {}

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[porch|light]Automate light based on sunset'
    id: porch_light_automate_light_based_on_sunset
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
        id: "turn_on"
      - platform: time
        at: "22:45"
        id: "turn_off"
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'turn_on' }}"
              - condition: time
                before: "22:45"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.shelly_porch
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'turn_off' }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: light.shelly_porch
      # - delay:
      #     minutes: 90
      # - wait_for_trigger:
      #     - platform: template
      #       value_template: >-
      #         {{ now() > today_at("23:00") }}
      #     - platform: time
      #       at: "23:59:00"
      #   timeout:
      #     minutes: 180
      # - service: light.turn_off
      #   data:
      #     entity_id: light.shelly_porch

  - alias: "[porch|light] Turn on at 06:00 if before sunrise, off 10 min after sunrise"
    id: yaml_automation_porch_light_turn_on_0600_if_before_sunrise_off_10_min_after_sunrise
    description: "Turns porch light on at 06:00 only if it's still dark; turns it off 10 minutes after sunrise."
    mode: single
    trigger:
      - platform: time
        at: "06:00:00"
        id: turn_on
      - platform: sun
        event: sunrise
        offset: "00:10:00"
        id: turn_off
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'turn_on' }}"
              - condition: sun
                before: sunrise
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.shelly_porch
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'turn_off' }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.shelly_porch

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
