homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      average_illumination_study:
        device_class: illuminance
        unit_of_measurement: 'lx'
        value_template: "{{ (states('sensor.illumination_study')|int+states('sensor.illumination_study2')|int) }}"
      vibration_sensor_attributes:
        value_template: "{{ state_attr('binary_sensor.vibration_sensor', 'orientation'), state_attr('binary_sensor.vibration_sensor', 'tiltangle') }}"
  - platform: statistics
    name: average_illumination_study_stats
    entity_id: sensor.average_illumination_study
    max_age:
      minutes: 30

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      scene_study_bright_cool:
        device_class: light
        value_template: >-
          {{ 
            states.light.study.attributes.brightness == 254 and 
            states.light.study.attributes.color_temp == 280 
          }}
      scene_study_bright_warm:
        device_class: light
        value_template: >-
          {{ 
            states.light.study.attributes.brightness == 254 and 
            states.light.study.attributes.color_temp == 454
          }}
      computer_on:
        device_class: power
        value_template: >-
          {{
            states.sensor.blitzwolf_computer_energy_power.state|float > 100
          }}
      study_motion_combined:
        device_class: motion
        value_template: >-
          {{
            is_state('binary_sensor.motion_sensor_study', 'on') or
            is_state('binary_sensor.motion_sensor_study_2', 'on')
          }}

##################
#    SWITCHES    #
##################
switch:
  - platform: template
    switches:
      scene_study_bright_cool:
        icon_template: mdi:lightbulb-outline
        value_template: "{{ states.binary_sensor.scene_study_bright_cool.state }}"
        turn_on:
          service: scene.turn_on
          entity_id: scene.study_bright_cool
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.study
            transition: 2
      scene_study_bright_warm:
        icon_template: mdi:lightbulb-outline
        value_template: "{{ states.binary_sensor.scene_study_bright_warm.state }}"
        turn_on:
          service: scene.turn_on
          entity_id: scene.study_bright_warm
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.study
            transition: 2
  - platform: flux
    name: flux_study
    mode: mired
    disable_brightness_adjust: True
    transition: 30
    lights:
      - light.study_1
      - light.study_2
      - light.study_3
      - light.study_candle

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[study|lights] Turn on lights when motion is detected'
    trigger:
      - platform: state
        entity_id: binary_sensor.study_motion_combined
        to: 'on'
      - platform: state
        entity_id: sensor.vibration_sensor_attributes
      - platform: state
        entity_id: binary_sensor.vibration_sensor
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
        - condition: sun
          before: sunrise
          before_offset: "01:00:00"
        - condition: numeric_state
          entity_id: sensor.average_illumination_study_stats
          below: 80
    action:
      - service: light.turn_on
        data:
          entity_id: light.study_lights
          brightness: 255
      - service: switch.flux_study_update

  #Turn on study lights when motion is detected cool
  # - alias: study_motion_bright_cool
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.motion_sensor_study2
  #       to: 'on'
  #   condition:
  #     - condition: time
  #       after: '7:00:00'
  #       before: '19:00:00'
  #     - condition: sun
  #       after: sunset
  #       after_offset: "-01:00:00"
  #   action:
  #     service: scene.turn_on
  #     entity_id: scene.study_bright_cool

  #Turn on study lights when motion is detected warm
  # - alias: study_motion_bright_warm
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.motion_sensor_study2
  #     to: 'on'
  #   condition:
  #     - condition: time
  #       after: '19:00:00'
  #       before: '6:00:00'
  #     - condition: sun
  #       after: sunset
  #       after_offset: "-01:00:00"
  #   action:
  #     service: scene.turn_on
  #     entity_id: scene.study_bright_warm

  - alias: '[study|lights] Auto lights off'
    trigger:
      - platform: state
        entity_id: binary_sensor.study_motion_combined
        to: 'off'
        for: 00:10:00
      - platform: template
        value_template: "{{ (as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.sensor.vibration_sensor_attributes.last_changed)) > 600  }}"
      - platform: state
        entity_id: binary_sensor.vibration_sensor
        to: 'off'
        for: 00:10:00
    condition:
      - condition: template
        value_template: "{{ (as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.sensor.vibration_sensor_attributes.last_changed)) > 300  }}"
      - condition: state
        entity_id: binary_sensor.vibration_sensor
        state: 'off'
        for: 00:05:00
      - condition: state
        entity_id: binary_sensor.study_motion_combined
        state: 'off'
        for: 00:10:00
    action:
      service: light.turn_off
      entity_id: light.study_lights

  #Turn off study lights if no motion has been detected for 10 minutes
  - alias: study_nomotion_nopc_turn_off
    trigger:
      - platform: state
        entity_id: binary_sensor.study_motion_combined
        to: 'off'
        for: 00:05:00
      - platform: state
        entity_id: binary_sensor.study_motion_combined
        to: 'off'
        for: 00:10:00
      - platform: state
        entity_id: binary_sensor.study_motion_combined
        to: 'off'
        for: 00:15:00
      - platform: state
        entity_id: binary_sensor.blokmeisterdesktop
        to: 'off'
      - platform: state
        entity_id: binary_sensor.computer_on
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.study_motion_combined
          state: 'off'
          #for: 00:01:00
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.blokmeisterdesktop
              state: 'off'
            - condition: state
              entity_id: binary_sensor.computer_on
              state: 'off'
    action:
      service: light.turn_off
      entity_id: light.study

  #Turn off study lights if no motion has been detected for 1 hour
  - alias: study_nomotion_pc_turn_off
    trigger:
      platform: state
      entity_id: binary_sensor.study_motion_combined
      from: 'on'
      to: 'off'
      for: 01:00:00
    action:
      service: light.turn_off
      entity_id: light.study

  - alias: 'Turn scene to warm at 19:00'
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.scene_study_bright_cool
        state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.study_bright_warm

  - alias: 'Message when computer is still on when not home'
    trigger:
      - platform: state
        entity_id: person.sander_blok
        from: 'home'
        to: 'not_home'
        for: 00:20:00
    condition:
      - condition: state
        entity_id: binary_sensor.computer_on
        state: 'on'
    action:
      - service: notify.mobile_app_blokmeister_op6
        data:
          message: "Computer still draws power: {{ states.sensor.blitzwolf_computer_energy_power.state }}W"
          title: "Home Assistant - Computer on"
          data:
            icon: http://192.168.1.252:8123/local/icons/desktop-tower-monitor.png

  - alias: '[study|lights]Toggle lights through switch press'
    trigger:
      platform: state
      entity_id: switch.shelly_study
    action:
      - service: light.toggle
        entity_id: light.study
      - condition: state
        entity_id: light.study
        state: 'on'
      - service: light.turn_on
        data:
          entity_id: light.study
          brightness: 255
      - service: switch.flux_study_update
################
#    SCENES    #
################
scene:
  - name: study_bright_cool
    entities:
      light.study_lights:
        state: on
        brightness: 254 
        color_temp: 280 
        transition: 2
  - name: study_bright_warm
    entities:
      light.study_lights:
        state: on
        brightness: 254 
        color_temp: 454 
        transition: 2

################
#    GROUPS    #
################
group:
  study_lighting_automations:
    entities:
      - automation.study_motion_bright_cool
      - automation.study_motion_bright_warm
      - automation.study_nomotion_nopc_turn_off
      - automation.study_nomotion_pc_turn_off

################
#    LIGHTS    #
################
light:
  - platform: group
    name: Study Lights
    entities:
      - light.study_1
      - light.study_2
      - light.study_3
      - light.study_candle