homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[toilet|notification] Notify when motion is detected'
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_toilet
        to: 'on'
    condition:
      - condition: state
        entity_id: person.sander_blok
        state: 'home'
    action:
      - service: notify.mobile_app_blokmeister_op6
        data:
          message: "Motion detected on toilet"
          title: "Toilet motion"
          data:
            icon: http://192.168.1.252:8123/local/icons/toilet.png
            tag: 3
      - service: notify.mobile_app_blokmeister_op6_haapp
        data:
          message: "Motion detected on toilet"
          title: "Toilet motion"
          data:
            group: Warning
            tag: toiletmotion
            icon_url: local/icons/toilet.png
            timeout: 300
      - delay:
          minutes: 5

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
