homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[washroom|light]Turn on light when door is opened'
    id: washroom_light_turn_on_light_when_door_is_opened
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.washroom_door_sensor
        not_from:
          - "unknown"
          - "unavailable"
    action:
      - choose: #If door is opened, turn on light, if it is closed, turn off
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: switch.turn_on
              data:
                entity_id: switch.shelly_washroom
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: switch.turn_off
              data:
                entity_id: switch.shelly_washroom
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
