homeassistant:
  customize: {}

command_line:
  - switch:
      name: Washing Machine
      command_on: !secret washing_machine_start_command
      command_off: !secret washing_machine_stop_command
#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[washroom|light]Turn on light when door is opened'
    id: washroom_light_turn_on_light_when_door_is_opened
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.washroom_door_sensor
        not_from:
          - "unknown"
          - "unavailable"
    action:
      - choose: #If door is opened, turn on light, if it is closed, turn off
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: switch.turn_on
              data:
                entity_id: switch.shelly_washroom
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: switch.turn_off
              data:
                entity_id: switch.shelly_washroom

  - alias: "[washroom|leak]Warn Washing Machine Leak"
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_leak_sensor
        to: "on"  # Water detected
    condition: []
    action:
      - service: notify.sander_and_tamara_phones
        data:
          message: >-
            Warning: Water detected under the washing machine!
            Detector state: {{ states('binary_sensor.washing_machine_leak_sensor') }} since {{ states.binary_sensor.washing_machine_leak_sensor.last_changed.strftime('%Y-%m-%d %H:%M:%S') }}.
            Please check immediately to prevent damage.
          title: "Washing Machine Leak Alert"
          data:
            ttl: 0
            sticky: "true"
            clickAction: "/config/devices/device/c17a7e5ae9db356e4fa58009b762b291"
            priority: high
            tag: washing_machine_leak
            group: "water_leak_alert"
            notification_icon: "mdi:water-alert"
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.washing_machine_leak_sensor
            to: "off"  # No water detected
            for:
              hours: 12
      - service: notify.sander_and_tamara_phones
        data:
          message: "clear_notification"
          data:
            ttl: 0
            priority: high
            tag: washing_machine_leak

  - alias: "[washroom|notify] Washing machine progress bar notification"
    id: yaml_automation_washroom_notify_washing_machine_progress_bar_notification
    description: "Show a sticky progress bar notification for the washing machine on Android"
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.washer_washer_machine_state
        from:
          - 'Stopped'
          - 'stop'
        to: 'run'
    variables:
      start_time: "{{ now().isoformat() }}"
    action:
      - alias: "Start progress bar loop"
        repeat:
          while:
            - condition: state
              entity_id: sensor.washer_washer_machine_state
              state: "run"
          sequence:
            - variables:
                end_time: "{{ as_datetime(states('sensor.washer_washer_completion_time')).astimezone() }}"
                progress: >
                  {% set elapsed = (now() - as_datetime(start_time)).total_seconds() / 60 %}
                  {{ elapsed | round(0) }}
                progress_max: >
                  {% set total = (as_datetime(end_time) - as_datetime(start_time)).total_seconds() / 60 %}
                  {% if total > 0 %}{{ total | round(0) }}{% else %}1{% endif %}
                percent_done: >
                  {% if progress_max|float(0) > 0 %}
                    {{ ((progress|float / progress_max|float) * 100) | round(0) }}
                  {% else %}
                    0
                  {% endif %}
            - service: notify.sander_and_tamara_phones
              continue_on_error: true
              data:
                title: "Washing Machine Progress"
                message: >
                  🧺 Laundry in progress: {{ progress|int }} / {{ progress_max|int }} min
                  ({{ percent_done }}%)
                  Done at {{ as_datetime(end_time).strftime('%H:%M') }}.
                data:
                  tag: "washing_machine_progress"
                  notification_icon: mdi:washing-machine
                  persistent: true
                  sticky: true
                  progress: "{{ progress|int }}"
                  progress_max: "{{ progress_max|int }}"
                  chronometer: true
                  alert_once: true
            - service: script.update_washing_machine_display
              continue_on_error: true
              data:
                display_device_id: 165750b668ea226052a89d9bf8239287
                progress_percent: "{{ percent_done }}"
            - delay: "00:05:00"
      - alias: "Remove progress bar when done"
        service: notify.sander_and_tamara_phones
        continue_on_error: true
        data:
          title: "Washing Machine"
          message: "Laundry finished!"
          data:
            notification_icon: mdi:washing-machine
            tag: "washing_machine_progress"
            progress: -1  # This removes the progress bar
      - service: script.update_washing_machine_display
        continue_on_error: true
        data:
          display_device_id: 165750b668ea226052a89d9bf8239287
          progress_percent: "100"


################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
