homeassistant:
  customize: {}

command_line:
  - switch:
      name: Washing Machine
      command_on: !secret washing_machine_start_command
      command_off: !secret washing_machine_stop_command
#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[washroom|light]Turn on light when door is opened'
    id: washroom_light_turn_on_light_when_door_is_opened
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.washroom_door_sensor
        not_from:
          - "unknown"
          - "unavailable"
    action:
      - choose: #If door is opened, turn on light, if it is closed, turn off
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: switch.turn_on
              data:
                entity_id: switch.shelly_washroom
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: switch.turn_off
              data:
                entity_id: switch.shelly_washroom

  - alias: "[washroom|leak]Warn Washing Machine Leak"
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_leak_sensor
        to: "on"  # Water detected
    condition: []
    action:
      - service: notify.sander_and_tamara_phones
        data:
          message: >-
            Warning: Water detected under the washing machine!
            Detector state: {{ states('binary_sensor.washing_machine_leak_sensor') }} since {{ states.binary_sensor.washing_machine_leak_sensor.last_changed.strftime('%Y-%m-%d %H:%M:%S') }}.
            Please check immediately to prevent damage.
          title: "Washing Machine Leak Alert"
          data:
            ttl: 0
            priority: high
            tag: washing_machine_leak
            group: "water_leak_alert"
            notification_icon: "mdi:water-alert"
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.washing_machine_leak_sensor
            to: "off"  # No water detected
            for:
              hours: 12
      - service: notify.sander_and_tamara_phones
        data:
          message: "clear_notification"
          data:
            ttl: 0
            priority: high
            tag: washing_machine_leak

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
