homeassistant:
  customize:

command_line:
  - switch:
      name: Washing Machine
      command_on: >
          curl --location --request POST 'https://api.smartthings.com/v1/devices/8b480cab-4dda-9024-8ecf-3c3f29f9cf4f/commands' --header 'authorization: Bearer 60c858c9-75fe-4393-8f87-3d05468b3d1f' --header 'Content-Type: text/plain' --data-raw '[    {   "capability":"washerOperatingState",        "command":"setMachineState",        "arguments":["run"]    }]'
      command_off: >
          curl --location --request POST 'https://api.smartthings.com/v1/devices/8b480cab-4dda-9024-8ecf-3c3f29f9cf4f/commands' --header 'Authorization: Bearer 60c858c9-75fe-4393-8f87-3d05468b3d1f' --header 'Content-Type: text/plain' --data-raw '[    {   "capability":"washerOperatingState",        "command":"setMachineState",        "arguments":["stop"]    }]'
#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[washroom|light]Turn on light when door is opened'
    id: washroom_light_turn_on_light_when_door_is_opened
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.washroom_door_sensor
        not_from:
          - "unknown"
          - "unavailable"
    action:
      - choose: #If door is opened, turn on light, if it is closed, turn off
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: switch.turn_on
              data:
                entity_id: switch.shelly_washroom
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'off' }}"
          sequence:
            - service: switch.turn_off
              data:
                entity_id: switch.shelly_washroom
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
