import { describe, it, expect } from 'vitest';
import { processPackageContent, sanitizePackageContent } from '../../js/io/adapters/package_processor.js';

describe('Package Processor', () => {

  describe('sanitizePackageContent', () => {
    it('comments out system-level block keys', () => {
      const yaml = `
esphome:
  name: test
  
wifi:
  ssid: "network"

font:
  - file: "font.ttf"
            `.trim();

      const sanitized = sanitizePackageContent(yaml);

      expect(sanitized).toContain('# esphome: # (Auto-commented)');
      expect(sanitized).toContain('# wifi: # (Auto-commented)');

      expect(sanitized).toContain('#   name: test');
      expect(sanitized).toContain('#   ssid: "network"');

      // Should NOT comment non-system keys that are at root
      expect(sanitized).toContain('font:');
      expect(sanitized).toContain('  - file: "font.ttf"');
    });

    it('handles deep_sleep correctly', () => {
      const yaml = "deep_sleep:\n  run_duration: 10s";
      const sanitized = sanitizePackageContent(yaml);
      expect(sanitized).toContain('# deep_sleep: # (Auto-commented)');
      expect(sanitized).toContain('#   run_duration: 10s');
    });
  });

  describe('processPackageContent', () => {
    const mockProfile = { isPackageBased: true };
    const mockLayout = { orientation: 'landscape', width: 800, height: 480 };
    const mockLines = ["display:", "  - platform: whatever", "font:", "  - file: x"];

    it('injects lambda content at the placeholder preserving indentation', () => {
      const packageYaml = `
display:
  - platform: x
    # __LAMBDA_PLACEHOLDER__
    id: disp
            `.trim();

      const lambdaLines = ["it.print(0, 0, id(font1), \"Hello\");"];

      const result = processPackageContent(packageYaml, lambdaLines, [], mockProfile, mockLayout, false, mockLines);

      // Should inject the lambda header
      expect(result).toContain('    lambda: |-');
      // Should preserve the 4-space indent of the placeholder plus 2 spaces for the lambda content
      expect(result).toContain('      it.print(0, 0, id(font1), "Hello");');
    });

    it('skips lambda injection if isLvgl is true', () => {
      const packageYaml = `
display:
  - platform: x
    # __LAMBDA_PLACEHOLDER__
    id: disp
            `.trim();
      const lambdaLines = ["it.print(0, 0, id(font1), \"Hello\");"];

      // isLvgl = true
      const result = processPackageContent(packageYaml, lambdaLines, [], mockProfile, mockLayout, true, mockLines);

      // Should NOT inject lambda
      expect(result).not.toContain('lambda: |-');
      expect(result).not.toContain('it.print');
    });

    it('removes a template lambda header when LVGL consumes its placeholder', () => {
      const packageYaml = `
display:
  - platform: mipi_spi
    lambda: |-
      # __LAMBDA_PLACEHOLDER__
    id: my_display
            `.trim();

      const result = processPackageContent(packageYaml, [], [], mockProfile, mockLayout, true, mockLines);

      expect(result).not.toContain('lambda: |-');
      expect(result).toContain('id: my_display');
    });

    it('injects touch sensors at the placeholder', () => {
      const packageYaml = `
binary_sensor:
  # __TOUCH_SENSORS_PLACEHOLDER__
  - platform: gpio
            `.trim();

      const touchSensors = [
        "  - platform: touchscreen",
        "    id: btn1",
        "    x_min: 0"
      ];

      const result = processPackageContent(packageYaml, [], touchSensors, mockProfile, mockLayout, false, mockLines);

      expect(result).toContain('  - platform: touchscreen');
      expect(result).toContain('    id: btn1');
    });

    it('removes touch placeholder if no touch sensors provided', () => {
      const packageYaml = `
binary_sensor:
  # __TOUCH_SENSORS_PLACEHOLDER__
  - platform: gpio
            `.trim();

      const result = processPackageContent(packageYaml, [], [], mockProfile, mockLayout, false, mockLines);
      expect(result).not.toContain('__TOUCH_SENSORS_PLACEHOLDER__');
    });

    it('preserves the generated Device Settings diagnostics for package exports', () => {
      const packageYaml = `
# ============================================================================
# ESPHome YAML - Generated by ESPHome Designer
# ============================================================================
display:
  - platform: x
    id: disp
            `.trim();
      const generatedLines = [
        '# ============================================================================',
        '# ESPHome YAML - Generated by ESPHome Designer',
        '# ============================================================================',
        '#',
        '# ====================================',
        '# Device Settings',
        '# ====================================',
        '# Orientation: portrait',
        '# Layout Signature: abc123',
        '# Layout Summary: mode=direct pages=1 widgets=0',
        '# Boot Log Hint: Compare the runtime build signature with this header to spot OTA rollbacks.',
        '# ====================================',
        '',
        'font:',
        '  - file: x'
      ];

      const result = processPackageContent(packageYaml, [], [], mockProfile, mockLayout, false, generatedLines);

      expect(result).toContain('# Device Settings');
      expect(result).toContain('# Orientation: portrait');
      expect(result).toContain('# Layout Signature: abc123');
      expect(result).toContain('# Boot Log Hint: Compare the runtime build signature with this header to spot OTA rollbacks.');
    });

    it('inserts missing rotation inside display instead of the first platform block', () => {
      const packageYaml = `
output:
  - platform: ledc
    pin: GPIO38
    id: gpio_backlight_pwm
    frequency: 100Hz

display:
  - platform: st7701s
    id: my_display
    update_interval: never
            `.trim();

      const result = processPackageContent(
        packageYaml,
        [],
        [],
        { isPackageBased: true, resolution: { width: 480, height: 480 } },
        { orientation: 'portrait' },
        true,
        []
      );

      expect(result).toContain([
        'display:',
        '  - platform: st7701s',
        '    id: my_display',
        '    update_interval: never',
        '    rotation: 90'
      ].join('\n'));
      expect(result).toContain([
        'output:',
        '  - platform: ledc',
        '    pin: GPIO38',
        '    id: gpio_backlight_pwm',
        '    frequency: 100Hz'
      ].join('\n'));
      expect(result).not.toContain('frequency: 100Hz\n    rotation: 90');
    });
  });

});
