# This is the base configuration file for ESPHome
# It includes essential components that are common across different devices

safe_mode:
  boot_is_good_after: 2min
  reboot_timeout: 10min
  num_attempts: 10

# Enable logging for debugging and monitoring device behavior
logger:

# Enable the Home Assistant API
# This allows the device to communicate with Home Assistant, enabling control and monitoring
api:

# Over-The-Air (OTA) updates configuration
# Allows updating the firmware wirelessly without needing physical access to the device
ota:
  - platform: esphome
# Captive portal configuration
# Provides a fallback method for configuring the WiFi credentials via a web portal
# This is especially useful if the device cannot connect to the WiFi network
captive_portal:

# Time configuration
# This sets up the device to use the Home Assistant instance as a time source
# Ensuring accurate timekeeping for time-based automations and tasks
time:
  - platform: homeassistant
    id: homeassistant_time

# ESPHome Version Sensor
# Reports the current version of ESPHome running on the device. Useful for monitoring and updates.
text_sensor:
  - platform: version
    name: "${device_name} ESPHome Version"
    id: esphome_version

# Restart Button
# Creates a virtual button that can be used to remotely restart the device. This is particularly useful for maintenance or troubleshooting without physical access.
button:
  - platform: restart
    id: restart_button
    name: "${device_name} Restart"
