text_sensor:
  # IP Address
  # Shows the current IP address assigned to the device on your network.
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP"
      id: ip
      icon: mdi:ip-network
  # SSID
  # Displays the SSID (network name) the device is currently connected to.
    ssid:
      name: "${device_name} SSID"
      id: ssid
      icon: mdi:router-network-wireless
  # BSSID
  # Reports the BSSID (MAC address) of the wireless access point the device is connected to.
    bssid:
      name: "${device_name} BSSID"
      id: bssid
      icon: mdi:router-network-wireless

  # Additional text sensor for AP Name based on BSSID
  - platform: template
    name: "${device_name} AP Name"
    # Maybe D0:21:F9:B7:EA:68 is AP outside instead.
    lambda: |-
      if (id(bssid).state == "D2:21:F9:97:9C:89") {
        return {"AP-Lite 1st Floor"};
      } else if (id(bssid).state == "D2:21:F9:97:EA:69") {
        return {"AP-Lite Outside"};
      } else if (id(bssid).state == "D2:21:F9:14:06:3A") {
        return {"U6-LR"};
      } else if (id(bssid).state == "B2:8B:A9:15:EF:0A") {
        return {"U6-Pro 2nd Floor"};
      } else {
        return {"Unknown AP"};
      }
    icon: "mdi:access-point-network"
    entity_category: diagnostic

sensor:
  # Uptime Sensor
  # Measures how long the device has been running since the last restart.
  # Useful for monitoring stability and identifying unexpected restarts.
  - platform: uptime
    name: "${device_name} Uptime"
    id: uptime_sensor
    icon: mdi:timer-check-outline
  # WiFi Signal Sensor
  # Monitors the WiFi signal strength to the device.
  # Allows assessing the quality of the wireless connection and identifying potential connectivity issues.
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 5s  # How often the signal strength is measured.
    filters:
      # Applies filters to the reported signal strength values to reduce noise and improve readability.
      - or:
        - throttle_average: 60s  # Averages the value over 60 seconds to smooth out rapid changes.
        - delta: 5  # Only reports changes greater than 5dB to prevent frequent minor updates.
