substitutions:
  device_friendly_name: "AQM Shed"
  device_name: "AQM Shed"
  location: "Shed"
  espname: "shed-air-quality-monitor"

packages:
  aqm: !include templates/AQM_new.yaml
  climate: !include templates/aqm_components/climate.yaml
  tvoc: !include templates/aqm_components/tvoc.yaml
  co2: !include templates/aqm_components/co2.yaml
  particulates: !include templates/aqm_components/particulates.yaml
  display: !include
    file: templates/aqm_components/display.yaml
    vars:
      display_rotation: "0"
  leds: !include templates/aqm_components/leds.yaml
  fan: !include templates/aqm_components/fan.yaml

