sensor:
  - platform: bl0940
    uart_id: uart_bus
    update_interval: ${plug_power_update_interval}
    <<: !include /config/esphome/templates/plug_functions/plug_calibration_power_sensor_settings.yaml

    internal_temperature:
      name: "${device_name} Internal temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      id: internal_temp
      icon: mdi:thermometer
      filters:
        - throttle_average: 5s
        - or:
          - throttle_average: 60s
          - delta: 1.0
        - round: 1
