sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: ${hlw8012_sf1_pin}
    change_mode_every: ${hlw8012_change_mode_every}
    current_resistor: ${current_res}
    voltage_divider: ${hlw_8012_voltage_div}
    update_interval: ${plug_power_update_interval}
    <<: !include /config/esphome/templates/plug_functions/plug_calibration_power_sensor_settings.yaml
