current:
  name: "${device_name} Current"
  unit_of_measurement: A
  accuracy_decimals: 3
  id: current
  icon: mdi:current-ac
  force_update: true
  filters:
    - multiply: ${current_multiplier}
    - throttle_average: 1s
voltage:
  name: "${device_name} Voltage"
  unit_of_measurement: V
  accuracy_decimals: 1
  id: voltage
  icon: mdi:flash-outline
  force_update: true
  filters:
    - multiply: ${voltage_multiplier}
    - throttle_average: 1s
power:
  name: "${device_name} Power"
  unit_of_measurement: W
  accuracy_decimals: 1
  id: power
  icon: mdi:gauge
  force_update: true
  filters:
    - throttle_average: 1s
