homeassistant:
  customize:

input_boolean:
  garbagereminder:
    name: Garbage Reminder
    icon: mdi:trash-can-outline
    
#################
#    SENSORS    #
#################
sensor:
- platform: afvalbeheer
  wastecollector: Waalre
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: !secret postal_code
  streetnumber: !secret street_number
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 1
  nameprefix: 1
  builtinicons: 0
  printwastetypes: 0
- platform: template
  sensors:
    afval_morgen:
      friendly_name: "Afval morgen"
      icon_template: mdi:calendar
      value_template: > 
        {% if is_state('sensor.waalre_morgen', 'restafval') %}
        Grijze container
        {% elif is_state('sensor.waalre_morgen', 'gft') %}
        Groene container   
        {% elif is_state('sensor.waalre_morgen', 'papier') %}
        Oud papier   
        {% elif is_state('sensor.waalre_morgen', 'pbd') or is_state('sensor.waalre_morgen', 'pmd') %}
        Plastic
        {% else %}
        -
        {% endif %}
    afval_vandaag:
      friendly_name: "Afval vandaag"
      icon_template: mdi:calendar-today
      value_template: > 
        {% if is_state('sensor.waalre_vandaag', 'restafval') %}
        Grijze container
        {% elif is_state('sensor.waalre_vandaag', 'gft') %}
        Groene container   
        {% elif is_state('sensor.waalre_vandaag', 'papier') %}
        Oud papier   
        {% elif is_state('sensor.waalre_vandaag', 'pbd') or is_state('sensor.waalre_morgen', 'pmd') %}
        Plastic
        {% else %}
        -
        {% endif %}

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[afval|notify]Wait for notification dismiss'
    trigger:
      platform: state
      entity_id: input_boolean.garbagereminder
      to: 'on'
    action:
      - wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "dismiss"
      - service: input_boolean.turn_off
        entity_id: input_boolean.garbagereminder

  - alias: Herinnering afval morgen
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      - condition: template
        value_template: '{{states.sensor.waalre_morgen.state != ''None''}}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.garbagereminder
      - alias: Notify phone until notification is dismissed
        repeat:
          sequence:
            - service: notify.mobile_app_blokmeister_op6
              data:
                title: Afval morgen
                message: '{{states.sensor.afval_morgen.state}}'
                data:
                  icon: http://192.168.1.252:8123/local/icons/trash-can-outline.png
            - service: notify.mobile_app_blokmeister_op6_haapp
              data:
                title: Afval morgen
                message: '{{states.sensor.afval_morgen.state}}'
                data:
                  group: reminder
                  tag: garbagenotify
                  icon_url: local/icons/trash-can-outline.png
                  actions:
                    - action: "snooze"
                      title: "Snooze"
                    - action: "dismiss"
                      title: "Dismiss"
            - delay:
                minutes: 30
          until:
            - condition: state
              entity_id: input_boolean.garbagereminder
              state: 'off'

  - alias: Herinnering afval vandaag
    trigger:
      - platform: time
        at: 07:00:00
      - platform: state
        entity_id: input_boolean.sleep_tracking_on
        to: 'off'
        for: 00:10:00
    condition:
      - condition: template
        value_template: '{{states.sensor.waalre_vandaag.state != ''None''}}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.garbagereminder
      - alias: Notify phone until notification is dismissed
        repeat:
          sequence:
            - service: notify.mobile_app_blokmeister_op6
              data:
                title: Afval vandaag
                message: '{{states.sensor.afval_vandaag.state}}'
                data:
                  icon: http://192.168.1.252:8123/local/icons/trash-can-outline.png
            - service: notify.mobile_app_blokmeister_op6_haapp
              data:
                title: Afval vandaag
                message: '{{states.sensor.afval_vandaag.state}}'
                data:
                  group: reminder
                  tag: garbagenotify
                  icon_url: local/icons/trash-can-outline.png
                  actions:
                    - action: "snooze"
                      title: "Snooze"
                    - action: "dismiss"
                      title: "Dismiss"
            - delay:
                minutes: 10
          until:
            - condition: state
              entity_id: input_boolean.garbagereminder
              state: 'off'

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
