homeassistant:
  customize:

input_boolean:
  garbagereminder:
    name: Garbage Reminder
    icon: mdi:trash-can-outline

#################
#    SENSORS    #
#################
sensor:
- platform: afvalbeheer
  name: 'Afval Voor'
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
  postcode: !secret postal_code
  streetnumber: !secret street_number_nosuffix
  suffix: !secret street_number_suffix
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 1
  nameprefix: 1
  builtinicons: 0
  printwastetypes: 0
- platform: afvalbeheer
  name: 'Afval Achter'
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
  postcode: !secret postal_code_afval_achter
  streetnumber: !secret street_number_afval_achter
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 1
  nameprefix: 1
  builtinicons: 0
  printwastetypes: 0

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[afval|notify]Wait for notification dismiss'
    mode: restart
    trigger:
      platform: state
      entity_id: input_boolean.garbagereminder
      to: 'on'
    action:
      - wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "dismiss"
          - platform: state
            entity_id: input_boolean.garbagereminder
            to: "off"
      - service: input_boolean.turn_off
        entity_id: input_boolean.garbagereminder

  - alias: '[afval|notify]Herinnering afval morgen'
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      # - condition: not
      #   conditions:
      #     - condition: state
      #       entity_id: sensor.mijnafvalwijzer_afval_achter_morgen
      #       state: "None"
      #     - condition: state
      #       entity_id: sensor.mijnafvalwijzer_afval_voor_morgen
      #       state: "None"
      - condition: template
        value_template: "{{ not is_state('sensor.mijnafvalwijzer_afval_achter_morgen', 'None') or not is_state('sensor.mijnafvalwijzer_afval_voor_morgen', 'None') }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.garbagereminder
      - alias: Notify phone until notification is dismissed
        repeat:
          sequence:
            # - service: automation.trigger
            #   entity_id: automation.afval_notify_wait_for_notification_dismiss
            - service: notify.mobile_app_blokmeisters21u
              data:
                title: Afval morgen
                message: "Afval achter: {{ states( 'sensor.mijnafvalwijzer_afval_achter_morgen' ) }}, afval voor: {{ states( 'sensor.mijnafvalwijzer_afval_voor_morgen' ) }}"
                data:
                  group: reminder
                  tag: garbagenotify
                  icon_url: local/icons/trash-can-outline.png
                  actions:
                    - action: "snooze"
                      title: "Snooze"
                    - action: "dismiss"
                      title: "Dismiss"
            - delay:
                minutes: 30
          until:
            - condition: or
              conditions:
                - condition: template
                  value_template: "{{ repeat.index >= 5 }}"
                - condition: state
                  entity_id: input_boolean.garbagereminder
                  state: 'off'
                - condition: template
                  value_template: "{{ not is_state('sensor.mijnafvalwijzer_afval_achter_morgen', 'None') or not is_state('sensor.mijnafvalwijzer_afval_voor_morgen', 'None') }}"

  - alias: '[afval|notify]Herinnering afval vandaag'
    trigger:
      - platform: time
        at: 07:00:00
      - platform: state
        entity_id: input_boolean.sleep_tracking_on
        to: 'off'
        for: 00:10:00
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.mijnafvalwijzer_afval_achter_vandaag', 'None') or not is_state('sensor.sensor.mijnafvalwijzer_afval_voor_vandaag', 'None') }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.garbagereminder
      - alias: Notify phone until notification is dismissed
        repeat:
          sequence:
            - service: notify.mobile_app_blokmeisters21u
              data:
                title: Afval vandaag
                message: "Afval achter: {{ states( 'sensor.mijnafvalwijzer_afval_achter_vandaag' ) }}, afval voor: {{ states( 'sensor.mijnafvalwijzer_afval_voor_vandaag' ) }}"
                data:
                  group: reminder
                  tag: garbagenotify
                  icon_url: local/icons/trash-can-outline.png
                  actions:
                    - action: "snooze"
                      title: "Snooze"
                    - action: "dismiss"
                      title: "Dismiss"
            - delay:
                minutes: 10
          until:
            - condition: or
              conditions:
                - condition: template
                  value_template: "{{ repeat.index >= 5 }}"
                - condition: state
                  entity_id: input_boolean.garbagereminder
                  state: 'off'
                - condition: template
                  value_template: "{{ not is_state('sensor.mijnafvalwijzer_afval_achter_morgen', 'none') and not is_state('sensor.mijnafvalwijzer_afval_achter_morgen', '-') }}"

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
