homeassistant:
  customize: {}

input_boolean:
  garbagereminder:
    name: Garbage Reminder
    icon: mdi:trash-can-outline
  garbage_taken_out:
    name: Garbage taken out
    icon: mdi:trash-can-check

# afvalbeheer:
#   - name: 'Afval Voor'
#     wastecollector: MijnAfvalwijzer
#     resources:
#       - restafval
#       - gft
#       - papier
#     postcode: !secret postal_code
#     streetnumber: !secret street_number_nosuffix
#     #suffix: !secret street_number_suffix
#     upcomingsensor: 1
#     dateformat: '%d-%m-%Y'
#     dateonly: 1
#     nameprefix: 1
#     builtinicons: 1
#     printwastetypes: 0

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      days_to_gft:
        friendly_name: "Days to GFT"
        unique_id: yaml_template_sensor_days_to_gft
        icon_template: mdi:leaf
        unit_of_measurement: 'days'
        value_template: >-
          {{ (strptime(states('sensor.afval_voor_gft'), '%d-%m-%Y', today_at()) | as_local - today_at()).days }}
        availability_template: "{{ states('sensor.afval_voor_gft') not in ['unknown', 'unavailable', 'none'] }}"
      days_to_papier:
        friendly_name: "Days to Papier"
        unique_id: yaml_template_sensor_days_to_papier
        icon_template: mdi:newspaper-variant
        unit_of_measurement: 'days'
        value_template: >-
          {{ (strptime(states('sensor.afval_voor_papier'), '%d-%m-%Y', today_at()) | as_local - today_at()).days }}
        availability_template: "{{ states('sensor.afval_voor_papier') not in ['unknown', 'unavailable', 'none'] }}"
      days_to_restafval:
        friendly_name: "Days to Restafval"
        unique_id: yaml_template_sensor_days_to_restafval
        icon_template: mdi:delete
        unit_of_measurement: 'days'
        value_template: >-
          {{ (strptime(states('sensor.afval_voor_restafval'), '%d-%m-%Y', today_at()) | as_local - today_at()).days }}
        availability_template: "{{ states('sensor.afval_voor_restafval') not in ['unknown', 'unavailable', 'none'] }}"


########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: "[misc|garbage] Dismiss sticky garbage notification when acknowledged"
    id: yaml_automation_misc_garbage_dismiss_sticky_garbage_notification_when_acknowledged
    description: Clears the sticky garbage notification on all phones when either phone confirms it's out.
    mode: single
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: GARBAGE_PUT_OUT
    action:
      - service: notify.sander_and_tamara_phones
        data:
          message: "clear_notification"
          data:
            tag: garbage_pickup
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.garbage_taken_out

  - alias: '[afval|notify]Herinnering afval morgen'
    id: yaml_automation_afval_notify_herinnering_afval_morgen
    description: Send a sticky reminder the evening before pickup and reset the helper flag.
    mode: single
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      - condition: template
        value_template: "{{ ((as_timestamp(state_attr('calendar.afvalbeheer_mijnafvalwijzer', 'start_time')) - as_timestamp(now()))/3600 < 24) and ((as_timestamp(state_attr('calendar.afvalbeheer_mijnafvalwijzer', 'start_time')) - as_timestamp(now()))/3600 > 0) }}"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.garbage_taken_out
      - service: notify.sander_and_tamara_phones
        data:
          title: "Afval morgen"
          message: "Afval: {{ states('sensor.afval_voor_tomorrow') }}"
          data:
            sticky: true
            ttl: 0
            priority: high
            tag: garbage_pickup
            group: garbage
            channel: Garbage
            notification_icon: mdi:trash-can-outline
            icon_url: local/icons/trash-can-outline.png
            actions:
              - action: GARBAGE_PUT_OUT
                title: "I put it outside"

  - alias: '[afval|notify]Herinnering afval vandaag'
    id: yaml_automation_afval_notify_herinnering_afval_vandaag
    description: Send a single sticky notification on the morning of garbage pickup.
    mode: single
    trigger:
      - platform: time
        at: '07:00:00'
      - platform: state
        entity_id: input_boolean.sleep_tracking_on
        to: 'off'
        for: '00:10:00'
    condition:
      - condition: template
        value_template: >-
          {{ ((as_timestamp(state_attr('calendar.afvalbeheer_mijnafvalwijzer', 'start_time')) - as_timestamp(now()))/3600 < 0)
             and ((as_timestamp(state_attr('calendar.afvalbeheer_mijnafvalwijzer', 'start_time')) - as_timestamp(now()))/3600 > -12) }}
      - condition: state
        entity_id: input_boolean.garbage_taken_out
        state: "off"
    action:
      - service: notify.sander_and_tamara_phones
        data:
          title: "Afval vandaag"
          message: "Afval voor: {{ states('sensor.afval_voor_today') }}"
          data:
            sticky: true
            ttl: 0
            priority: high
            tag: garbage_pickup
            group: garbage
            channel: Garbage
            notification_icon: mdi:trash-can-outline
            icon_url: local/icons/trash-can-outline.png
            actions:
              - action: GARBAGE_PUT_OUT
                title: "I put it outside"

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
