homeassistant:
  customize:
    sensor.blokmeisterhausen_tado_bridge_status:
      icon: mdi:link-box-outline
    sensor.heating_tado_mode:
      icon: mdi:thermostat
    sensor.heating_link:
      icon: mdi:link-box-outline
    # sensor.heating_overlay:
    #   icon: mdi:lightbulb-outline
    # sensor.heating_power:
    #   icon: mdi:lightbulb-outline
    # device_tracker.tado:
    #   icon: mdi:lightbulb-outline
    sensor.heating_heating:
      icon: mdi:speedometer
    # sensor.heating_temperature:
    #   icon: mdi:lightbulb-outline
    # climate.hot_water:
    #   icon: mdi:lightbulb-outline
    # sensor.hot_water_tado_mode:
    #   icon: mdi:lightbulb-outline
    sensor.hot_water_link:
      icon: mdi:link-box-outline
    # sensor.hot_water_overlay:
    #   icon: mdi:lightbulb-outline
    # sensor.hot_water_power:
    #   icon: mdi:lightbulb-outline
    group.tado_all:
      templates:
        icon: >
          'mdi-thermostat'
        icon_color: >
          {% if state.climate.heating.attributes.hvac_action == 'idle' %}
            'rgb(124, 124, 124)'
          {% else %}
            'rgb(255, 50, 50)'
          {% endif %}

ble_monitor:
  devices:
    - mac: 'A4:C1:38:86:60:BE'
      name: 'Filament box sensor'
      temperature_unit: C
    - mac: 'A4:C1:38:C1:83:3A'
      name: 'Kitchen temp'
      temperature_unit: C
    - mac: 'A4:C1:38:76:01:29'
      name: 'Study temp'
      temperature_unit: C
    - mac: 'A4:C1:38:14:F4:B3'
      name: 'Plant box temp'
      temperature_unit: C

luxtronik:
  host: !secret luxtronik_gateway_IP
  port: !secret luxtronik_gateway_port
#################
#    SENSORS    #
#################
sensor:
  - platform: luxtronik
    scan_interval: 15
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TVL
        friendly_name: Temperatuur VV aanvoer

      - group: calculations
        id: ID_WEB_Temperatur_TRL
        friendly_name: Temperatuur VV retour

      - group: calculations
        id: ID_WEB_Sollwert_TRL_HZ
        friendly_name: Setpunkt retour verwarming

      - group: calculations
        id: ID_WEB_Temperatur_TA
        friendly_name: Temperatuur buiten

      - group: calculations
        id: ID_WEB_Temperatur_TBW
        friendly_name: Temperatuur tapwater

      - group: calculations
        id: ID_WEB_Einst_BWS_akt
        friendly_name: Tapwater gewenst

      - group: calculations
        id: ID_WEB_Temperatur_TWE
        friendly_name: Temperatuur warmtebron ingang

      - group: calculations
        id: ID_WEB_Temperatur_TWA
        friendly_name: Temperatuur warmtebron uitgang

      - group: calculations
        id: ID_WEB_Temperatur_RFV
        friendly_name: Temperatuur ruimte

      - group: calculations
        id: ID_WEB_HauptMenuStatus_Zeile1
        friendly_name: Status 1

      - group: calculations
        id: ID_WEB_HauptMenuStatus_Zeile2
        friendly_name: Status 2

      - group: calculations
        id: ID_WEB_HauptMenuStatus_Zeile3
        friendly_name: Status 3

      - group: calculations
        id: ID_WEB_Zaehler_BetrZeitVD1
        friendly_name: Bedrijfsuren compressor

      - group: calculations
        id: ID_WEB_Zaehler_BetrZeitImpVD1
        friendly_name: Impulsen compressor

      - group: calculations
        id: ID_WEB_WP_BZ_akt
        friendly_name: Toestand

      - group: calculations
        id: Heat_Output
        friendly_name: Thermisch vermogen

      - group: calculations
        id: ID_WEB_Code_WP_akt
        friendly_name: Warmtepomp type

      - group: calculations
        id: ID_WEB_RBE_RT_Soll
        friendly_name: Ruimte temperatuur gewenst

      - group: calculations
        id: ID_WEB_RBE_RT_Ist
        friendly_name: Ruimte temperatuur nu

      - group: calculations
        id: ID_WEB_Sollwert_TRL_HZ
        friendly_name: Verwarming retour setpoint

      - group: calculations
        id: ID_WEB_Time_WPein_akt
        friendly_name: Warmtepomp loopt

      - group: calculations
        id: ID_WEB_Zaehler_BetrZeitWP

      - group: calculations
        id: ID_WEB_Zaehler_BetrZeitKue
        friendly_name: Bedrijfsuren koeling

      - group: calculations
        id: ID_WEB_Zaehler_BetrZeitBW
        friendly_name: Bedrijfsuren tapwater

      - group: calculations
        id: ID_WEB_Zaehler_BetrZeitHz
        friendly_name: Bedrijfsuren verwarming

      - group: calculations
        id: ID_WEB_WMZ_Heizung
        friendly_name: Verwarming

      - group: calculations
        id: ID_WEB_WMZ_Seit
        friendly_name: Gezamelijke warmteproductie

      - group: calculations
        id: ID_WEB_WMZ_Brauchwasser
        friendly_name: Tapwater

      - group: calculations
        id: ID_WEB_Temperatur_THG
        friendly_name: Heetgas

      - group: calculations
        id: ID_WEB_Freq_VD
        friendly_name: Compressorfrequentie

      - group: calculations
        id: ID_WEB_HZIO_PWM
        friendly_name: Regelsignaal circulatiepomp

      - group: calculations
        id: ID_WEB_Durchfluss_WQ
        friendly_name: Doorstroom

      - group: calculations
        id: Flow_Rate_254
        friendly_name: Flow rate

      - group: calculations
        id: ID_WEB_Time_LGS_akt
        friendly_name: Thermische desinfectie sinds

      - group: calculations
        id: ID_WEB_Switchoff_file_Nr0
        friendly_name: Afschakelcode

      - group: calculations
        id: ID_WEB_HauptMenuStatus_Zeile1
        friendly_name: Status regel 1

      - group: calculations
        id: ID_WEB_HauptMenuStatus_Zeile2
        friendly_name: Status regel 2

      - group: calculations
        id: ID_WEB_HauptMenuStatus_Zeile3
        friendly_name: Status regel 3

      - group: calculations
        id: ID_WEB_LIN_HD
        friendly_name: Hogedruk

      - group: calculations
        id: ID_WEB_LIN_ND
        friendly_name: Lagedruk

      - group: calculations
        id: ID_WEB_WMZ_Durchfluss
        friendly_name: Doorstroom 2

      - group: calculations
        id: ID_WEB_SoftStand
        friendly_name: Firmware versie

      - group: calculations
        id: ID_WEB_AdresseIP_akt
        friendly_name: IP adres

      - group: calculations
        id: ID_WEB_SEC_BZ
        friendly_name: Bedrijfstoestand

      - group: calculations
        id: ID_WEB_FreigabKuehl
        friendly_name: Vrijgave koeling

      # - 'ID_WEB_Freq_VD' #Compressorfrequentie , Zie ook de template sensor voor omzetten naar juist aantal Hz
      - group: calculations
        id: ID_WEB_LIN_ANSAUG_VERDAMPFER
        friendly_name: Aanzuigtemperatuur verdamper

      - group: parameters
        id: ID_Ba_Hz_akt
        friendly_name: Verwarming test

      - group: parameters
        id: ID_Ba_Bw_akt
        friendly_name: Tapwater test

      - group: parameters
        id: ID_Einst_BA_Kuehl_akt
        friendly_name: Koeling instelling

      - group: parameters
        id: ID_Einst_WK_akt

      - group: parameters
        id: ID_Ba_Hz_MK3_akt
        friendly_name: Koeling instelling2

      - group: parameters
        id: ID_Ba_Bw_akt
        friendly_name: Tapwater instelling

      - group: parameters
        id: ID_Ba_Hz_akt
        friendly_name: Verwarming instelling

      # - group: parameters
        # id: ID_Einst_HzHwHKE_akt
      - group: parameters
        id: ID_Einst_HzHKRANH_akt
        friendly_name: Voetpunt stooklijn

      - group: parameters
        id: ID_Einst_HzHKRABS_akt
        friendly_name: Nachtverlaging

      - group: parameters
        id: ID_Einst_Heizgrenze_Temp
        friendly_name: Stookgrens

      - group: parameters
        id: ID_Einst_KuehlFreig_akt
        friendly_name: Koelen vanaf BT

      - group: parameters
        id: ID_Sollwert_KuCft2_akt
        friendly_name: Aanvoer temperatuur koeling

      - group: parameters
        id: ID_Einst_Kuhl_Zeit_Ein_akt
        friendly_name: Koeling aan na BT overschrijding

      - group: parameters
        id: ID_Einst_Kuhl_Zeit_Aus_akt
        friendly_name: Koeling uit na BT onderschrijding

  - platform: derivative
    source: sensor.gezamelijke_warmteproductie
    name: Total Heat Production Power
    unit_time: h
    unit: kW

  - platform: derivative
    source: sensor.tapwater
    name: Tapwater Heat Production Power
    unit_time: h
    unit: kW

  - platform: derivative
    source: sensor.verwarming
    name: Heating Heat Production Power
    unit_time: h
    unit: kW

  - platform: command_line
    name: ah_woonkamer
    command: "cat python_scripts/gateway.json | jq '.Woonkamer' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: command_line
    name: ah_slaapkamer1
    command: "cat python_scripts/gateway.json | jq '.Slaapkamer1' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: command_line
    name: ah_slaapkamer2
    command: "cat python_scripts/gateway.json | jq '.Slaapkamer2' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: command_line
    name: ah_slaapkamer3
    command: "cat python_scripts/gateway.json | jq '.Slaapkamer3' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: command_line
    name: ah_slaapkamer4
    command: "cat python_scripts/gateway.json | jq '.Slaapkamer4' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: command_line
    name: ah_slaapkamer5
    command: "cat python_scripts/gateway.json | jq '.Slaapkamer5' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: command_line
    name: ah_badkamer
    command: "cat python_scripts/gateway.json | jq '.Badkamer' "
    json_attributes:
      - temperature
      - battery
      - setpoint
    scan_interval: 60

  - platform: template
    sensors:
      woonkamer_temperatuur:
        friendly_name: "Woonkamer temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_woonkamer', 'temperature') | round(1, 0) }}"
      woonkamer_battery:
        friendly_name: "Woonkamer batterij"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_woonkamer', 'battery') }}"
      woonkamer_ingestelde_temperatuur:
        friendly_name: "Woonkamer ingestelde temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_woonkamer', 'setpoint') | round(1, 0) }}"

      slaapkamer1_temperatuur:
        friendly_name: "Slaapkamer 1 Temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer1', 'temperature') | round(1, 0) }}"
      slaapkamer1_battery:
        friendly_name: "Slaapkamer 1 Battery"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_slaapkamer1', 'battery') }}"
      slaapkamer1_ingestelde_temperatuur:
        friendly_name: "Slaapkamer 1 Setpoint"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer1', 'setpoint') | round(1, 0) }}"

      slaapkamer2_temperatuur:
        friendly_name: "Slaapkamer 2 Temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer2', 'temperature') | round(1, 0) }}"
      slaapkamer2_battery:
        friendly_name: "Slaapkamer 2 Battery"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_slaapkamer2', 'battery') }}"
      slaapkamer2_ingestelde_temperatuur:
        friendly_name: "Slaapkamer 2 Setpoint"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer2', 'setpoint') | round(1, 0) }}"

      slaapkamer3_temperatuur:
        friendly_name: "Slaapkamer 3 Temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer3', 'temperature') | round(1, 0) }}"
      slaapkamer3_battery:
        friendly_name: "Slaapkamer 3 Battery"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_slaapkamer3', 'battery') }}"
      slaapkamer3_ingestelde_temperatuur:
        friendly_name: "Slaapkamer 3 Setpoint"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer3', 'setpoint') | round(1, 0) }}"

      slaapkamer4_temperatuur:
        friendly_name: "Slaapkamer 2 Temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer4', 'temperature') | round(1, 0) }}"
      slaapkamer4_battery:
        friendly_name: "Slaapkamer 4 Battery"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_slaapkamer4', 'battery') }}"
      slaapkamer4_ingestelde_temperatuur:
        friendly_name: "Slaapkamer 4 Setpoint"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer4', 'setpoint') | round(1, 0) }}"

      slaapkamer5_temperatuur:
        friendly_name: "Slaapkamer 5 Temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer5', 'temperature') | round(1, 0) }}"
      slaapkamer5_battery:
        friendly_name: "Slaapkamer 5 Battery"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_slaapkamer5', 'battery') }}"
      slaapkamer5_ingestelde_temperatuur:
        friendly_name: "Slaapkamer 5 Setpoint"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_slaapkamer5', 'setpoint') | round(1, 0) }}"

      badkamer_temperatuur:
        friendly_name: "Badkamer Temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_badkamer', 'temperature') | round(1, 0) }}"
      badkamer_battery:
        friendly_name: "Badkamer Battery"
        device_class: battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ah_badkamer', 'battery') }}"
      badkamer_ingestelde_temperatuur:
        friendly_name: "Badkamer Setpoint"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.ah_badkamer', 'setpoint') | round(1, 0) }}"

      warmtebron_in_uit_delta:
        friendly_name: Warmtebron in-uit Delta T
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.temperatuur_warmtebron_uitgang')|float - states('sensor.temperatuur_warmtebron_ingang')|float}}"
        availability_template: "{{ states.sensor.temperatuur_warmtebron_uitgang not in ['unavailable', 'unknown', 'none', None] and states.sensor.temperatuur_warmtebron_ingang not in ['unavailable', 'unknown', 'none', None] }}"
      vloerverwarming_in_uit_delta:
        friendly_name: Vloerverwarming in-uit Delta T
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.temperatuur_vv_aanvoer')|float - states('sensor.temperatuur_vv_retour')|float}}"
        availability_template: "{{ states.sensor.temperatuur_vv_aanvoer not in ['unavailable', 'unknown', 'none', None] and states.sensor.temperatuur_vv_retour not in ['unavailable', 'unknown', 'none', None] }}"
########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: luxtronik
    scan_interval: 60
    sensors:
      - group: calculations
        friendly_name: Brine pomp ventilator
        #icon: mdi:fan
        id: ID_WEB_VBOout

      - group: calculations
        friendly_name: Ventilatie warmtepomp (lucht)
        id: ID_WEB_VENout

      - group: calculations
        id: ID_WEB_ZIPout
        friendly_name: Circulatiepomp

      - group: calculations
        id: ID_WEB_ZUPout
        friendly_name: Aanvullende circulatiepomp

      - group: calculations
        id: ID_WEB_BWTin
        friendly_name: Vraag warm tapwater

      - group: calculations
        id: ID_WEB_HDin
        friendly_name: Hogedruk pressostaat
        #Uit is ok, rule aanmaken

      - group: calculations
        id: ID_WEB_MOTin
        friendly_name: Motorbeveiliging

      - group: calculations
        id: ID_WEB_NDin
        friendly_name: Lagedruk pressostaat

      - group: calculations
        id: ID_WEB_BUPout
        friendly_name: Circulatiepomp warm tapwater

      - group: calculations
        id: ID_WEB_HUPout
        friendly_name: Vloerverwaming circulatiepomp

      - group: calculations
        id: ID_WEB_MA1out
        friendly_name: Mixer uitgang open
        
      - group: calculations
        id: ID_WEB_MZ1out
        friendly_name: Mixer uitgang dicht
      
      - group: calculations
        id: ID_WEB_VD1out
        friendly_name: Compressor
        
      - group: calculations
        id: ID_WEB_ASDin
        friendly_name: Ontdooien, flow brine, doorstroming
        
      - group: calculations
        id: ID_WEB_Comfort_exists
        friendly_name: Comfort print aanwezig
########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[climate|temperature] Poll Alpha Home Temperatures'
    trigger:
      platform: time_pattern
      minutes: "/1"
    action:
      - service: shell_command.poll_alphahome_sensors
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:

########################
#    SHELL COMMANDS    #
########################
shell_command:
  poll_alphahome_sensors: "python3 /config/python_scripts/gateway.py > /config/python_scripts/gateway.json"
