homeassistant:
  customize:
    sensor.blokmeisterhausen_tado_bridge_status:
      icon: mdi:link-box-outline
    sensor.heating_tado_mode:
      icon: mdi:thermostat
    sensor.heating_link:
      icon: mdi:link-box-outline
    # sensor.heating_overlay:
    #   icon: mdi:lightbulb-outline
    # sensor.heating_power:   
    #   icon: mdi:lightbulb-outline
    # device_tracker.tado:
    #   icon: mdi:lightbulb-outline
    sensor.heating_heating:
      icon: mdi:speedometer
    # sensor.heating_temperature:
    #   icon: mdi:lightbulb-outline
    # climate.hot_water:
    #   icon: mdi:lightbulb-outline
    # sensor.hot_water_tado_mode:
    #   icon: mdi:lightbulb-outline
    sensor.hot_water_link:
      icon: mdi:link-box-outline
    # sensor.hot_water_overlay:
    #   icon: mdi:lightbulb-outline
    # sensor.hot_water_power:
    #   icon: mdi:lightbulb-outline


#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[climate] Tado off when sleeping'
    trigger:
      platform: state
      entity_id: input_boolean.sleep_tracking_on
      to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: climate.heating
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  tado_all:
    entities:
      - sensor.blokmeisterhausen_tado_bridge_status
      - climate.heating
      - sensor.heating_tado_mode
      - sensor.heating_humidity
      - sensor.heating_link
      - sensor.heating_overlay
      - sensor.heating_power        
      - device_tracker.tado
      - sensor.heating_heating
      - sensor.heating_temperature
      - climate.hot_water
      - sensor.hot_water_tado_mode
      - sensor.hot_water_link
      - sensor.hot_water_overlay
      - sensor.hot_water_power
  tado_climate:
    entities:
      - climate.heating
      - sensor.heating_tado_mode
      - sensor.heating_humidity
      - sensor.heating_link
      - sensor.heating_overlay
      - sensor.heating_power        
      - device_tracker.tado
      - sensor.heating_heating
      - sensor.heating_temperature
  tado_water:
    entities:
      - climate.hot_water
      - sensor.hot_water_tado_mode
      - sensor.hot_water_link
      - sensor.hot_water_overlay
      - sensor.hot_water_power
#################
#    SCRIPTS    #
#################
script: