homeassistant:
  customize:


# ble_monitor:
#   discovery: False
#   restore_state: True
#   active_scan: False
#   hci_interface:
#     - 0
#     - 1
#   devices:
#     - mac: 'A4:C1:38:86:60:BE'
#       name: 'Filament box sensor'
#       temperature_unit: C
#     - mac: 'A4:C1:38:C1:83:3A'
#       name: 'Kitchen temp'
#       temperature_unit: C
#     - mac: 'A4:C1:38:76:01:29'
#       name: 'Study temp'
#       temperature_unit: C
#     - mac: 'A4:C1:38:14:F4:B3'
#       name: 'Plant box temp'
#       temperature_unit: C

# luxtronik:
#   host: !secret luxtronik_gateway_IP
#   port: !secret luxtronik_gateway_port
#################
#    SENSORS    #
#################
sensor:
  - platform: min_max
    type: sum
    name: Total Heat Production Power
    entity_ids:
      - sensor.tapwater_heat_production_power
      - sensor.heating_heat_production_power

  - platform: derivative
    source: sensor.heatpump_tapwater_heat_amount
    name: Tapwater Heat Production Power
    unit_time: h
    unit: kW

  - platform: derivative
    source: sensor.heatpump_heat_amount_heating
    name: Heating Heat Production Power
    unit_time: h
    unit: kW

  - platform: derivative
    source: sensor.heatpump_tapwater_temperature
    name: Tapwater Temperature Change
    time_window: "00:02:00"
    unit_time: h
    unit: °C

  - platform: min_max
    type: mean
    name: Home Mean Humidity
    unique_id: sensor_home_mean_humidity
    entity_ids:
      - sensor.humidity_livingroom
      - sensor.livingroom_aqm_humidity

      - sensor.humidity_bathroom

      - sensor.humidity_bedroom
      - sensor.bedroom_aqm_humidity

      - sensor.study_multi_sensor_humidity
      - sensor.study_aqm_humidity

  - platform: min_max
    type: mean
    name: Home Mean Humidity Without Bathroom
    unique_id: sensor_home_mean_humidity_without_bathroom
    entity_ids:
      - sensor.humidity_livingroom
      - sensor.livingroom_aqm_humidity

      - sensor.humidity_bedroom
      - sensor.bedroom_aqm_humidity

      - sensor.study_multi_sensor_humidity
      - sensor.study_aqm_humidity

  - platform: template
    sensors:
      warmtebron_in_uit_delta:
        friendly_name: Warmtebron in-uit Delta T
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.heatpump_heat_source_output_temperature')|float - states('sensor.heatpump_heat_source_input_temperature')|float}}"
        availability_template: "{{ states.sensor.heatpump_heat_source_output_temperature not in ['unavailable', 'unknown', 'none', None] and states.sensor.heatpump_heat_source_input_temperature not in ['unavailable', 'unknown', 'none', None] }}"
      vloerverwarming_in_uit_delta:
        friendly_name: Vloerverwarming in-uit Delta T
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.heatpump_flow_in_temperature')|float - states('sensor.heatpump_flow_out_temperature')|float}}"
        availability_template: "{{ states.sensor.heatpump_flow_in_temperature not in ['unavailable', 'unknown', 'none', None] and states.sensor.heatpump_flow_in_temperature not in ['unavailable', 'unknown', 'none', None] }}"
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  # - alias: '[climate|temperature] Poll Alpha Home Temperatures'
  #   trigger:
  #     platform: time_pattern
  #     minutes: "/1"
  #   action:
  #     - service: shell_command.poll_alphahome_sensors
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:

########################
#    SHELL COMMANDS    #
########################
shell_command:
  # poll_alphahome_sensors: "python3 /config/python_scripts/gateway.py > /config/python_scripts/gateway.json"
