#Used as template template: https://github.com/Limych/HomeAssistantConfiguration/blob/master/packages/house/guest_mode.yaml

homeassistant:
  customize:
    input_boolean.guest_mode:
      templates:
        icon: >
          if (state === 'on') return 'mdi:account-group';
          else if (state === 'off') return 'mdi:account';
        icon_color: >
          if (state === 'on') return 'rgb(56, 150, 56)';
          else if (state === 'off') return 'rgb(249, 251, 255)';

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:
  guest_mode:
    name: "Guest mode"
    icon: mdi:account-clock

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: 'Guest Mode On'
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'on'
    action:
      - service: notify.all
        data_template:
          title: 'Guest mode on'
          message: >
            'Guest mode turned on!'

  - alias: 'Guest Mode Off'
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'off'
    action:
      - service: notify.all
        data_template:
          title: 'Guest mode off'
          message: >
            'Guest mode turned off!'

  - alias: 'Turn on guest mode'
    initial_state: on
    trigger:
      - platform: state
        entity_id: calendar.gasten_in_huis
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode

  - alias: 'Turn off guest mode'
    initial_state: on
    trigger:
      - platform: state
        entity_id: calendar.gasten_in_huis
        to: 'off'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode        
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: