homeassistant:
  customize: {}

adaptive_lighting:
  name: "Adaptive lighting"
  lights:
    - light.entry
    - light.kitchen
    - light.living_room

    - light.hallway_1st_floor
    - light.bathroom
    - light.bathroom_mirror_hue
    - light.babyroom

    - light.hallway_2nd_floor
    - light.study

    # Shelly dimmers (no color)
    - light.shelly_dinner_table
    - light.shelly_bedroom
    - light.shelly_tamara_s_room
  initial_transition: 1
  min_brightness: 30
  min_color_temp: 2000
  max_color_temp: 5000
  max_sunrise_time: "06:15:00"
  take_over_control: True # Disable adaptive lighting when I set the color/brightness of a light myself
  autoreset_control_seconds: 600 # Reset lights to use adaptive lighting after 10 minutes
  intercept: False # Disable intercepting of light.turn_on calls. I do all of this myself.
  interval: 300 # Update lights every 5 minutes
  transition: 10

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: "[home|lights] Set Sleep Mode Light Brightness"
    id: yaml_automation_home_lights_set_sleep_mode_light_brightness
    description: >
      Sets the lights to a dimmer level when sleep tracking is active and you're home alone.
      This triggers when sleep tracking starts and stops, ensuring lights are adjusted accordingly.
    trigger:
      - platform: template
        value_template: >
          {{
            not is_state('sensor.sleepasandroid_sander', 'sleep_tracking_stopped') and
            not is_state('sensor.sleepasandroid_sander', 'time_to_bed_alarm_alert') and
            not is_state('sensor.sleepasandroid_sander', 'alarm_alert_dismiss') and
            not is_state('sensor.sleepasandroid_sander', 'alarm_rescheduled') or
            not is_state('sensor.sleepasandroid_sander', 'unknown')
          }}
        for:
          minutes: 3
        id: sleep_tracking_start
      - platform: template
        value_template: >
          {{
            is_state('sensor.sleepasandroid_sander', 'sleep_tracking_stopped') or
            is_state('sensor.sleepasandroid_sander', 'time_to_bed_alarm_alert') or
            is_state('sensor.sleepasandroid_sander', 'alarm_alert_dismiss') or
            is_state('sensor.sleepasandroid_sander', 'alarm_rescheduled') or
            is_state('sensor.sleepasandroid_sander', 'unknown')
          }}
        for:
          minutes: 3
        id: sleep_tracking_stop
    condition:
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'sleep_tracking_start' }}"
              - condition: numeric_state
                entity_id: sensor.guest_wifi_clients
                below: 1
              - condition: not
                conditions:
                  - condition: state
                    entity_id: person.tamara
                    state: home
            sequence:
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_sleep_mode_adaptive_lighting
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.id == 'sleep_tracking_stop' }}"
            sequence:
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_sleep_mode_adaptive_lighting

  - alias: "[home|lights]Toggle Light Automations When Home Alone"
    description: "Enables motion-based lighting automations when I'm home alone between 06:00 and 22:00. Disables them when I'm not home alone, regardless of the time."
    id: "yaml_automation_home_lights_toggle_light_automations_when_home_alone"
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.sander_home_alone
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.sander_home_alone
                state: "on"
              - condition: time
                after: "06:00:00"
                before: "22:00:00"
            sequence:
              - service: automation.turn_on
                target:
                  entity_id:
                    - automation.livingroom_lights_turn_on_lights_when_motion_is_detected
                    - automation.kitchen_lights_turn_on_lights_when_motion_is_detected
                    - automation.study_lights_turn_on_lights_when_motion_is_detected
                    - automation.entry_lights_turn_on_lights_when_motion_is_detected
                    - automation.hallway1stfloor_lights_turn_on_lights_when_motion_is_detected
                    - automation.hallway2ndfloor_lights_turn_on_lights_when_motion_is_detected
        default:
          - service: automation.turn_off
            target:
              entity_id:
                - automation.livingroom_lights_turn_on_lights_when_motion_is_detected
                - automation.kitchen_lights_turn_on_lights_when_motion_is_detected
                - automation.study_lights_turn_on_lights_when_motion_is_detected
                - automation.entry_lights_turn_on_lights_when_motion_is_detected
                - automation.hallway1stfloor_lights_turn_on_lights_when_motion_is_detected
                - automation.hallway2ndfloor_lights_turn_on_lights_when_motion_is_detected
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  all_lighting_automations:
    entities:
      - group.bedroom_lighting_automations
      - group.livingroom_lighting_automations
      - group.kitchen_lighting_automations
      - group.study_lighting_automations
      #- automation.bathroom_light_turn_on_light_through_motion
      - automation.entry_lights_turn_on_lights_when_motion_is_detected
  # update_illumination_limit_automations:
  #   entities:
  #     - automation.bedroom_light_update_illumination_limit
  #     - automation.kitchen_light_update_illumination_limit
  #     - automation.livingroom_light_update_illumination_limit
  #     - automation.study_light_update_illumination_limit

#################
#    SCRIPTS    #
#################
script:
  toggle_lights_with_adaptive_brightness:
    alias: Toggle lights with adaptive brightness
    description: Toggle lights with adaptive brightness and different click actions based on button clicks.
    # id: yaml_script_toggle_lights_with_adaptive_brightness
    mode: parallel
    fields:
      light_entity:
        description: Entity ID of the light to control
        example: light.livingroom
      click_count:
        description: The number of times the switch is clicked
        example: 2
      transition_time:
        description: Transition time of the lights
        example: 0
        default: "0.0"
        required: false
    sequence:
      - choose:
          # Single Click: Toggle light with adaptive brightness
          - conditions:
              - condition: template
                value_template: "{{ click_count | int == 1 }}"
            sequence:
              - service: light.toggle
                data:
                  entity_id: "{{ light_entity }}"
                  brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
                  color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
                  transition: "{{ transition_time }}"
          # Double Click: Full brightness if below 100%, otherwise adaptive brightness
          - conditions:
              - condition: template
                value_template: "{{ click_count | int == 2 }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state(light_entity, 'off') or (state_attr(light_entity, 'brightness') | int(0) < 250) or (state_attr(light_entity, 'color_temp_kelvin') | int(0) < 4000) }}"
                    sequence:
                      - service: light.turn_on
                        data:
                          entity_id: "{{ light_entity }}"
                          brightness_pct: 100
                          color_temp_kelvin: 4200 # "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
                          transition: "{{ transition_time }}"
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ light_entity }}"
                      brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
                      color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
                      transition: "{{ transition_time }}"
          # Triple Click: Set brightness to 10% if above, otherwise reset to adaptive brightness
          - conditions:
              - condition: template
                value_template: "{{ click_count | int == 3 }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state(light_entity, 'off') or (state_attr(light_entity, 'brightness') | int(100) > 30) }}" # Brightness 30/256, so around 12%
                    sequence:
                      - service: light.turn_on
                        data:
                          entity_id: "{{ light_entity }}"
                          brightness_pct: 10
                          color_temp_kelvin: 2300 #"{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
                          transition: "{{ transition_time }}"
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ light_entity }}"
                      brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'brightness_pct') | int }}"
                      color_temp_kelvin: "{{ state_attr('switch.adaptive_lighting_adaptive_lighting', 'color_temp_kelvin') | int }}"
                      transition: "{{ transition_time }}"
        default:
          - service: logbook.log
            data:
              name: "Toggle Lights Script"
              message: >
                "Default option chosen in 'toggle_lights_with_adaptive_brightness'.
                light_entity: {{ light_entity }}, click_count: {{ click_count }}, transition_time: {{ transition_time }}"
              entity_id: "script.toggle_lights_with_adaptive_brightness"
          - service: system_log.write
            data:
              level: warning
              message: >
                "Default option chosen in 'toggle_lights_with_adaptive_brightness'.
                light_entity: {{ light_entity }}, click_count: {{ click_count }}, transition_time: {{ transition_time }}"
