homeassistant:
  customize:

adaptive_lighting:
  name: "Adaptive lighting"
  lights:
    - light.entry
    - light.hallway_1st_floor
    - light.hallway_2nd_floor
    - light.kitchen
    - light.study
  initial_transition: 1
  min_brightness: 30
  min_color_temp: 2000
  max_color_temp: 5000
  sunrise_time: "06:15:00"

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  all_lighting_automations:
    entities:
      - group.bedroom_lighting_automations
      - group.livingroom_lighting_automations
      - group.kitchen_lighting_automations
      - group.study_lighting_automations
      - automation.bathroom_light_turn_on_light_through_motion
      - automation.entry_light_turn_on_light_through_motion
  update_illumination_limit_automations:
    entities:
      - automation.bedroom_light_update_illumination_limit
      - automation.kitchen_light_update_illumination_limit
      - automation.livingroom_light_update_illumination_limit
      - automation.study_light_update_illumination_limit

#################
#    SCRIPTS    #
#################
script:
