homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      house_occupied:
        device_class: occupancy
        value_template: >-
          {{
            is_state('person.sander_blok','home') or
            is_state('person.tamara','home') or
            is_state('device_tracker.phone_kb', 'home') or
            is_state('device_tracker.phone_kb_2', 'home') or
            is_state('calendar.gasten_in_huis','on')
          }}
        availability_template: >-
          {{
            states('person.sander_blok') not in ['unavailable', 'unknown', 'none', None]
            or states('person.tamara') not in ['unavailable', 'unknown', 'none', None]
            or states('device_tracker.phone_kb') not in ['unavailable', 'unknown', 'none', None]
            or states('device_tracker.phone_kb_2') not in ['unavailable', 'unknown', 'none', None]
            or states('calendar.gasten_in_huis') not in ['unavailable', 'unknown', 'none', None]
          }}
########################
#    INPUT BOOLEANS    #
########################
input_boolean:
  enable_tamara_mode:
    name: "Enable Tamara mode"
    icon: mdi:person
  tamara_mode:
    name: "Tamara Mode"
    icon: mdi:person

##################
#    SWITCHES    #
##################
switch:
  - platform: template
    switches:
      tamara_mode:
        friendly_name: "Tamara mode"
        value_template: "{{ is_state('input_boolean.tamara_mode', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.tamara_mode
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.tamara_mode

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[occupancy|lights]execute_tamara_mode'
    mode: restart
    trigger:
      - platform: state
        entity_id: input_boolean.tamara_mode
    condition:
      condition: state
      entity_id: input_boolean.enable_tamara_mode
      state: 'on'
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.tamara_mode
                state: "on"
            sequence:
              - service: automation.turn_off
                entity_id: group.all_lighting_automations
              - service: tts.cloud_say
                entity_id: media_player.living_room_speaker
                data:
                  message: "Tamara mode enabled. All motion-activated light automations have been turned off."
                  language: en-IE
          - conditions:
              - condition: state
                entity_id: input_boolean.tamara_mode
                state: "off"
            sequence:
              - service: automation.turn_on
                entity_id: group.all_lighting_automations
              - service: tts.cloud_say
                entity_id: media_player.living_room_speaker
                data:
                  message: "Tamara mode disabled. The house is now fully automated again!"
                  language: en-IE

  - alias: '[occupancy|sensors]Deconz Xiaomi Aqara Motion attributes fix'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay:
          minutes: 2
      # set hacked motion sensor timout duration to 5 seconds
      - service: deconz.configure
        data:
          entity: binary_sensor.motion_sensor_bedroom
          field: "/config"
          data: {"duration": 5}
      - delay:
          seconds: 1
      - service: deconz.configure
        data:
          entity: binary_sensor.motion_sensor_study
          field: "/config"
          data: {"duration": 5}
      - delay:
          seconds: 1
      - service: deconz.configure
        data:
          entity: binary_sensor.motion_sensor_livingroom3
          field: "/config"
          data: {"duration": 5}
      - delay:
          seconds: 1
      - service: deconz.configure
        data:
          entity: binary_sensor.motion_sensor_livingroom2
          field: "/config"
          data: {"duration": 5}
      - delay:
          seconds: 1
      - service: deconz.configure
        data:
          entity: binary_sensor.motion_sensor_kitchen
          field: "/config"
          data: {"duration": 5}
      - service: deconz.configure
        data:
          entity: binary_sensor.hallway_1st_floor_motion_1
          field: "/config"
          data: {"duration": 5}
      - service: deconz.configure
        data:
          entity: binary_sensor.hallway_1st_floor_motion_2
          field: "/config"
          data: {"duration": 5}
      - service: deconz.configure
        data:
          entity: binary_sensor.hallway_2nd_floor_motion_1
          field: "/config"
          data: {"duration": 5}
      - service: deconz.configure
        data:
          entity: binary_sensor.hallway_2nd_floor_motion_2
          field: "/config"
          data: {"duration": 5}
      - delay:
          seconds: 1
      # Set study chair vibration sensitivity to 1 (highest)
      - service: deconz.configure
        data:
          entity: binary_sensor.vibration_sensor
          data: {"sensitivity": 2}
          field: "/config"

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
