sensor:
  - platform: miflora
    mac: 'C4:7C:8D:6B:17:07'
    name: Coffee Plant
    force_update: true
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:6B:12:B5'
    name: Bonsai
    force_update: true
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:6A:F3:7B'
    name: Calathea
    force_update: true
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:6B:16:8A'
    name: Herbs
    force_update: true
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery