homeassistant:
  customize:
    switch.blitzwolf_coffeeplant:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_coffeeplant_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_coffeeplant_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_coffeeplant_energy_today:
      icon: mdi:lightning-bolt

    switch.blitzwolf_computer_2:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_computer_2_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_computer_2_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_computer_2_energy_today:
      icon: mdi:lightning-bolt

    switch.blitzwolf_computer:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_computer_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_computer_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_computer_energy_today:
      icon: mdi:lightning-bolt

    switch.blitzwolf_watercooker:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_watercooker_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_watercooker_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_watercooker_energy_today:
      icon: mdi:lightning-bolt

    switch.blitzwolf_mediacenter:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_mediacenter_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_mediacenter_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_mediacenter_energy_today:
      icon: mdi:lightning-bolt

    switch.blitzwolf_electricblanket:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_electricblanket_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_electricblanket_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_electricblanket_energy_today:
      icon: mdi:lightning-bolt

    switch.blitzwolf_nuc:
      icon: mdi:power-socket-eu
    sensor.blitzwolf_nuc_energy_power:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_nuc_energy_total:
      icon: mdi:lightning-bolt
    sensor.blitzwolf_nuc_energy_today:
      icon: mdi:lightning-bolt

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      total_power:
        unit_of_measurement: 'Watts'
        value_template: "{{ (states.sensor.blitzwolf_electricblanket_energy_power.state|float + states.sensor.blitzwolf_computer_energy_power.state|float + states.sensor.blitzwolf_mediacenter_energy_power.state|float + states.sensor.blitzwolf_watercooker_energy_power.state|float + states.sensor.blitzwolf_coffeeplant_energy_power.state|float) |round(2) }}"
      total_energy_today:
        unit_of_measurement: 'kWh'
        value_template: "{{ (states.sensor.blitzwolf_electricblanket_energy_today.state|float + states.sensor.blitzwolf_computer_energy_today.state|float + states.sensor.blitzwolf_mediacenter_energy_today.state|float + states.sensor.blitzwolf_watercooker_energy_today.state|float + states.sensor.blitzwolf_coffeeplant_energy_today.state|float) |round(2) }}"
      electricblanket_cost_today:
        unit_of_measurement: '€'
        value_template: "{{ (states.sensor.blitzwolf_electricblanket_energy_today.state|float * 0.22) |round(2) }}"
      mediacenter_cost_today:
        unit_of_measurement: '€'
        value_template: "{{ (states.sensor.blitzwolf_mediacenter_energy_today.state|float * 0.22) |round(2) }}"
      watercooker_cost_today:
        unit_of_measurement: '€'
        value_template: "{{ (states.sensor.blitzwolf_watercooker_energy_today.state|float * 0.22) |round(2) }}"
      computer_cost_today:
        unit_of_measurement: '€'
        value_template: "{{ (states.sensor.blitzwolf_computer_energy_today.state|float * 0.22) |round(2) }}"
      coffeeplant_cost_today:
        unit_of_measurement: '€'
        value_template: "{{ (states.sensor.blitzwolf_coffeeplant_energy_today.state|float * 0.22) |round(2) }}"
      total_energy_cost_today:
        unit_of_measurement: '€'
        value_template: "{{ (states.sensor.total_energy_today.state|float * 0.22) |round(2) }}"


  - platform: rest
    resource: http://192.168.1.61/api/v1/smartmeter?limit=1&json=object&round=on
    name: Huidig verbruik
    value_template: '{{ value_json.0.CONSUMPTION_W }}'
    unit_of_measurement: "W"

  - platform: rest
    resource: http://192.168.1.61/api/v1/powergas/min?limit=1&json=object&round=off
    name: Current gas usage per min
    value_template: '{{ value_json.0.CONSUMPTION_GAS_DELTA_M3 }}'
    unit_of_measurement: "m3"

  - platform: rest
    resource: http://192.168.1.61/api/v1/powergas/hour?limit=1&json=object&round=off
    name: Current gas usage per hour
    value_template: '{{ value_json.0.CONSUMPTION_GAS_DELTA_M3 }}'
    unit_of_measurement: "m3"

  - platform: rest
    resource: http://192.168.1.61/api/v1/smartmeter?limit=1&json=object&round=off
    name: Meterstand hoog
    value_template: '{{ value_json.0.CONSUMPTION_KWH_HIGH | round(2) }}'
    unit_of_measurement: "kWh"

  - platform: rest
    resource: http://192.168.1.61/api/v1/smartmeter?limit=1&json=object&round=off
    name: Meterstand laag
    value_template: '{{ value_json.0.CONSUMPTION_KWH_LOW | round(2) }}'
    unit_of_measurement: "kWh"
    
  - platform: rest
    resource: http://192.168.1.61/api/v1/financial/day?limit=1&json=object&round=off
    name: Kosten Hoog Tarief
    value_template: '{{ value_json.0.CONSUMPTION_COST_ELECTRICITY_HIGH | round(2) }}'
    unit_of_measurement: "€"

  - platform: rest
    resource: http://192.168.1.61/api/v1/financial/day?limit=1&json=object&round=off
    name: Kosten Laag Tarief
    value_template: '{{ value_json.0.CONSUMPTION_COST_ELECTRICITY_LOW | round(2) }}'
    unit_of_measurement: "€"

  - platform: rest
    resource: http://192.168.1.61/api/v1/financial/month?limit=1&json=object&round=off
    name: Maand Hoog Tarief
    value_template: '{{ value_json.0.CONSUMPTION_COST_ELECTRICITY_HIGH | round(2) }}'
    unit_of_measurement: "€"

  - platform: rest
    resource: http://192.168.1.61/api/v1/financial/month?limit=1&json=object&round=off
    name: Maand Laag Tarief
    value_template: '{{ value_json.0.CONSUMPTION_COST_ELECTRICITY_LOW | round(2) }}'
    unit_of_measurement: "€"

  - platform: rest
    resource: http://192.168.1.61/api/v1/powergas/day?limit=1&json=object&round=off
    name: Verbruik Per Dag
    value_template: '{{ value_json.0.CONSUMPTION_DELTA_KWH | round(4) }}'
    unit_of_measurement: "kWh"

  - platform: rest
    resource: http://192.168.1.61/api/v1/powergas/day?limit=1&json=object&round=off
    name: Gasverbruik Per Dag
    value_template: '{{ value_json.0.CONSUMPTION_GAS_DELTA_M3 | round(4) }}'
    unit_of_measurement: "m3"

  - platform: mqtt
    name: timestamp_local
    state_topic: "p1monitor/smartmeter/timestamp_local"
    device_class: timestamp
  - platform: mqtt
    name: timestamp_utc
    state_topic: "p1monitor/smartmeter/timestamp_utc"
    device_class: timestamp
  - platform: mqtt
    name: consumption_gas_m3
    state_topic: "p1monitor/smartmeter/consumption_gas_m3"
    unit_of_measurement: m3
    force_update: true
  - platform: mqtt
    name: consumption_kwh_high
    state_topic: "p1monitor/smartmeter/consumption_kwh_high"
    unit_of_measurement: kWh
  - platform: mqtt
    name: consumption_kwh_low
    state_topic: "p1monitor/smartmeter/consumption_kwh_low"
    unit_of_measurement: kWh
  - platform: mqtt
    name: consumption_kw
    state_topic: "p1monitor/smartmeter/consumption_kw"
    device_class: power
    unit_of_measurement: kW
  - platform: mqtt
    name: tarifcode
    state_topic: "p1monitor/smartmeter/tarifcode"
  - platform: mqtt
    name: record_is_processed
    state_topic: "p1monitor/smartmeter/record_is_processed"
  - platform: mqtt
    name: consumption_l1_w
    state_topic: "p1monitor/phase/consumption_l1_w"
    device_class: power
    unit_of_measurement: W
  - platform: mqtt
    name: l1_v
    state_topic: "p1monitor/phase/l1_v"
    unit_of_measurement: V
  - platform: mqtt
    name: l1_a
    state_topic: "p1monitor/phase/l1_a"
    unit_of_measurement: A

  - platform: template
    sensors:
      energie_kosten_dag:
        value_template: "{{ states('sensor.kosten_hoog_tarief') | float + states('sensor.kosten_laag_tarief') | float | round(2) }}"
        unit_of_measurement: "€"
      energie_kosten_maand:
        value_template: "{{ states('sensor.maand_hoog_tarief') | float + states('sensor.maand_laag_tarief') | float | round(2) }}"
        unit_of_measurement: "€"
      total_power_watt:
        value_template: "{{ states('sensor.consumption_kw') | float * 1000 | float | round(2) }}"
        unit_of_measurement: "W"
      current_costs_per_hour:
        value_template: "{{ ( states('sensor.consumption_kw') | float * (states('sensor.kosten_hoog_tarief') | float) | float ) | round(2) }}"
        unit_of_measurement: "€/h"
  
  - platform: derivative
    source: sensor.consumption_gas_m3
    name: Gas consumption per hour
    time_window: "00:10:00"
      


########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: "Power state on HA start-up"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "sonoffs/cmnd/state"
          payload: ""

# Example automations.yaml entry
  - id: 'sonoff_firmware_installed'
    alias: Sonoff Firmware Installed
    trigger:
    - event: start
      platform: homeassistant
    action:
    - data:
        payload: '2'
        topic: sonoffs/cmnd/status
      service: mqtt.publish
    initial_state: 'true'

# Example automations.yaml entry
  - alias: "Enable MQTT discovery for all devices"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/SetOption19"
          payload: "1"
          
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  blitzwolf_coffeeplant:
    entities:
      - switch.blitzwolf_coffeeplant
      - sensor.blitzwolf_coffeeplant_status
      - sensor.blitzwolf_coffeeplant_energy_voltage      
      - sensor.blitzwolf_coffeeplant_energy_current
      - sensor.blitzwolf_coffeeplant_energy_power
      - sensor.blitzwolf_coffeeplant_energy_apparentpower
      - sensor.blitzwolf_coffeeplant_energy_reactivepower
      - sensor.blitzwolf_coffeeplant_energy_today
      - sensor.blitzwolf_coffeeplant_energy_yesterday
      - sensor.blitzwolf_coffeeplant_energy_total
      - sensor.blitzwolf_coffeeplant_energy_totalstarttime
  blitzwolf_computer:
    entities:
      - switch.blitzwolf_computer_2
      - sensor.blitzwolf_computer_status
      - sensor.blitzwolf_computer_energy_voltage      
      - sensor.blitzwolf_computer_energy_current
      - sensor.blitzwolf_computer_energy_power
      - sensor.blitzwolf_computer_energy_apparentpower
      - sensor.blitzwolf_computer_energy_reactivepower
      - sensor.blitzwolf_computer_energy_today
      - sensor.blitzwolf_computer_energy_yesterday
      - sensor.blitzwolf_computer_energy_total_2
      - sensor.blitzwolf_computer_energy_totalstarttime
  blitzwolf_electricblanket:
    entities:
      - switch.blitzwolf_electricblanket
      - sensor.blitzwolf_electricblanket_status
      - sensor.blitzwolf_electricblanket_energy_voltage      
      - sensor.blitzwolf_electricblanket_energy_current
      - sensor.blitzwolf_electricblanket_energy_power
      - sensor.blitzwolf_electricblanket_energy_apparentpower
      - sensor.blitzwolf_electricblanket_energy_reactivepower
      - sensor.blitzwolf_electricblanket_energy_today
      - sensor.blitzwolf_electricblanket_energy_yesterday
      - sensor.blitzwolf_electricblanket_energy_total
      - sensor.blitzwolf_electricblanket_energy_totalstarttime
  blitzwolf_mediacenter:
    entities:
      - switch.blitzwolf_mediacenter
      - sensor.blitzwolf_mediacenter_status
      - sensor.blitzwolf_mediacenter_energy_voltage      
      - sensor.blitzwolf_mediacenter_energy_current
      - sensor.blitzwolf_mediacenter_energy_power
      - sensor.blitzwolf_mediacenter_energy_apparentpower
      - sensor.blitzwolf_mediacenter_energy_reactivepower
      - sensor.blitzwolf_mediacenter_energy_today
      - sensor.blitzwolf_mediacenter_energy_yesterday
      - sensor.blitzwolf_mediacenter_energy_total
      - sensor.blitzwolf_mediacenter_energy_totalstarttime
  blitzwolf_watercooker:
    entities:
      - switch.blitzwolf_watercooker
      - sensor.blitzwolf_watercooker_status
      - sensor.blitzwolf_watercooker_energy_voltage      
      - sensor.blitzwolf_watercooker_energy_current
      - sensor.blitzwolf_watercooker_energy_power
      - sensor.blitzwolf_watercooker_energy_apparentpower
      - sensor.blitzwolf_watercooker_energy_reactivepower
      - sensor.blitzwolf_watercooker_energy_today
      - sensor.blitzwolf_watercooker_energy_yesterday
      - sensor.blitzwolf_watercooker_energy_total
      - sensor.blitzwolf_watercooker_energy_totalstarttime
  blitzwolf_nuc:
    entities:
      - switch.blitzwolf_nuc
      - sensor.blitzwolf_nuc_status
      - sensor.blitzwolf_nuc_energy_voltage      
      - sensor.blitzwolf_nuc_energy_current
      - sensor.blitzwolf_nuc_energy_power
      - sensor.blitzwolf_nuc_energy_apparentpower
      - sensor.blitzwolf_nuc_energy_reactivepower
      - sensor.blitzwolf_nuc_energy_today
      - sensor.blitzwolf_nuc_energy_yesterday
      - sensor.blitzwolf_nuc_energy_total
      - sensor.blitzwolf_nuc_energy_totalstarttime
  meter_readings:
    name: Meter readings
    entities:
      - sensor.timestamp_local
      - sensor.timestamp_utc
      - sensor.consumption_gas_m3
      - sensor.consumption_kwh_high
      - sensor.consumption_kwh_low
      - sensor.consumption_kw
      - sensor.tarifcode
      - sensor.record_is_processed
      - sensor.consumption_l1_w
      - sensor.l1_v
      - sensor.l1_a
#################
#    SCRIPTS    #
#################
script: