homeassistant:
  customize:

utility_meter:
  hourly_energy_use:
    source: sensor.total_energy_usage
    delta_values: False
    cycle: hourly
    unique_id: yaml_template_sensor_hourly_energy_use
    net_consumption: true
  daily_energy_use:
    source: sensor.total_energy_usage
    delta_values: False
    cycle: daily
    unique_id: yaml_template_sensor_daily_energy_use
    net_consumption: true
  weekly_energy_use:
    source: sensor.total_energy_usage
    delta_values: False
    cycle: weekly
    unique_id: yaml_template_sensor_weekly_energy_use
    net_consumption: true
  monthly_energy_use:
    source: sensor.total_energy_usage
    delta_values: False
    cycle: monthly
    unique_id: yaml_template_sensor_monthly_energy_use
    net_consumption: true
  yearly_energy_use:
    source: sensor.total_energy_usage
    delta_values: False
    cycle: yearly
    unique_id: yaml_template_sensor_yearly_energy_use
    net_consumption: true

  daily_unknown_energy:
    source: sensor.unknown_energy
    delta_values: False
    cycle: daily
    unique_id: yaml_template_sensor_daily_unknown_energy
    net_consumption: true

  # Water Use
  hourly_water_use:
    source: sensor.total_water
    delta_values: false
    cycle: hourly
    periodically_resetting: true
    unique_id: yaml_template_sensor_hourly_water_use
  daily_water_use:
    source: sensor.total_water
    delta_values: false
    cycle: daily
    periodically_resetting: true
    unique_id: yaml_template_sensor_daily_water_use
  weekly_water_use:
    source: sensor.total_water
    delta_values: false
    cycle: weekly
    periodically_resetting: true
    unique_id: yaml_template_sensor_weekly_water_use
  monthly_water_use:
    source: sensor.total_water
    delta_values: false
    cycle: monthly
    periodically_resetting: true
    unique_id: yaml_template_sensor_monthly_water_use
  yearly_water_use:
    source: sensor.total_water
    delta_values: false
    cycle: yearly
    periodically_resetting: true
    unique_id: yaml_template_sensor_yearly_water_use

  # Heatpump tapwater consumption
  heatpump_tapwater_hourly_energy_use:
    source: sensor.heatpump_tapwater_energy_usage
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_heatpump_tapwater_hourly_energy_use
  heatpump_tapwater_daily_energy_use:
    source: sensor.heatpump_tapwater_energy_usage
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_heatpump_tapwater_daily_energy_use
  heatpump_tapwater_weekly_energy_use:
    source: sensor.heatpump_tapwater_energy_usage
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_heatpump_tapwater_weekly_energy_use
  heatpump_tapwater_monthly_energy_use:
    source: sensor.heatpump_tapwater_energy_usage
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_heatpump_tapwater_monthly_energy_use
  heatpump_tapwater_yearly_energy_use:
    source: sensor.heatpump_tapwater_energy_usage
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_heatpump_tapwater_yearly_energy_use

  # Heatpump heating consumption
  heatpump_verwarming_hourly_energy_use:
    source: sensor.heatpump_heating_energy_usage
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_heatpump_verwarming_hourly_energy_use
  heatpump_verwarming_daily_energy_use:
    source: sensor.heatpump_heating_energy_usage
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_heatpump_verwarming_daily_energy_use
  heatpump_verwarming_weekly_energy_use:
    source: sensor.heatpump_heating_energy_usage
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_heatpump_verwarming_weekly_energy_use
  heatpump_verwarming_monthly_energy_use:
    source: sensor.heatpump_heating_energy_usage
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_heatpump_verwarming_monthly_energy_use
  heatpump_verwarming_yearly_energy_use:
    source: sensor.heatpump_heating_energy_usage
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_heatpump_verwarming_yearly_energy_use

  # Heatpump tapwater production
  heatpump_tapwater_hourly_heat_production:
    source: sensor.heatpump_tapwater_heat_amount
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_heatpump_tapwater_hourly_heat_production
  heatpump_tapwater_daily_heat_production:
    source: sensor.heatpump_tapwater_heat_amount
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_heatpump_tapwater_daily_heat_production
  heatpump_tapwater_weekly_heat_production:
    source: sensor.heatpump_tapwater_heat_amount
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_heatpump_tapwater_weekly_heat_production
  heatpump_tapwater_monthly_heat_production:
    source: sensor.heatpump_tapwater_heat_amount
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_heatpump_tapwater_monthly_heat_production
  heatpump_tapwater_yearly_heat_production:
    source: sensor.heatpump_tapwater_heat_amount
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_heatpump_tapwater_yearly_heat_production

  # Heatpump heating production
  heatpump_verwarming_hourly_heat_production:
    source: sensor.heatpump_heat_amount_heating
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_heatpump_verwarming_hourly_heat_production
  heatpump_verwarming_daily_heat_production:
    source: sensor.heatpump_heat_amount_heating
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_heatpump_verwarming_daily_heat_production
  heatpump_verwarming_weekly_heat_production:
    source: sensor.heatpump_heat_amount_heating
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_heatpump_verwarming_weekly_heat_production
  heatpump_verwarming_monthly_heat_production:
    source: sensor.heatpump_heat_amount_heating
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_heatpump_verwarming_monthly_heat_production
  heatpump_verwarming_yearly_heat_production:
    source: sensor.heatpump_heat_amount_heating
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_heatpump_verwarming_yearly_heat_production

  # Heatpump Circulation
  heatpump_circulation_hourly_energy_use:
    source: sensor.blitzwolf_heatpump_consumption
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_heatpump_circulation_hourly_energy_use
  heatpump_circulation_daily_energy_use:
    source: sensor.blitzwolf_heatpump_consumption
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_heatpump_circulation_daily_energy_use
  heatpump_circulation_weekly_energy_use:
    source: sensor.blitzwolf_heatpump_consumption
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_heatpump_circulation_weekly_energy_use
  heatpump_circulation_monthly_energy_use:
    source: sensor.blitzwolf_heatpump_consumption
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_heatpump_circulation_monthly_energy_use
  heatpump_circulation_yearly_energy_use:
    source: sensor.blitzwolf_heatpump_consumption
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_heatpump_circulation_yearly_energy_use

  # Vacuums
  vacuums_hourly_energy_use:
    source: sensor.vacuums_energy_estimate
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_vacuums_hourly_energy_use
    name: Vacuums Hourly Energy Use
  vacuums_daily_energy_use:
    source: sensor.vacuums_energy_estimate
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_vacuums_daily_energy_use
    name: Vacuums Daily Energy Use
  vacuums_weekly_energy_use:
    source: sensor.vacuums_energy_estimate
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_vacuums_weekly_energy_use
    name: Vacuums Weekly Energy Use
  vacuums_monthly_energy_use:
    source: sensor.vacuums_energy_estimate
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_vacuums_monthly_energy_use
    name: Vacuums Monthly Energy Use
  vacuums_yearly_energy_use:
    source: sensor.vacuums_energy_estimate
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_vacuums_yearly_energy_use
    name: Vacuums Yearly Energy Use

# Zonnepanelen:
  solar_panel_hourly_energy_production:
    source: sensor.solar_panel_energy_production
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_solar_panel_hourly_energy_production
    name: Solar Panel Hourly Energy Production
  solar_panel_daily_energy_production:
    source: sensor.solar_panel_energy_production
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_solar_panel_daily_energy_production
    name: Solar Panel Daily Energy Production
  solar_panel_weekly_energy_production:
    source: sensor.solar_panel_energy_production
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_solar_panel_weekly_energy_production
    name: Solar Panel Weekly Energy Production
  solar_panel_monthly_energy_production:
    source: sensor.solar_panel_energy_production
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_solar_panel_monthly_energy_production
    name: Solar Panel Monthly Energy Production
  solar_panel_yearly_energy_production:
    source: sensor.solar_panel_energy_production
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_solar_panel_yearly_energy_production
    name: Solar Panel Yearly Energy Production

  # Ventilation usage
  ventilation_hourly_energy_use:
    source: sensor.ventilation_energy_usage
    delta_values: False
    cycle: hourly
    unique_id: yaml_template_sensor_hourly_ventilation_energy_use
    net_consumption: true
  ventilation_daily_energy_use:
    source: sensor.ventilation_energy_usage
    delta_values: False
    cycle: daily
    unique_id: yaml_template_sensor_daily_ventilation_energy_use
    net_consumption: true
  ventilation_weekly_energy_use:
    source: sensor.ventilation_energy_usage
    delta_values: False
    cycle: weekly
    unique_id: yaml_template_sensor_weekly_ventilation_energy_use
    net_consumption: true
  ventilation_monthly_energy_use:
    source: sensor.ventilation_energy_usage
    delta_values: False
    cycle: monthly
    unique_id: yaml_template_sensor_monthly_ventilation_energy_use
    net_consumption: true
  ventilation_yearly_energy_use:
    source: sensor.ventilation_energy_usage
    delta_values: False
    cycle: yearly
    unique_id: yaml_template_sensor_yearly_ventilation_energy_use
    net_consumption: true




############################## ELECTRICITY COST UTILITY METERS ##############################

  # TOTAL_ELECTRICITY_COST
  total_electricity_cost_hourly_energy_use:
    source: sensor.total_electricity_cost
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_total_electricity_cost_hourly_energy_use
    name: Total Electricity Cost Hourly Energy Use
  total_electricity_cost_daily_energy_use:
    source: sensor.total_electricity_cost
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_total_electricity_cost_daily_energy_use
    name: Total Electricity Cost Daily Energy Use
  total_electricity_cost_weekly_energy_use:
    source: sensor.total_electricity_cost
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_total_electricity_cost_weekly_energy_use
    name: Total Electricity Cost Weekly Energy Use
  total_electricity_cost_monthly_energy_use:
    source: sensor.total_electricity_cost
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_total_electricity_cost_monthly_energy_use
    name: Total Electricity Cost Monthly Energy Use
  total_electricity_cost_yearly_energy_use:
    source: sensor.total_electricity_cost
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_total_electricity_cost_yearly_energy_use
    name: Total Electricity Cost Yearly Energy Use

  # COMPUTER_ELECTRICITY_COST
  computer_electricity_cost_hourly_energy_use:
    source: sensor.blitzwolf_computer_energy_cost_hourly
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_computer_electricity_cost_hourly_energy_use
    name: Computer Electricity Cost Hourly Energy Use
  computer_electricity_cost_daily_energy_use:
    source: sensor.blitzwolf_computer_energy_cost_hourly
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_computer_electricity_cost_daily_energy_use
    name: Computer Electricity Cost Daily Energy Use
  computer_electricity_cost_weekly_energy_use:
    source: sensor.blitzwolf_computer_energy_cost_hourly
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_computer_electricity_cost_weekly_energy_use
    name: Computer Electricity Cost Weekly Energy Use
  computer_electricity_cost_monthly_energy_use:
    source: sensor.blitzwolf_computer_energy_cost_hourly
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_computer_electricity_cost_monthly_energy_use
    name: Computer Electricity Cost Monthly Energy Use
  computer_electricity_cost_yearly_energy_use:
    source: sensor.blitzwolf_computer_energy_cost_hourly
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_computer_electricity_cost_yearly_energy_use
    name: Computer Electricity Cost Yearly Energy Use

  # NAS_ELECTRICITY_COST
  nas_electricity_cost_hourly_energy_use:
    source: sensor.blitzwolf_nas_energy_cost_hourly
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_nas_electricity_cost_hourly_energy_use
    name: Nas Electricity Cost Hourly Energy Use
  nas_electricity_cost_daily_energy_use:
    source: sensor.blitzwolf_nas_energy_cost_hourly
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_nas_electricity_cost_daily_energy_use
    name: Nas Electricity Cost Daily Energy Use
  nas_electricity_cost_weekly_energy_use:
    source: sensor.blitzwolf_nas_energy_cost_hourly
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_nas_electricity_cost_weekly_energy_use
    name: Nas Electricity Cost Weekly Energy Use
  nas_electricity_cost_monthly_energy_use:
    source: sensor.blitzwolf_nas_energy_cost_hourly
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_nas_electricity_cost_monthly_energy_use
    name: Nas Electricity Cost Monthly Energy Use
  nas_electricity_cost_yearly_energy_use:
    source: sensor.blitzwolf_nas_energy_cost_hourly
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_nas_electricity_cost_yearly_energy_use
    name: Nas Electricity Cost Yearly Energy Use

  # HEATPUMP_ELECTRICITY_COST
  heatpump_electricity_cost_hourly_energy_use:
    source: sensor.blitzwolf_heatpump_energy_cost_hourly
    delta_values: false
    cycle: hourly
    unique_id: yaml_utilitymeter_heatpump_electricity_cost_hourly_energy_use
    name: Heatpump Electricity Cost Hourly Energy Use
  heatpump_electricity_cost_daily_energy_use:
    source: sensor.blitzwolf_heatpump_energy_cost_hourly
    delta_values: false
    cycle: daily
    unique_id: yaml_utilitymeter_heatpump_electricity_cost_daily_energy_use
    name: Heatpump Electricity Cost Daily Energy Use
  heatpump_electricity_cost_weekly_energy_use:
    source: sensor.blitzwolf_heatpump_energy_cost_hourly
    delta_values: false
    cycle: weekly
    unique_id: yaml_utilitymeter_heatpump_electricity_cost_weekly_energy_use
    name: Heatpump Electricity Cost Weekly Energy Use
  heatpump_electricity_cost_monthly_energy_use:
    source: sensor.blitzwolf_heatpump_energy_cost_hourly
    delta_values: false
    cycle: monthly
    unique_id: yaml_utilitymeter_heatpump_electricity_cost_monthly_energy_use
    name: Heatpump Electricity Cost Monthly Energy Use
  heatpump_electricity_cost_yearly_energy_use:
    source: sensor.blitzwolf_heatpump_energy_cost_hourly
    delta_values: false
    cycle: yearly
    unique_id: yaml_utilitymeter_heatpump_electricity_cost_yearly_energy_use
    name: Heatpump Electricity Cost Yearly Energy Use
