homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:
  vacation_mode:
    name: Vacation mode

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: 'Vacation mode turned on'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: 'on'     
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - group.bedroom_lighting_automations
          - group.livingroom_lighting_automations
          - group.kitchen_lighting_automations
          - group.study_lighting_automations
      - service: light.turn_off
        entity_id: all
      - service: homeassistant.turn_on
        entity_id: 
          - group.vacation_mode_lights

  - alias: 'Vacation mode turned off'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: 'off'     
    action:
      - service: homeassistant.turn_on
        entity_id: 
          - group.bedroom_lighting_automations
          - group.livingroom_lighting_automations
          - group.kitchen_lighting_automations
          - group.study_lighting_automations
      - service: homeassistant.turn_off
        entity_id: 
          - group.vacation_mode_lights

  - alias: 'Turn on lights during vacation bedroom'
    trigger:
      - platform: sun
        event: sunrise
        offset: "-00:45:00"
      - platform: sun
        event: sunset
        offset: "-00:45:00"
    condition:
      - condition: state
        entity_id: person.sander_blok
        state:  not_home
    action:
      service: scene.turn_on
      entity_id:
        - scene.bedroom_bright_wakeup

  - alias: 'Turn off lights during vacation bedroom'
    trigger:
      - platform: sun
        event: sunrise
        offset: "+01:45:00"
      - platform: sun
        event: sunset
        offset: "+00:45:00"
    condition:
      - condition: state
        entity_id: person.sander_blok
        state:  not_home
    action:
      service: light.turn_off
      entity_id:
        - light.bedroom

  - alias: 'Turn on lights during vacation other'
    trigger:
      - platform: sun
        event: sunrise
        offset: "-00:15:00"
      - platform: sun
        event: sunset
        offset: "-01:45:00"
    condition:
      - condition: state
        entity_id: person.sander_blok
        state:  not_home
    action:
      service: scene.turn_on
      entity_id:
        - scene.livingroom_bright_warm
        - scene.kitchen_bright_warm

  - alias: 'Turn off lights during vacation other'
    trigger:
      - platform: sun
        event: sunrise
        offset: "+02:15:00"
      - platform: sun
        event: sunset
        offset: "+01:15:00"
    condition:
      - condition: state
        entity_id: person.sander_blok
        state:  not_home
    action:
      service: light.turn_off
      entity_id:
        - light.living_room
        - light.kitchen
        - light.study

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  vacation_mode_lights:
    entities:
      - automation.turn_on_lights_during_vacation_other
      - automation.turn_off_lights_during_vacation_other
      - automation.turn_on_lights_during_vacation_bedroom
      - automation.turn_off_lights_during_vacation_bedroom

#################
#    SCRIPTS    #
#################
script: