homeassistant:
  customize:
    automation.auto_clean_litterbox_when_not_home_check_every_10_min:
      icon: mdi:robot-vacuum
    automation.auto_clean_whole_house_when_not_home_check_every_10_min:
      icon: mdi:robot-vacuum
    automation.notification_when_consuela_is_done_cleaning:
      icon: mdi:robot-vacuum
    automation.turn_input_boolean_vacuumed_today_off:
      icon: mdi:robot-vacuum
    automation.drive_vacuum_to_trash_bin:
      icon: mdi:robot-vacuum
  customize_glob:
    "script.vacuum_*":
      icon: mdi:robot-vacuum

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.237
    token: !secret vacuum_token

input_select:
  vacuum_areas:
    options:
      - livingroom
      - kitchen
      - entry
      - study
      - hallway
      - bedroom
      - bathroom
    initial: livingroom
    icon: mdi:robot-vacuum

# utility_meter:
#   area_cleaned_today:
#     source: sensor.area_total_clean
#     cycle: daily
#   area_cleaned_since_empty_bin:
#     source: sensor.area_total_clean
#     cycle: yearly
#     tariffs:
#       - default
#       - backup

input_number:
  area_cleaned_at_start_of_day: #in minutes
    name: Area cleaned at the start of the day
    step: 1
    min: 0
    max: 100000
    mode: box
    unit_of_measurement: m2
  area_cleaned_at_last_empty_bin: #in minutes
    name: Area cleaned after last time empty bin
    step: 1
    min: 0
    max: 100000
    mode: box
    unit_of_measurement: m2

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      area_last_clean:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        unit_of_measurement: 'm2'
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaned_area')|int }}"
      area_total_clean:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        unit_of_measurement: 'm2'
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'total_cleaned_area')|int }}"
      area_cleaned_today:
        unit_of_measurement: 'm2'
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'total_cleaned_area')|int - states('input_number.area_cleaned_at_start_of_day')|int }}"
      area_cleaned_since_last_empty_bin:
        unit_of_measurement: 'm2'
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'total_cleaned_area')|int - states('input_number.area_cleaned_at_last_empty_bin')|int }}"
########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:
  # vacuumed_today:
  #   name: Checks if Consuela vacuumed today
  #   icon: mdi:robot-vacuum

##################
#    COUNTERS    #
##################
counter:
  # times_vacuumed_since_empty_bin:
  #   #initial: 0
  #   step: 1
  #   restore: true

#####################
#    AUTOMATIONS    #
#####################
automation:
#Auto clean whole house when I'm not home on mon, wed, fri
  - alias: '[home|vacuum]scheduled_cleanup'
    mode: single
    trigger:
      - platform: state
        entity_id: person.sander_blok
        from: 'home'
        # for: 00:10:00
      - platform: time
        at: '07:00:00'
    condition:
      - condition: or
        conditions:
          - condition: time
            weekday:
              - mon
              - wed
              - fri
          - condition: numeric_state
            entity_id: 'sensor.sander_home_yesterday'
            above: 16
      - condition: time
        after: '7:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: binary_sensor.house_occupied
        state: 'off'
      # - condition: not
      #   conditions:
      #     - condition: state
      #       entity_id: person.sander_blok
      #       state: 'home'
      - condition: numeric_state
        entity_id: sensor.area_cleaned_today
        below: 50
    action:
      - service: system_log.write
        data:
          message: 'Started vacuum automation: auto clean whole house when not home'
          level: info
      - service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      # - service: notify.mobile_app_blokmeister_op6
      #   data:
      #     message: "Started scheduled cleanup"
      #     title: "Home Assistant - Vacuum"
      #     data:
      #       icon: http://192.168.1.252:8123/local/icons/robot-vacuum.png
      - service: notify.mobile_app_blokmeister_op6_haapp
        data:
          message: "Started scheduled cleanup"
          title: "Home Assistant - Vacuum"
          data:
            group: info
            tag: vacuum
            icon_url: local/icons/robot-vacuum.png
            timeout: 1800
      # - service: input_boolean.turn_on
      #   data:
      #     entity_id: input_boolean.vacuumed_today
      # - service: counter.increment
      #   data:
      #     entity_id: counter.times_vacuumed_since_empty_bin

  - alias: '[home|vacuum]counter_drive_to_trashbin'
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        attribute: battery_level
        above: 99
      - platform: state
        entity_id: person.sander_blok
        to: 'home'
    condition:
      # - condition: numeric_state  
      #   entity_id: counter.times_vacuumed_since_empty_bin
      #   above: 2
      - condition: numeric_state  
        entity_id: sensor.area_cleaned_since_last_empty_bin
        above: 150
      - condition: state
        entity_id: person.sander_blok
        state: 'home'
      - condition: numeric_state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        attribute: battery_level
        above: 99
    action:
      - service: script.vacuum_goto_kitchen
      - service: notify.mobile_app_blokmeister_op6_haapp
        data:
          message: "Please empty vacuum bin"
          title: "Home Assistant - Vacuum"
          data:
            group: info
            tag: vacuum
            icon_url: local/icons/robot-vacuum.png
            timeout: 10800
      - wait_for_trigger:
          - platform: event
            event_type: xiaomi_aqara.click
            event_data:
              entity_id: binary_sensor.switch_vacuumcleaner
              click_type: double
        timeout:
          hours: 3
      # - service: utility_meter.reset
      #   entity_id: utility_meter.area_cleaned_since_empty_bin
      - delay:
          minutes: 20
      - service: input_number.set_value
        data:
          entity_id: input_number.area_cleaned_at_last_empty_bin
          value: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner','total_cleaned_area') }}"


#Turns off the vacuumed today boolean at the start of every day. Used by vacuum automations
  # - alias: '[home|vacuum]turn_off_vacuumed_today_each_night'
  #   trigger: 
  #     platform: time
  #     at: 01:00:00
  #   action:
  #     - service: system_log.write
  #       data:
  #         message: 'Turn off input boolean vacuumed today'
  #         level: info
  #     - service: input_boolean.turn_off
  #       data:
  #         entity_id: input_boolean.vacuumed_today

#Buttons:
  - alias: '[home|vauum]button_drive_to_trashbin'
    trigger: 
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_vacuumcleaner
        click_type: double
    condition:
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: docked
    action:
      - service: automation.trigger
        data:
          entity_id: automation.home_vacuum_counter_drive_to_trashbin
          skip_condition: true
      - wait_for_trigger:
          platform: state
          entity_id: vacuum.xiaomi_vacuum_cleaner
          to: 'Docked'
      - service: input_number.set_value
        data:
          entity_id: input_number.area_cleaned_at_last_empty_bin
          value: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner','total_cleaned_area') }}"
      # - service: script.vacuum_goto_kitchen
      # - service: counter.reset
      #   data:
      #     entity_id: counter.times_vacuumed_since_empty_bin

  - alias: '[home|vacuum]button_dock_vacuum'
    trigger: 
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_vacuumcleaner
        click_type: double
    condition:
      condition: template
      value_template: "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'docked') }}"
    action:
      - service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: '[home|vacuum]button_start_vacuum'
    trigger: 
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_vacuumcleaner
        click_type: single
    condition:
      condition: template
      value_template: "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    action:
      - service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: '[home|vacuum]button_pause_vacuum'
    trigger: 
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_vacuumcleaner
        click_type: single
    condition:
      condition: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      state: cleaning
    action:
      - service: vacuum.pause
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: '[home|vacuum]update_template_sensors'
    trigger:
      platform: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      to: 'cleaning'
    action:
      - repeat:
          while:
            - condition: state
              entity_id: vacuum.xiaomi_vacuum_cleaner
              state: 'cleaning'
          sequence:
            - service: homeassistant.update_entity
              data:
                entity_id:
                  - sensor.area_last_clean
                  - sensor.area_total_clean
                  - sensor.area_cleaned_today
            - delay: 00:00:05

  - alias: '[home|vacuum]reset_area_cleaned_input_number'
    trigger:
      platform: time
      at: '00:00:00'
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.area_cleaned_at_start_of_day
          value: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner','total_cleaned_area') }}"

########## NOTIFICATIONS ########## 
#Send a notification to Ariela when Consuela is done cleaning. Uses state of vacuum.xiaomi_vacuum_cleaner
  - alias: '[home|vacuum]notify_phone'
    trigger:
      platform: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      to: 'charging'
    action:
      service: script.vacuum_message_done_cleaning

  # - alias: '[home|vacuum]write_log_when_counter_changes'
  #   trigger:
  #     platform: state
  #     entity_id: counter.times_vacuumed_since_empty_bin
  #   action:
  #     - service: system_log.write
  #       data:
  #         message: 'Counter counter.times_vacuumed_since_empty_bin changed to {{ states.counter.times_vacuumed_since_empty_bin.state }}'
  #         level: info
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
  vacuum_around_litterbox_twice:
      alias: "Clean around litterbox"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[16618,28223,18568,29623]]
          
  vacuum_kitchen_twice:
      alias: "Clean kitchen"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[14898,24722,17198,26572]]
          
  vacuum_study_twice:
      alias: "Clean study"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[16611,21710,18811,24760]]
          
  vacuum_bedroom_twice:
      alias: "Clean bedroom"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[21786,20518,26336,24818]]
          
  vacuum_bathroom_twice:
      alias: "Clean bathroom"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[19634,21767,21484,23717]]
          
  vacuum_dining_twice:
      alias: "Clean dining area"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[18516,25061,22916,29661]]
          
  vacuum_tv_twice:
      alias: "Clean TV area"
      sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          repeats: 2
          zone: [[22840,25127,26540,29727]]

  vacuum_goto_kitchen:
      alias: "Go to kitchen"
      sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: "app_goto_target"
          params: [16000,25200]

  # vacuum_message_litterbox_clean:
  #     alias: "Message phone about litterbox cleaning"
  #     sequence:
  #       - service: notify.mobile_app_blokmeister_op6
  #         data:
  #           message: "Consuela has started cleaning around the litterbox."
  #           title: "Home Assistant - Consuela"
  #           data:
  #             icon: http://192.168.1.252:8123/local/icons/robot-vacuum.png
  #             image: "https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/6/678bffd33fa7882979bdcfd3fb3fc1b78badfdbf.png"

  # vacuum_message_scheduled_cleanup:
  #     alias: "Message phone about scheduled cleaning"
  #     sequence:
  #       - service: notify.mobile_app_blokmeister_op6
  #         data:
  #           message: "Consuela has started a scheduled cleanup."
  #           title: "Home Assistant - Consuela"
  #           data:
  #             icon: http://192.168.1.252:8123/local/icons/robot-vacuum.png
  #             image: "https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/6/678bffd33fa7882979bdcfd3fb3fc1b78badfdbf.png"

  # vacuum_message_done_cleaning:
  #     alias: "Message phone about scheduled cleaning"
  #     sequence:
  #       - service: notify.mobile_app_blokmeister_op6
  #         data:
  #           message: "Consuela is done cleaning."
  #           title: "Home Assistant - Consuela"
  #           data:
  #             icon: http://192.168.1.252:8123/local/icons/robot-vacuum.png
  #             image: "https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/6/678bffd33fa7882979bdcfd3fb3fc1b78badfdbf.png"
