homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      washingmachine_on:
        value_template: >
          {{ states('sensor.blitzwolf_washingmachine_energy_power')|float > 25 }}
########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
