homeassistant:
  customize: {}

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: template
    sensors:
      washingmachine_on:
        value_template: "{{ states('sensor.plug_washing_machine_power')|float > 25 }}"
        availability_template: "{{ states('sensor.plug_washing_machine_power')|is_number }}"
########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
