homeassistant:
  customize: {}

template:
  - binary_sensor:
      - name: Washingmachine On
        state: "{{ states('sensor.plug_washing_machine_power')|float > 25 }}"
        availability: "{{ states('sensor.plug_washing_machine_power')|is_number }}"
#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
