homeassistant:
  customize:

weather:
  - platform: buienradar
    name: 'Home'
    # Force 'Meetstation Volkel' to be used:
    forecast: true

camera:
  - platform: buienradar
#################
#    SENSORS    #
#################
sensor:
  - platform: buienradar
    timeframe: 120
    monitored_conditions:
      #current conditions:
      - condition
      - symbol
      - humidity
      - temperature
      - windspeed
      - winddirection
      - pressure
      - precipitation
      - irradiance

      #conditions for forecasted data:
      - symbol_1d
      - symbol_2d
      - symbol_3d
      - symbol_4d
      - symbol_5d
      - temperature_1d
      - temperature_2d
      - temperature_3d
      - temperature_4d
      - temperature_5d
      - mintemp_1d
      - rainchance_1d
      - rainchance_2d
      - sunchance_1d
      - sunchance_2d
      - rain_1d
      - rain_2d
      - minrain_1d
      - maxrain_1d
      - windforce_1d
      - windforce_2d
      - windspeed_1d
      - windspeed_2d
########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: