homeassistant:
  customize: {}

# weather:
#   - platform: buienradar
#     name: 'Home'
#     # Force 'Meetstation Volkel' to be used:
#     forecast: true

# camera:
#   - platform: buienradar

command_line:
  - sensor:
      name: "Precipitation Forecast"
      unique_id: "yaml_command_line_buienradar_api_precip_forecast"
      icon: mdi:weather-rainy
      command: >
        curl -s 'https://gadgets.buienradar.nl/data/raintext/?lat={{ state_attr('zone.home', 'latitude')|round(2) }}&lon={{ state_attr('zone.home', 'longitude')|round(2) }}' | 
        awk -F'|' -v "date=$(date +'%Y-%m-%d')" -v "hour=$(date +'%H')" '
        BEGIN {first = 1; print "{\"precipitation_raw\": ["} 
        {
          if (!first) printf ", "; 
          first = 0; 
          split($2, t, ":"); 
          if (t[1] < hour && hour >= 22) date=strftime("%Y-%m-%d", systime() + 86400); 
          ts = mktime(date " " t[1] " " t[2] " 00"); 
          printf "{\"time\":\"%s\",\"timestamp\":%d,\"precipitation\":%.1f,\"datetime\":\"%sT%s:00\"}", $2, ts, 10^(($1-109)/32), date, $2
        } 
        END {print "]}"}'
      scan_interval: 60  # Updates every minute; adjust as needed.
      value_template: "{{ value_json['precipitation_raw'][0]['precipitation'] }}"
      unit_of_measurement: "mm/h"
      device_class: precipitation_intensity
      json_attributes:
        - precipitation_raw

#################
#    SENSORS    #
#################
sensor:
  # - platform: buienradar
  #   timeframe: 120
  #   monitored_conditions:
  #     #current conditions:
  #     - condition
  #     - symbol
  #     - humidity
  #     - temperature
  #     - windspeed
  #     - winddirection
  #     - pressure
  #     - precipitation
  #     - irradiance

  #     #conditions for forecasted data:
  #     - symbol_1d
  #     - symbol_2d
  #     - symbol_3d
  #     - symbol_4d
  #     - symbol_5d
  #     - temperature_1d
  #     - temperature_2d
  #     - temperature_3d
  #     - temperature_4d
  #     - temperature_5d
  #     - mintemp_1d
  #     - rainchance_1d
  #     - rainchance_2d
  #     - sunchance_1d
  #     - sunchance_2d
  #     - rain_1d
  #     - rain_2d
  #     - minrain_1d
  #     - maxrain_1d
  #     - windforce_1d
  #     - windforce_2d
  #     - windspeed_1d
  #     - windspeed_2d

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
