esphome:
  name: ambilightleft
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ambilightleft Fallback Hotspot"
    password: !secret esphome_fallback_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

e131:
  method: unicast

light:
  - platform: neopixelbus
    type: GRB
    #color_correct: [80%, 80%, 80%]
    variant: WS2812
    method: ESP8266_DMA
    pin: GPIO3 #RX
    num_leds: 35
    name: "Ambilight left"
    gamma_correct: 1.5
    effects:
      - addressable_rainbow:
          width: 35
      - e131:
          universe: 1
          channels: RGB
