esphome:
  name: ambilightright
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.30.121
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ambilightright Fallback Hotspot"
    password: !secret esphome_fallback_pass

#problem can be fixed/introduced by adding/removing in V2023.6.0:
external_components:
  - source: github://esphome/esphome@2023.5.5
    components: e131

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

e131:
  method: unicast

light:
  - platform: neopixelbus
    type: GRB
    #color_correct: [80%, 80%, 80%]
    variant: WS2812
    method: ESP8266_DMA
    pin: GPIO3 #RX
    num_leds: 35
    name: "Ambilight right"
    gamma_correct: 1.2
    effects:
      - addressable_rainbow:
          width: 35
      - e131:
          universe: 1
          channels: RGB
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
