substitutions:
  device_friendly_name: "AQM Guest Room"
  device_name: "AQM Guest Room"
  location: "Guest Room"
  espname: "aqm-guest-room"
  pressure_multiplier: "1.018"
  pressure_offset: "-17.91"
  humidity_multiplier: "1.06"
  humidity_offset: "-4.83"
  eco2_baseline: "0xA31C"
  tvoc_baseline: "0x905E"

packages:
  aqm: !include templates/AQM_new.yaml
  climate: !include templates/aqm_components/climate.yaml
  tvoc: !include templates/aqm_components/tvoc.yaml
  co2: !include templates/aqm_components/co2.yaml
  particulates: !include templates/aqm_components/particulates.yaml
