substitutions:
  device_friendly_name: "AQM Living Room"
  device_name: "AQM Living Room"
  location: "Living Room"
  espname: "aqm-living-room"
  temperature_offset: "-0.5"
  pressure_multiplier: "1.005"
  pressure_offset: "-5.34"
  humidity_multiplier: "0.83"
  humidity_offset: "44.62"
  eco2_baseline: "0xA31C"
  tvoc_baseline: "0x905E"

packages:
  aqm: !include templates/AQM_new.yaml
  climate: !include templates/aqm_components/climate.yaml
  tvoc: !include templates/aqm_components/tvoc.yaml
  co2: !include templates/aqm_components/co2.yaml
  particulates: !include templates/aqm_components/particulates.yaml
  display: !include templates/aqm_components/display.yaml
  leds: !include templates/aqm_components/leds.yaml
  fan: !include
    file: templates/aqm_components/fan.yaml
    vars:
      initial_fan_speed: "30"

wifi:
  use_address: 10.0.30.101
