esphome:
  name: bed_scale
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "BlokmeisterWIFI"
  password: "ithurtswhenIP"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed Scale Fallback Hotspot"
    password: "s6DLTb8v6NYc"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


sensor:
  - platform: hx711
    name: "HX711 raw value"
    id: HX711_raw_value
    dout_pin: D1
    clk_pin: D2
    update_interval: 0.1s
    filters:
      - sliding_window_moving_average:
          window_size: 50
          send_every: 50 # 10 second updates @ 1 second scan interval.
          send_first_at: 50
    unit_of_measurement: muV
    # filters:
    #   - sliding_window_moving_average:
    #       window_size: 50
    #       send_every: 50 # 10 second updates @ 1 second scan interval.
    #       send_first_at: 50
    #   - calibrate_linear:
    #       - -1222100-> 0
    #       - -1515243 -> 68.2
    # unit_of_measurement: kg
    # accuracy_decimals: 2
    
  - platform: template
    name: "HX711 Value"
    lambda: |-
      return id(HX711_raw_value).state;
    filters:
      - calibrate_linear:
          - -1171748 -> 0
          - -1414105 -> 66.8
    update_interval: 5s
    unit_of_measurement: kg
    accuracy_decimals: 2