esphome:
  name: co2_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # manual_ip:
  #   static_ip: 192.168.1.135
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CO2 Sensor Fallback Hotspot"
    password: !secret esphome_fallback_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: D2
  tx_pin: D1
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: mhz19_sensor
    co2:
      name: "MH-Z19 CO2 Value"
      accuracy_decimals: 0
      id: mhz19_CO2_value
      unit_of_measurement: ppm
      internal: true
      # filters:
      #   - median:
      #       window_size: 3
      #       send_every: 1
      #       send_first_at: 1
      #   - sliding_window_moving_average:
      #       window_size: 12
      #       send_every: 12
      #       send_first_at: 6
    temperature:
      name: "MH-Z19 Temperature"
      internal: true
    update_interval: 5s
    automatic_baseline_calibration: false


  - platform: template
    name: "CO2 concentration filtered"
    lambda: |-
      if (id(mhz19_CO2_value).state > 1.0) {
        return id(mhz19_CO2_value).state;
      } else {
        return {};
      }
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 1
    accuracy_decimals: 0
    unit_of_measurement: ppm

switch:
  - platform: template
    name: "Calibrate MH-Z19"
    optimistic: true
    on_turn_on:
      - mhz19.abc_enable: mhz19_sensor
      - mhz19.calibrate_zero: mhz19_sensor
    on_turn_off:
      mhz19.abc_disable: mhz19_sensor
