substitutions:
  device_name: "Filament Lamp"
  max_power: "220.0"
  max_temp: "70.0"

esphome:
  name: filament-lamp

esp32:
  board: esp32doit-devkit-v1

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml

switch:
  - platform: gpio
    pin: 25
    name: "${device_name} Relay"
    id: relay
# Sensors with general information.
sensor:
  # Rotary encoder
  - platform: rotary_encoder
    name: ${device_name} Dimmer Knob
    id: encoder
    pin_a: 26
    pin_b: 27
    publish_initial_value: true
    resolution: 1
    min_value: 0
    max_value: 100
    on_value:
      then:
        - light.turn_on:
            id: filamentlamp
            transition_length: 1s
            brightness: !lambda |-
              return id(encoder).state / 100;

output:
  - platform: ac_dimmer
    id: filamentlamp_dimmer
    gate_pin: 32
    zero_cross_pin:
      number: 33
      mode:
        input: true

light:
  - platform: monochromatic
    name: ${device_name}
    icon: mdi:globe-light-outline
    output: filamentlamp_dimmer
    id: filamentlamp
    default_transition_length: 10s
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - switch.turn_on: relay
    on_turn_off:
      - switch.turn_off: relay

