substitutions:
  device_name: "Filament Lamp"
  max_power: "220.0"
  max_temp: "70.0"

esphome:
  name: filament-lamp

esp32:
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret esphome_fallback_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

# Enable Web server (optional).
web_server:
  port: 80

# Text sensors with general information.
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP Address"
    ssid:
      name: "${device_name} SSID"
    bssid:
      name: "${device_name} BSSID"
  - platform: version
    name: "${device_name} ESPHome Version"

switch:
  - platform: restart
    name: "${device_name} Restart"
  - platform: gpio
    pin: 25
    name: "${device_name} Relay"
    id: relay
# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${device_name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    update_interval: 60s

  # Rotary encoder
  - platform: rotary_encoder
    name: ${device_name} Dimmer Knob
    id: encoder
    pin_a: 26
    pin_b: 27
    publish_initial_value: true
    resolution: 1
    min_value: 0
    max_value: 100
    on_value:
      then:
        - light.turn_on:
            id: filamentlamp
            transition_length: 1s
            brightness: !lambda |-
              return id(encoder).state / 100;

output:
  - platform: ac_dimmer
    id: filamentlamp_dimmer
    gate_pin: 32
    zero_cross_pin:
      number: 33
      mode:
        input: true

light:
  - platform: monochromatic
    name: ${device_name}
    icon: mdi:globe-light-outline
    output: filamentlamp_dimmer
    id: filamentlamp
    default_transition_length: 10s
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - switch.turn_on: relay
    on_turn_off:
      - switch.turn_off: relay

