esphome:
  name: livingroom_ledstrip
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Ledstrip"
    password: !secret esphome_fallback_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

e131:
  method: unicast

status_led:
  pin: D0

light:
  - platform: fastled_clockless
    chipset: WS2812
    max_refresh_rate: 50ms
    pin: D1
    num_leds: 300
    rgb_order: GRB
    gamma_correct: 1
    name: "Livingroom A-RGB LEDstrip"
    effects:
      - e131:
          universe: 1
          channels: RGB
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 200
      - addressable_lambda:
          name: "My Custom Effect"
          update_interval: 20ms
          lambda: |-
            for (int i = 0; i < it.size()-1; i++) {
              if (i % 30 > 19) {
                it[i] = ESPColor(25*(i % 10), 0, 0);
              }
              else if (i % 30 > 9) {
                it[i] = ESPColor(0, 25*(i % 10), 0);
              }
              else {
                it[i] = ESPColor(0, 0, 25*(i % 10));
              }
            }
            
            // for (int i = 0; i < it.size()-1; i++) {
            //   if (brightleds[i]) {
            //     // it[i] = ESPColor(255, 235, 235);
            //     it[i] = current_color;
            //   }
            // }
