substitutions:
  device_name: "Plug Air Conditioner"
  plug_type: "Gosund SP111"
  espname: "plug-air-conditioner"

  max_power: "2200.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO04'

  # Calibrated on 2026-06-24 using power meter OCR script
  current_res: "0.002710"
  voltage_div: "688.93"
  current_multiplier: "1.882"

  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.152
