substitutions:
  device_name: "Plug NAS"
  plug_type: "Gosund SP111"
  espname: "plug-nas"

  max_power: "2200.0" # watt
  max_temp: "70.0" # °C

  current_res: "0.00263"
  voltage_div: "651.141" #20240825T06:41 changed from "650.9"
  current_multiplier: "1.78"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

# wifi:
#   use_address: 10.0.30.146
