substitutions:
  device_name: "Plug Electric Car"
  plug_type: "Blitzwolf SHP10"
  espname: "plug-electric-car"

  max_power: "3600.0" # watt
  max_temp: "70.0" # °C

  current_res: "0.00263"
  voltage_div: "1.00"
  current_multiplier: "1.00"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

<<: !include templates/blitzwolf_shp10_plug.yaml
