substitutions:
  device_name: "Plug Study Desk"
  plug_type: "Blitzwolf SHP6"
  espname: "plug-study-desk"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO14'

# Tasmota responses
# 17:02:12.531 CMD: VoltageCal
# 17:02:12.538 MQT: blitzwolf_computer/stat/RESULT = {"VoltageCal":1906}
# 17:02:15.570 CMD: CurrentCal
# 17:02:15.576 MQT: blitzwolf_computer/stat/RESULT = {"CurrentCal":2700}
# 17:02:17.868 CMD: PowerCal
# 17:02:17.875 MQT: blitzwolf_computer/stat/RESULT = {"PowerCal":10531}

  # Calibrated 20240825T09:48 using heat gun 796W load (half power)
  current_res: "0.0027532"
  voltage_div: "902.060" #20240825T06:41 changed from "940"
  current_multiplier: "1.829360237065966"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

# wifi:
#   use_address: 10.0.30.131
