substitutions:
  device_name: "Plug 10Gb Switch"
  plug_type: "Blitzwolf SHP6"
  espname: "plug-10gb-switch"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO14'

# Tasmota responses
# 23:06:44.533 CMD: VoltageCal
# 23:06:44.540 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"VoltageCal":1959}
# 23:06:46.510 CMD: CurrentCal
# 23:06:46.518 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"CurrentCal":2781}
# 23:06:48.282 CMD: PowerCal
# 23:06:48.289 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"PowerCal":10366}

  current_res: "0.00256"
  voltage_div: "926.056" #20240825T06:44 changed from "658.2"
  current_multiplier: "1.737"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml
