substitutions:
  device_name: "Plug Computer"
  plug_type: "Blitzwolf SHP6"
  espname: "plug-computer"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO14'

# Tasmota responses 2024-12-21
# 08:15:24.865 CMD: VoltageCal
# 08:15:24.873 MQT: blitzwolf_poe_switch/stat/RESULT = {"VoltageCal":1872}
# 08:15:27.647 CMD: CurrentCal
# 08:15:27.654 MQT: blitzwolf_poe_switch/stat/RESULT = {"CurrentCal":2736}
# 08:15:30.405 CMD: PowerCal
# 08:15:30.412 MQT: blitzwolf_poe_switch/stat/RESULT = {"PowerCal":10362}

  # Calibrated 20241221T13:59 using heat gun 780 load (half power)
  current_res: "0.002709"
  voltage_div: "883.4"
  current_multiplier: "1.8235"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.138
