substitutions:
  device_name: "Plug Dishwasher"
  plug_type: "Blitzwolf SHP10"
  espname: "plug-dishwasher"

  max_power: "3600.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO14'

# Tasmota responses

  current_res: "0.00256"
  voltage_div: "1.00997" #20240825T06:45 changed from "1.008"
  current_multiplier: "0.993"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/blitzwolf_shp10_plug.yaml

wifi:
  use_address: 10.0.30.140
