substitutions:
  device_name: "Plug TV"
  plug_type: "Gosund SP111"
  espname: "plug-tv"

  max_power: "2200.0" # watt
  max_temp: "70.0" # °C

# Tasmota responses
# 02:22:42.154 CMD: VoltageCal
# 02:22:42.159 RSL: RESULT = {"VoltageCal":1386}
# 02:22:53.517 CMD: CurrentCal
# 02:22:53.522 RSL: RESULT = {"CurrentCal":2940}
# 02:22:55.912 CMD: PowerCal
# 02:22:55.918 RSL: RESULT = {"PowerCal":8157}

  # Calibrated 20240825T11:00 using heat gun 805W load (half power)
  current_res: "0.002612"
  voltage_div: "658.2"
  current_multiplier: "1.7758"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml
