substitutions:
  device_name: "Plug Electric Bike"
  plug_type: "Blitzwolf SP111"
  espname: "plug-electric-bike"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

  # Calibrated on 20260415 with hair dryer at ~600W load
  current_res: "0.00245"
  voltage_div: "673.972"
  current_multiplier: "1.822"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.151
