substitutions:
  device_name: "Plug Router"
  plug_type: "Gosund SP1111"
  espname: "plug-router"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

# Tasmota responses
# 00:05:43.941 RSL: RESULT = {"VoltageCal":1340}
# 00:05:46.275 CMD: CurrentCal
# 00:05:46.280 RSL: RESULT = {"CurrentCal":2828}
# 00:05:47.811 CMD: PowerCal
# 00:05:47.816 RSL: RESULT = {"PowerCal":7848}

  current_res: "0.002624"
  voltage_div: "638.6"
  current_multiplier: "1.743"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml
