substitutions:
  device_name: "Plug Study Workbench"
  plug_type: "Gosund SP111"
  espname: "plug-study-workbench"

  max_power: "3000.0" # watt
  max_temp: "70.0" # °C

# Tasmota responses
# 00:05:42.505 CMD: VoltageCal
# 00:05:42.510 RSL: RESULT = {"VoltageCal":1340}
# 00:05:46.770 CMD: CurrentCal
# 00:05:46.775 RSL: RESULT = {"CurrentCal":2883}
# 00:05:50.256 CMD: PowerCal
# 00:05:50.261 RSL: RESULT = {"PowerCal":7814}

  current_res: "0.00260"
  voltage_div: "638.3"
  current_multiplier: "1.731"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml
