substitutions:
  device_name: "Plug PoE Switch"
  plug_type: "Gosund SP111"
  espname: "plug-poe-switch"

  max_power: "3000.0" # watt
  max_temp: "70.0" # °C

# Tasmota responses
# 00:01:06.922 CMD: VoltageCal
# 00:01:06.927 RSL: RESULT = {"VoltageCal":1372}
# 00:01:08.510 CMD: CurrentCal
# 00:01:08.515 RSL: RESULT = {"CurrentCal":2951}
# 00:01:09.858 CMD: PowerCal
# 00:01:09.862 RSL: RESULT = {"PowerCal":8018}

  current_res: "0.00258"
  voltage_div: "651.992" #20240825T06:41 changed from "652.4"
  current_multiplier: "1.756"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.132
