substitutions:
  device_name: "Plug Watercooker"
  plug_type: "Blitzwolf SHP6"
  espname: "plug-watercooker"

  max_power: "3000.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO14'

# Tasmota responses

  current_res: "0.00290"
  voltage_div: "940"
  current_multiplier: "1.70"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml
