substitutions:
  device_name: "Plug Epaper AP"
  plug_type: "Blitzwolf SHP6"
  espname: "plug-epaper-ap"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO14'

# Tasmota responses
# 20:00:43.513 CMD: VoltageCal
# 20:00:43.520 MQT: stat/blitzwolf_NUC/RESULT = {"VoltageCal":1950}
# 20:00:45.125 CMD: CurrentCal
# 20:00:45.132 MQT: stat/blitzwolf_NUC/RESULT = {"CurrentCal":3500}
# 20:00:46.464 CMD: PowerCal
# 20:00:46.471 MQT: stat/blitzwolf_NUC/RESULT = {"PowerCal":12530}

  # Calibrated 20240914T20:16 using heat gun 780 load (half power)
  current_res: "0.00265"
  voltage_div: "910.226" #20240825T06:44 changed from "658.2"
  current_multiplier: "1.854"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

# wifi:
#   use_address: 10.0.30.150
