substitutions:
  device_name: "Plug NUC"
  plug_type: "Gosund SP111"
  espname: "plug-nuc"

  max_power: "3000.0" # watt
  max_temp: "70.0" # °C

# Tasmota responses
# 00:03:06.345 CMD: VoltageCal
# 00:03:06.350 RSL: RESULT = {"VoltageCal":1349}
# 00:03:08.948 CMD: CurrentCal
# 00:03:08.953 RSL: RESULT = {"CurrentCal":2823}
# 00:03:10.426 CMD: PowerCal
# 00:03:10.431 RSL: RESULT = {"PowerCal":8063}

  current_res: "0.002584"
  voltage_div: "638.9"
  current_multiplier: "1.731"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml
