substitutions:
  device_name: "Plug Heat Pump"
  plug_type: "Gosund SP111"
  espname: "plug-heat-pump"

  max_power: "2200.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO04'

  # Calibrated on 20260630 using air conditioner and Power Meter OCR software
  current_res: "0.002461"
  voltage_div: "688.2"
  current_multiplier: "1.856"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

  # Settings for calibration mode:
  # plug_power_component_file: "/config/esphome/templates/plug_functions/hlw8012_default.yaml"
  # plug_power_component_file: "/config/esphome/templates/plug_functions/hlw8012_calibration.yaml"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.153
