substitutions:
  device_name: "Plug 3D Printer"
  plug_type: "Gosund SP111"
  espname: "plug-3d-printer"

  max_power: "2200.0" # watt
  max_temp: "70.0" # °C

  hlw8012_sf1_pin: 'GPIO04'

# Tasmota responses
# 00:00:21.868 CMD: VoltageCal
# 00:00:21.873 RSL: RESULT = {"VoltageCal":1326}
# 00:00:28.087 CMD: CurrentCal
# 00:00:28.092 RSL: RESULT = {"CurrentCal":2818}
# 00:00:30.178 CMD: PowerCal
# 00:00:30.183 RSL: RESULT = {"PowerCal":7790}

  current_res: "0.00259"
  voltage_div: "630.100" #20240825T06:38 changed from "631.9"
  current_multiplier: "1.70"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.147
