substitutions:
  device_name: "Plug Electric Car"
  plug_type: "Blitzwolf SHP10"
  espname: "plug-electric-car"

  max_power: "3600.0" # watt
  max_temp: "70.0" # °C

# Tasmota responses:
# 23:02:22.255 CMD: VoltageSet
# 23:02:22.261 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"VoltageSetCal":1959}
# 23:02:24.971 CMD: CurrentSet
# 23:02:24.978 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"CurrentSetCal":2781}
# 23:02:26.994 CMD: PowerSet
# 23:02:27.000 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"PowerSetCal":10366}
# 23:03:09.647 CMD: VoltageCal
# 23:03:09.654 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"VoltageCal":1959}
# 23:03:11.185 CMD: CurrentCal
# 23:03:11.192 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"CurrentCal":2781}
# 23:03:12.768 CMD: PowerCal
# 23:03:12.776 MQT: blitzwolf_10gbe_switch/stat/RESULT = {"PowerCal":10366}


  current_res: "0.00250"
  voltage_div: "1.00415" #20240825T06:46 changed from "1.008"
  current_multiplier: "0.9814"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"

packages:
  plug_base: !include templates/blitzwolf_shp10_plug.yaml

wifi:
  use_address: 10.0.30.137
