substitutions:
  device_name: "Plug Electric Bike"
  plug_type: "Blitzwolf SP111"
  espname: "plug-electric-bike"

  max_power: "2300.0" # watt
  max_temp: "70.0" # °C

  # Calibrated on 20260415 with hair dryer at ~600W load
  # Calibrated 20260707T13:02 using rpi OCR + hair dryer at ~670W load. Voltage at 0 load
  current_res: "0.002456"
  voltage_div: "675.5"
  current_multiplier: "1.8247"
  #ntc_reference_resistance: "10kOhm"
  #ntc_reference_temperature: "298.15K"
  # plug_power_component_file: "/config/esphome/templates/plug_functions/hlw8012_calibration.yaml"

packages:
  plug_base: !include templates/gosund_sp111_plug.yaml

wifi:
  use_address: 10.0.30.151
