substitutions:
  shelly_id: "Hallway 1st Floor"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-hallway-1st-floor"

packages:
  shelly: !include templates/shelly_1.yaml

#<<: !include templates/shelly_1.yaml
