substitutions:
  shelly_id: "Living Room"
  device_name: "Shelly ${shelly_id}"
  espname: shelly-livingroom
  shelly_type: "Shelly 1 Plus"

<<: !include templates/shelly_1_plus.yaml

wifi:
  use_address: 10.0.30.174
