substitutions:
  shelly_id: "Closet"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-closet-plus1mini"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

<<: !include templates/shelly1plusmini.yaml
