substitutions:
  shelly_id: "Dinner Table D2"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-dinnertable-dimmer2"

  #STM_firmware_version: "51.7"
  shelly_dimmer_version: "Shelly Dimmer 2"
  #input_pin: GPIO14

  max_power: "220.0" # watt
  max_temp: "70.0" # °C
  max_brightness: "1000"
  min_brightness: "40"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

packages:
  shelly: !include templates/shelly_dimmer.yaml
#<<: !include templates/shelly_dimmer.yaml

wifi:
  use_address: 10.0.30.179
