substitutions:
  shelly_id: "Living Room"
  device_name: "Shelly ${shelly_id}"
  espname: shelly-livingroom
  shelly_type: "Shelly 1 Plus"

  detached_mode_restore_mode: "RESTORE_DEFAULT_ON"
  relay_restore_mode: "RESTORE_DEFAULT_ON"

packages:
  shelly: !include templates/shelly_1_plus.yaml

wifi:
  use_address: 10.0.30.174
