substitutions:
  shelly_id: "porch"
  device_name: "Shelly ${shelly_id}"
  shelly_type: "Shelly 1 Plus"
  espname: "shelly-porch"

  relay_restore_mode: "RESTORE_DEFAULT_OFF"
  detached_mode_restore_mode: "RESTORE_DEFAULT_OFF"

packages:
  shelly: !include
    file: templates/shelly_1_plus.yaml
    vars:
      relay_restore_mode: ${relay_restore_mode}
      detached_mode_restore_mode: ${detached_mode_restore_mode}
#<<: !include templates/shelly_1_plus.yaml

wifi:
  use_address: 10.0.30.173
