substitutions:
  shelly_id: "Closet 2"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-closet-plus1mini"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

  relay_restore_mode: "RESTORE_DEFAULT_OFF"
  detached_mode_restore_mode: "RESTORE_DEFAULT_OFF"

<<: !include templates/shelly_1_plus_mini.yaml

wifi:
  use_address: 10.0.30.180
