substitutions:
  shelly_id: "Guest Room"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-guestroom"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

<<: !include templates/shelly1plusmini.yaml

wifi:
  use_address: 10.0.30.176
