substitutions:
  shelly_id: "Closet"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-closet-plus1mini"
  shelly_type: "Shelly 1 Plus Mini"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

  relay_restore_mode: "RESTORE_DEFAULT_OFF"
  detached_mode_restore_mode: "RESTORE_DEFAULT_OFF"

packages:
  shelly: !include
    file: templates/shelly_1_plus_mini.yaml
    vars:
      relay_restore_mode: ${relay_restore_mode}
      detached_mode_restore_mode: ${detached_mode_restore_mode}

wifi:
  use_address: 10.0.30.180
