substitutions:
  shelly_id: "porch"
  device_name: "Shelly ${shelly_id}"
  shelly_type: "Shelly 1 Plus"
  espname: "shelly-porch"

<<: !include templates/shelly_1_plus.yaml

wifi:
  use_address: 10.0.30.173
