esphome:
  name: stardestroyerlights
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "BlokmeisterWIFI"
  password: "ithurtswhenIP"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stardestroyerlights"
    password: "a2QRgr8Kl6yO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "ithurtswhenIP"

ota:
  password: "ithurtswhenIP"

light:
  - platform: fastled_spi
    id: ssdlights
    chipset: WS2801
    data_pin: D2
    clock_pin: D1
    num_leds: 38
    rgb_order: RGB
    default_transition_length: 2s
    name: "SSDlights"
    gamma_correct: 1.5
    effects:
      - random:
      - addressable_rainbow:
  - platform: fastled_spi
    id: ssdlights_innter
    chipset: WS2801
    data_pin: D4
    clock_pin: D3
    num_leds: 20
    rgb_order: RGB
    default_transition_length: 2s
    name: "SSDlights inner"
    gamma_correct: 1.5
    effects:
      - random:
      - addressable_rainbow: