substitutions:
  device_name: "Study Air Quality Monitor"
  short_device_name: "Study Air Mon"

esphome:
  name: air-quality-monitor-1

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${short_device_name} Hotspot
    password: !secret esphome_fallback_pass

uart:
  - rx_pin: GPIO1
    baud_rate: 9600
    id: pms

  - rx_pin: GPIO18
    tx_pin: GPIO19
    baud_rate: 9600
    id: mh

i2c:
  scl: GPIO22
  sda: GPIO21
  frequency: 100kHz

sensor:
    - platform: pmsx003
      type: PMSX003
      uart_id: pms
      pm_1_0:
        name: "PM 1 Concentration"
        id: pm1
        filters:
          - sliding_window_moving_average:
              window_size: 5
              send_every: 5
          - or:
            - throttle_average: 60s
            - delta: 1.0
      pm_2_5:
        name: "PM 2.5 Concentration"
        id: pm2_5
        filters:
          - sliding_window_moving_average:
              window_size: 5
              send_every: 5
          - or:
            - throttle_average: 60s
            - delta: 1.0
      pm_10_0:
        name: "PM 10 Concentration"
        id: pm10
        filters:
          - sliding_window_moving_average:
              window_size: 5
              send_every: 5
          - or:
            - throttle_average: 60s
            - delta: 1.0

    - platform: mhz19
      co2:
        name: "CO2"
        id: co2
        filters:
          - sliding_window_moving_average:
              window_size: 5
              send_every: 1
          - or:
            - throttle_average: 60s
            - delta: 10.0
      temperature:
        name: "MH-Z19 Temperature"
      update_interval: 10s
      automatic_baseline_calibration: false
      uart_id: mh
      id: mh_sensor

    - platform: bme280
      temperature:
        name: "Temperature"
        oversampling: 1x
        id: temp
        filters:
          - offset: -1.5
      pressure:
        name: "Pressure"
        oversampling: 1x
        id: press
      humidity:
        name: "Humidity"
        oversampling: 1x
        id: hum
      address: 0x76
      update_interval: 10s

    - platform: sgp30
      eco2:
        name: "eCO2"
        accuracy_decimals: 1
        id: eco2
      tvoc:
        name: "TVOC"
        accuracy_decimals: 1
        id: tvoc
      update_interval: 1s
      address: 0x58
      # https://esphome.io/components/sensor/sgp30.html#calibrating-baseline
      baseline:
        eco2_baseline: 0x92B7
        tvoc_baseline: 0x935A
      compensation:
         temperature_source: temp
         humidity_source: hum

switch:
  - platform: gpio
    name: "PMS7003_SET"
    pin:
      number: GPIO18
      mode: output
    restore_mode: ALWAYS_ON
    id: pms_set
  - platform: template
    name: "MH-Z19 ABC"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: mh_sensor
    on_turn_off:
      mhz19.abc_disable: mh_sensor
