esphome:
  name: study_desk_ledstrip_controller
  platform: ESP32
  board: nodemcu-32s
  platformio_options:
    lib_deps: NeoPixelBus@2.6.1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Study Desk Ledstrip Controller"
    password: !secret esphome_fallback_pass


captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

e131:
  method: unicast

status_led:
  pin: GPIO2

sensor:
  # - platform: ultrasonic
  #   trigger_pin: GPIO33
  #   echo_pin: GPIO25
  #   name: "Ultrasonic Sensor"
  #   update_interval: 0.1s
  #   internal: true

light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: GPIO26
    num_leds: 129
    gamma_correct: 1
    name: "Study Desk A-RGB LEDstrip"
    effects:
      - e131:
          universe: 1
          channels: RGB
      - addressable_rainbow:
          name: Rainbow Swirl
          speed: 10
          width: 129