substitutions:
  device_name: "Test GPS"
  espname: "testgps"

esphome:
  name: '${espname}'
  comment: 'ESP32S2'
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
#   framework:
#     type: esp-idf

packages:
  wifi: !include common/wifi.yaml
  network_diagnostics: !include common/network_diagnostics.yaml
  base_config: !include common/base_config.yaml


time:
  - platform: gps
    id: gps_time

# Example configuration entry
uart:
  rx_pin: GPIO17
  baud_rate: 9600

# Declare GPS module
gps:
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"
