substitutions:
  device_name: "Ventilation Controller"


esphome:
  name: ventilation-controller
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret esphome_fallback_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${device_name} Uptime
  # Home assistant sensors
  - platform: homeassistant
    name: "Bathroom Humidity"
    entity_id: sensor.humidity_bathroom
    id: ha_humidity_bathroom
    device_class: "humidity"
  - platform: homeassistant
    name: "Bedroom CO2 Concentration"
    entity_id: sensor.mh_z19_co2_value_2
    device_class: "carbon_dioxide"
    id: ha_co2_bedroom
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: pwm_output

fan:
  - platform: speed
    output: pwm_output
    speed_count: 100
    name: "Ventilation System"
    id: ventilationsystem

switch:
  - platform: template
    name: "Max Ventilation"
    id: maxventilationswitch
    turn_on_action:
      - fan.turn_on:
          id: ventilationsystem
          speed: 100
      - delay: 600s
      - switch.turn_off: maxventilationswitch
    turn_off_action:
      - fan.turn_on:
          id: ventilationsystem
          speed: 20
