esphome:
  name: '${espname}'
  comment: 'wemos_d1_mini32'
  on_boot:
    then:
      - lambda: 'id(pm2_5).publish_state(1.0);'
      - lambda: 'id(co2).publish_state(400);'
      - light.control:
          id: led1
          brightness: 0.25
          state: on
      - light.control:
          id: led2
          brightness: 0.25
          state: on
      - light.control:
          id: led3
          brightness: 0.25
          state: on
      - delay: 1 min
      - script.execute: min_max_zero_script

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

font:
  - file: "fonts/Roboto-Medium.ttf"
    id: arial
    size: 15
  - file: "fonts/Roboto-Medium.ttf"
    id: arial30
    size: 30
  - file: "fonts/Roboto-Medium.ttf"
    id: arial10
    size: 10

uart:
  - rx_pin: GPIO1
    baud_rate: 9600
    id: pms

  - rx_pin: GPIO18
    tx_pin: GPIO19
    baud_rate: 9600
    id: mh

i2c:
  scl: GPIO22
  sda: GPIO21
  frequency: 100kHz

button:
  - platform: template
    name: "${location} Calibrate MH-Z19"
    id: software_calibrate_button
    on_press:
      then:
        - mhz19.calibrate_zero: mh_sensor

switch:
  - platform: template
    name: "${location} MH-Z19 ABC"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: mh_sensor
    on_turn_off:
      mhz19.abc_disable: mh_sensor

sensor:
  - platform: pmsx003
    type: PMSX003
    uart_id: pms
    pm_1_0:
      name: "${location} PM 1 Concentration"
      id: pm1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
        - or:
          - throttle_average: 60s
          - delta: 1.0
    pm_2_5:
      name: "${location} PM 2.5 Concentration"
      id: pm2_5
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
        - or:
          - throttle_average: 60s
          - delta: 1.0
    pm_10_0:
      name: "${location} PM 10 Concentration"
      id: pm10
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
        - or:
          - throttle_average: 60s
          - delta: 1.0

  - platform: mhz19
    co2:
      name: "${location} CO2"
      id: co2
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - or:
          - throttle_average: 60s
          - delta: 10.0
    temperature:
      name: "${location} MH-Z19 Temperature"
      filters:
        - or:
          - throttle_average: 60s
          - delta: 1
    update_interval: 10s
    automatic_baseline_calibration: false
    uart_id: mh
    id: mh_sensor

  - platform: bme280
    temperature:
      name: "${location} AQM Temperature"
      oversampling: 1x
      id: temp
      filters:
        - offset: -1.5
        - or:
          - throttle_average: 60s
          - delta: 1.0
    pressure:
      name: "${location}  AQM Pressure"
      oversampling: 1x
      id: press
      filters:
        - or:
          - throttle_average: 60s
          - delta: 10
    humidity:
      name: "${location} AQM Humidity"
      oversampling: 1x
      id: hum
      filters:
        - or:
          - throttle_average: 60s
          - delta: 5
    address: 0x76
    update_interval: 10s
