substitutions:
  voltage_multiplier: "${voltage_div}"

esphome:
  name: ${espname}
  friendly_name: ${device_name}
  comment: ${plug_type}

esp8266:
  board: esp01_1m
  early_pin_init: false # Prevent relay toggle during boot
  framework:
    version: recommended

# Enable logging
logger:
  baud_rate: 0

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
  power: !include /config/esphome/common/power.yaml
  plug: !include
    file: /config/esphome/templates/plug_functions/plug_default_components.yaml
    vars:
      status_led_gpio_pin: "GPIO04"
      relay_gpio_pin: "GPIO05"

uart:
  id: uart_bus
  tx_pin: GPIO01  # Transmits data to BL0940
  rx_pin: GPIO03  # Receives data from BL0940
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0940
    uart_id: uart_bus
    update_interval: 1s
    <<: !include plug_functions/plug_default_power_sensor_settings.yaml

    internal_temperature:
      name: "${device_name} Internal temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      id: internal_temp
      icon: mdi:thermometer
      filters:
        - throttle_average: 5s
        - or:
          - throttle_average: 60s
          - delta: 1.0
