defaults:
  hlw_8012_voltage_div: "${voltage_div}"
  voltage_multiplier: "1"

substitutions:
  hlw8012_sf1_pin: 'GPIO04' #Default for SP111. GPIO14 is default for SHP6

esphome:
  name: ${espname}
  friendly_name: ${device_name}
  comment: ${plug_type}
# This allows the device to restore the last saved relay state, either "ON" or "OFF" for the switch later in this config
#  esp8266_restore_from_flash: true

esp8266:
  board: esp8285
  early_pin_init: false # Prevent relay toggle during boot
  framework:
    version: recommended

# preferences:
#   flash_write_interval: 5min  # set to 5min to prevent wearing out the onboard flash module too quickly

# Enable logging
logger:
  baud_rate: 0

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
  power: !include /config/esphome/common/power.yaml
  plug: !include
    file: /config/esphome/templates/plug_functions/plug_default_components.yaml
    vars:
      status_led_gpio_pin: "GPIO02"
      relay_gpio_pin: "GPIO15"

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: ${hlw8012_sf1_pin}
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${hlw_8012_voltage_div}
    update_interval: 0.5s
    <<: !include plug_functions/plug_default_power_sensor_settings.yaml
