#See config here: https://devices.esphome.io/devices/Shelly-Plus-1-Mini
esphome:
  name: "${espname}"
  comment: 'Shelly 1 Plus Mini'
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    #type: esp-idf

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
  inputs: !include
    file: /config/esphome/templates/shelly_functions/shelly_inputs.yaml
    vars:
      GPIO_pin: GPIO10
  relay: !include
    file: /config/esphome/templates/shelly_functions/shelly_relay.yaml
    vars:
      GPIO_pin: GPIO7
      detached_mode_restore_mode: ${detached_mode_restore_mode}
      relay_restore_mode: ${relay_restore_mode}
  ntc_sensor: !include
    file: /config/esphome/templates/shelly_functions/shelly_ntc_sensors.yaml
    vars:
      #ntc_b_constant: "3350"
      #ntc_reference_temperature: "298.15K"
      ntc_reference_resistance: "10kOhm"
      resistor_value: "10kOhm"
      adc_attenuation: "12db"
      adc_pin: "GPIO3"

status_led:
  pin:
    number: GPIO0
    inverted: true

binary_sensor:
  # Button on device
  - platform: gpio
    name: "${device_name} Button"
    internal: true
    pin:
      number: 1
      inverted: yes
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 5ms
