# See config here: https://devices.esphome.io/devices/Shelly-Plus-1
substitutions:
  relay_restore_mode: "ALWAYS_ON"
  detached_mode_restore_mode: "RESTORE_DEFAULT_ON"

esphome:
  name: "${espname}"
  comment: 'Shelly 1 Plus'
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    # version: latest
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "20"
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
  inputs: !include
    file: /config/esphome/templates/shelly_functions/shelly_inputs.yaml
    vars:
      GPIO_pin: GPIO04
  relay: !include
    file: /config/esphome/templates/shelly_functions/shelly_relay.yaml
    vars:
      GPIO_pin: GPIO26
      detached_mode_restore_mode: ${detached_mode_restore_mode}
      relay_restore_mode: ${relay_restore_mode}
  ntc_sensor: !include
    file: /config/esphome/templates/shelly_functions/shelly_ntc_sensors.yaml
    vars:
      #ntc_b_constant: "3350"
      #ntc_reference_temperature: "298.15K"
      ntc_reference_resistance: "10kOhm"
      resistor_value: "10kOhm"
      adc_attenuation: "12db"
      adc_pin: "GPIO32"

status_led:
  pin:
    number: GPIO0
    inverted: true

binary_sensor:
  # Button on device
  - platform: gpio
    name: "${device_name} Button"
    internal: true
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 5ms
