esphome:
  name: "${espname}"
  comment: 'Shelly 1'

esp8266:
  board: esp01_1m
  framework:
    version: recommended

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
  inputs: !include
    file: /config/esphome/templates/shelly_functions/shelly_inputs.yaml
  relay: !include
    file: /config/esphome/templates/shelly_functions/shelly_relay.yaml
