substitutions:
  min_brightness: "0"
  max_brightness: "1000"
  gamma_correct: "2"
  warmup_brightness: "40"

esphome:
  name: "${espname}"
  comment: "${shelly_dimmer_version}"
  on_boot:
    priority: 100
    then:
      - binary_sensor.template.publish:
          id: switch_clicker
          state: OFF

esp8266:
  board: esp01_1m
  early_pin_init: false # Prevent relay toggle during boot
  framework:
    version: recommended

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
  dimmer: !include
    file: /config/esphome/templates/shelly_functions/shelly_dimmer_light.yaml
    vars:
      min_brightness: ${min_brightness}
      max_brightness: ${max_brightness}
      gamma_correct: ${gamma_correct}
      warmup_brightness: ${warmup_brightness}
  inputs: !include
    file: /config/esphome/templates/shelly_functions/shelly_dimmer_inputs.yaml
    vars:
      input_GPIO_pin: GPIO14
  ntc_sensor: !include
    file: /config/esphome/templates/shelly_functions/shelly_dimmer_ntc_sensors.yaml
    vars:
      #ntc_b_constant: "3350"
      #ntc_reference_temperature: "298.15K"
      ntc_reference_resistance: "10kOhm"
      resistor_value: "32kOhm"
      adc_pin: "A0"
  power: !include /config/esphome/common/power.yaml

logger:
  baud_rate: 0
