esphome:
  name: "${espname}"
  comment: 'Shelly 1 Plus'
  platformio_options:
    board_build.f_cpu: 160000000L
  on_boot:
    priority: 100
    then:
      - binary_sensor.template.publish:
          id: switch_clicker
          state: OFF

esp32:
  board: esp32doit-devkit-v1

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml
