#See config here: https://devices.esphome.io/devices/Shelly-Plus-1-Mini

esphome:
  name: "${espname}"
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 100
    then:
      - binary_sensor.template.publish:
          id: switch_clicker
          state: OFF
  comment: "Shelly Plus 1 Mini"

esp32:
  board: esp32-c3-devkitm-1
  #framework:
    #type: esp-idf
    #version: latest
    # sdkconfig_options:
    #   CONFIG_FREERTOS_UNICORE: y
    #   CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
    #   CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
    #   CONFIG_ESP_TASK_WDT_TIMEOUT_S: "20"
    #   CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n
    #   CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

packages:
  wifi: !include /config/esphome/common/wifi.yaml
  network_diagnostics: !include /config/esphome/common/network_diagnostics.yaml
  base_config: !include /config/esphome/common/base_config.yaml

# Sensors with general information.
sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${device_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: ${ntc_b_constant}
      reference_resistance: ${ntc_reference_resistance}
      reference_temperature: ${ntc_reference_temperature}
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 11db

status_led:
  pin:
    number: GPIO0
    inverted: true

# Shelly 1 detached switch config with fallback in case of wifi or api fail
output:
  - platform: gpio
    pin: GPIO7
    id: shelly_relay

light:
  - platform: binary
    name: ${shelly_id}
    output: shelly_relay
    id: shelly_light
    restore_mode: RESTORE_DEFAULT_ON


binary_sensor:
  - platform: gpio
    name: ${device_name} Input
    pin:
      number: GPIO10
    # small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
        then:
          - binary_sensor.template.publish:
              id: switch_clicker
              state: ON
          - delay: 100ms
          - binary_sensor.template.publish:
              id: switch_clicker
              state: OFF
  - platform: gpios
    name: "${device_name} Button"
    pin:
      number: 1
      inverted: yes
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 5ms
  - platform: template
    name: ${device_name} Momentary Switch
    id: switch_clicker
    on_multi_click:
      # double click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                title: ${device_name} double click
                device_name: ${device_name}
                click_type: double
                click_count: "2"
      - timing:
          - ON for at most 1s
          - OFF for at least 0.4s
        then:
          # send single click event in case wifi and api are conncected
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                title: ${device_name} short click
                device_name: ${device_name}
                click_type: single
                click_count: "1"
          - light.toggle: shelly_light
