import { buildLayoutDiagnostics } from './yaml_generation_diagnostics.js';

/**
 * @param {any} payload
 * @returns {string}
 */
export function getStayAwakeEntityId(payload) {
    const value = payload.deepSleepStayAwakeEntityId;
    return (typeof value === 'string' && value.trim()) ? value.trim() : 'input_boolean.esphome_stay_awake';
}

/**
 * @param {any} profile
 * @param {any} layout
 * @param {boolean} [requiresMaterialIcons]
 * @returns {string[]}
 */
export function generateInstructionHeader(profile, layout, requiresMaterialIcons = true) {
    const lines = [];
    const diagnostics = buildLayoutDiagnostics(layout);
    lines.push("# ============================================================================");
    lines.push("# ESPHome YAML - Generated by ESPHome Designer");
    lines.push("# ============================================================================");
    lines.push(`# TARGET DEVICE: ${profile.name || "Unknown"}`);

    const feats = profile.features || {};
    const platform = profile.displayPlatform || (feats.lcd ? (profile.id === 'reterminal_e1001' ? 'reterminal_e1001' : 'LCD') : (feats.epaper ? "waveshare_epaper" : "Unknown"));

    const chip = profile.chip || "esp32-s3";
    const unsupportedChips = ["esp32-c3", "esp32-c6", "esp8266"];
    const isUnsupported = unsupportedChips.some(c => (chip || "").toLowerCase().includes(c));
    const effectivePsram = feats.psram && !isUnsupported;

    lines.push(`#         - Display Platform: ${platform}`);
    lines.push(`#         - Touchscreen: ${feats.touch ? (profile.touch?.platform || 'Yes') : 'No'}`);
    lines.push(`#         - PSRAM: ${effectivePsram ? 'Yes' : 'No'}`);

    let frameworkHint = profile.frameworkHint || "esp-idf (Recommended)";
    if (chip === 'esp8266') {
        frameworkHint = "Arduino (Default)";
    } else if (!profile.frameworkHint && effectivePsram && (profile.chip?.includes("s3") || profile.id?.includes("s3"))) {
        frameworkHint = "ESP-IDF (Required for stable PSRAM/LVGL)";
    }
    lines.push(`#         - Framework: ${frameworkHint}`);

    lines.push("# ============================================================================");
    lines.push("#");
    lines.push("# SETUP INSTRUCTIONS:");
    lines.push("#");
    let stepNumber = 1;
    if (requiresMaterialIcons) {
        lines.push(`# STEP ${stepNumber}: Copy the Material Design Icons font file`);
        lines.push("#         - From this repo: resources/fonts/materialdesignicons-webfont.ttf");
        lines.push("#         - To ESPHome: /config/esphome/fonts/materialdesignicons-webfont.ttf");
        lines.push("#");
        stepNumber += 1;
    }
    lines.push(`# STEP ${stepNumber}: Create a new device in ESPHome`);
    lines.push("#         - Click \"New Device\"");
    if (chip === 'esp8266') {
        lines.push("#         - Select: ESP8266");
        lines.push("#         - Framework: Arduino (Default)");
    } else if (chip === 'esp32') {
        lines.push("#         - Select: ESP32");
        lines.push(`#         - Framework: ${frameworkHint}`);
    } else if (chip.includes('p4')) {
        lines.push("#         - Select: ESP32-P4");
        lines.push("#         - Framework: ESP-IDF (Required)");
    } else if (chip.includes('c3')) {
        lines.push("#         - Select: ESP32-C3");
        lines.push("#         - Framework: ESP-IDF (Recommended) or Arduino");
    } else if (chip.includes('c6')) {
        lines.push("#         - Select: ESP32-C6");
        lines.push("#         - Framework: ESP-IDF (Recommended)");
    } else {
        lines.push("#         - Select: ESP32-S3 (or appropriate for your board)");
        lines.push("#         - Framework: ESP-IDF (Essential for S3 stability)");
    }
    lines.push("#");
    stepNumber += 1;
    lines.push(`# STEP ${stepNumber}: PASTE this snippet into your device YAML`);
    lines.push("#         - Paste this snippet at the end of your configuration.");
    const sysLabel = chip === 'esp8266' ? 'esp8266' : 'esp32';
    lines.push(`#         - System sections (esphome, ${sysLabel}) are auto-commented`);
    lines.push("#           to avoid conflicts with your existing base setup.");
    lines.push("#");
    lines.push("# CAPTIVE PORTAL:");
    lines.push("#         - If WiFi connection fails, the device will create a hotspot.");
    lines.push("#         - Search for its name in your WiFi settings.");
    lines.push("#         - Connect and go to http://192.168.4.1 to configure WiFi.");
    lines.push("#");
    if (chip.includes('s3')) {
        if (usesUsbPins(profile?.pins)) {
            lines.push("# WARNING: GPIO19/GPIO20 are used by this device's hardware (e.g. I2C/Display).");
            lines.push("#          Do NOT enable USB_CDC logging (hardware_uart: USB_CDC), as it");
            lines.push("#          will conflict and cause hardware communication failures.");
            lines.push("#          Use UART0 (hardware_uart: UART0) or default hardware UART instead.");
            lines.push("#");
        } else {
            lines.push("# TIP: For reTerminal / S3 devices, if you cannot see logs via USB,");
            lines.push("#      add this to your base 'logger:' section:");
            lines.push("#      hardware_uart: USB_CDC");
            lines.push("#");
        }
    }
    lines.push("# ============================================================================");
    lines.push("");
    lines.push("# ====================================");
    lines.push("# Device Settings");
    lines.push("# ====================================");
    lines.push(`# Orientation: ${layout.orientation || "landscape"}`);
    lines.push(`# Dark Mode: ${layout.darkMode ? "enabled" : "disabled"}`);
    lines.push(`# Refresh Interval: ${layout.refreshInterval || 600}`);
    const isLcd = !!(profile.features && (profile.features.lcd || profile.features.oled));
    let strategy;
    if (layout.manualRefreshOnly) {
        strategy = "Manual Refresh Only";
    } else if (isLcd) {
        const lcdStrategy = layout.lcdEcoStrategy || 'backlight_off';
        /** @type {Record<string, string>} */
        const map = {
            always_on: 'Always On',
            backlight_off: 'Backlight Off Schedule',
            halt_updates: 'Halt Updates',
            deep_sleep: 'Deep Sleep',
            dim_after_timeout: 'Dim after timeout'
        };
        strategy = map[lcdStrategy] || lcdStrategy;
    } else {
        strategy = layout.deepSleepEnabled ? "Ultra Eco (Deep Sleep)" : (layout.sleepEnabled ? "Eco (Light Sleep)" : "Always On");
    }
    lines.push(`# Power Strategy: ${strategy}`);
    lines.push(`# Deep Sleep: ${layout.deepSleepEnabled ? 'enabled' : 'disabled'}`);
    lines.push(`# Deep Sleep Stay Awake Switch: ${layout.deepSleepStayAwakeSwitch ? 'enabled' : 'disabled'}`);
    lines.push(`# Deep Sleep Stay Awake Entity: ${getStayAwakeEntityId(layout)}`);
    lines.push(`# Deep Sleep Firmware Guard: ${layout.deepSleepFirmwareGuard ? 'enabled' : 'disabled'}`);
    lines.push(`# Deep Sleep Interval: ${layout.deepSleepEnabled ? `${layout.deepSleepInterval || 600}s` : 'Disabled'}`);
    lines.push(`# ${diagnostics.headerLine}`);
    lines.push(`# ${diagnostics.summaryLine}`);
    lines.push("# Boot Log Hint: Compare the runtime build signature with this header to spot OTA rollbacks.");
    lines.push("# ====================================");
    lines.push("");
    return lines;
}

/**
 * @param {any} profile
 * @param {any} layout
 * @returns {string[]}
 */
export function generateSystemSections(profile, layout) {
    const lines = [];
    const chip = profile.chip || "esp32-s3";
    const board = profile.board || (chip === 'esp8266' ? 'nodemcuv2' : (chip === 'esp32' ? 'esp32dev' : (chip.includes('c3') ? 'esp32-c3-devkitm-1' : (chip.includes('c6') ? 'esp32-c6-devkitc-1' : (chip.includes('p4') ? 'esp32-p4-evboard' : 'esp32-s3-devkitc-1')))));
    const overrides = profile.system_section_overrides || {};
    /** @param {string[]} [blockLines] */
    const pushCommentedBlock = (blockLines = []) => {
        blockLines.forEach((line) => {
            lines.push(`#${line ? ' ' + line : ''}`);
        });
    };

    const isEpaper = !!(profile.features && (profile.features.epaper || profile.features.epd));
    const isCoreInk = (profile.board === "m5stack-coreink") || (profile.name && profile.name.toLowerCase().includes("coreink"));

    lines.push("# esphome:");
    lines.push("#   name: your-device-name");
    lines.push("#   comment: 'Snippet generated by ESPHome Designer'");
    pushCommentedBlock(overrides.esphome);
    if (layout.plugin_includes && layout.plugin_includes.length > 0) {
        lines.push("#   includes:");
        layout.plugin_includes.forEach((/** @type {string} */ inc) => {
            lines.push(`#     - ${inc}`);
        });
    }
    lines.push("#   on_boot:");
    lines.push("#     priority: 300");
    lines.push("#     then:");

    if (!isCoreInk) {
        if (profile.id === 'esp32_s3_photopainter') {
            lines.push("#       - lambda: |-");
            lines.push("#           auto write_reg = [](uint8_t reg, uint8_t val) {");
            lines.push("#             uint8_t data[2] = {reg, val};");
            lines.push("#             id(bus_a)->write(0x34, data, 2);");
            lines.push("#           };");
            lines.push("#           write_reg(0x94, 0x1C); // ALDO3 3.3V");
            lines.push("#           write_reg(0x95, 0x1C); // ALDO4 3.3V");
            lines.push("#           write_reg(0x90, 0x1F); // Enable rails");
            lines.push("#           ESP_LOGI(\"power\", \"AXP2101 Configured\");");
            lines.push("#       - delay: 200ms");
            lines.push("#       - component.update: epaper_display");
        }

        if (profile.battery && profile.pins && profile.pins.batteryEnable) {
            lines.push("#       - output.turn_on: bsp_battery_enable");
        }
        if (profile.m5paper?.main_power_pin || profile.pins?.main_power_pin) {
            lines.push("#       - output.turn_on: main_power");
        }
        if (profile.m5paper?.battery_power_pin || profile.pins?.battery_power_pin) {
            lines.push("#       - output.turn_on: battery_power");
        }
        lines.push("#       - delay: 2s");
    }

    if (isCoreInk) {
        lines.push("#       # 1. HARDWARE POWER LOCK (ESP-IDF Version)");
        lines.push("#       - lambda: |-");
        lines.push("#           gpio_set_direction(GPIO_NUM_12, GPIO_MODE_OUTPUT);");
        lines.push("#           gpio_set_level(GPIO_NUM_12, 1);");
        lines.push("#           gpio_hold_en(GPIO_NUM_12);");
        lines.push("#           gpio_deep_sleep_hold_en();");
        lines.push("#");
        lines.push("#       # 2. Start the Main Logic Loop");
        lines.push("#       - script.execute: manage_run_and_sleep");
        lines.push("#");
        lines.push("#       # 3. Initial Screen Update");
        lines.push("#       - component.update: epaper_display");
    } else {
        lines.push("#       - script.execute: manage_run_and_sleep");
    }

    if (layout.autoCycleEnabled) {
        lines.push("#       - script.execute: auto_cycle_timer");
    }
    if (chip === 'esp8266') {
        lines.push("#");
        lines.push("# esp8266:");
        lines.push(`#   board: ${board || 'nodemcuv2'}`);
    } else {
        lines.push("#");
        lines.push("# esp32:");
        lines.push(`#   board: ${board}`);
        if (chip.includes("p4")) {
            lines.push("#   variant: esp32p4");
        }
        if (overrides.esp32 && overrides.esp32.length > 0) {
            pushCommentedBlock(overrides.esp32);
        } else {
            lines.push("#   framework:");
            lines.push("#     type: esp-idf");
            if (chip.includes("s3")) {
                lines.push("#     sdkconfig_options:");
                lines.push("#       CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y");
                lines.push("#       CONFIG_ESP32S3_DATA_CACHE_64KB: y");
            } else if (chip.includes("p4")) {
                lines.push("#     advanced:");
                lines.push("#       enable_idf_experimental_features: true");
            }
        }
    }
    lines.push("#");
    lines.push("# logger:");
    if (chip.includes("s3")) {
        if (usesUsbPins(profile?.pins)) {
            lines.push("#   # NOTE: GPIO19/20 in use. USB_CDC logging disabled to prevent conflicts.");
            lines.push("#   hardware_uart: UART0 # Use UART0 instead of USB_CDC");
        } else {
            lines.push("#   hardware_uart: USB_CDC # Enable for USB debugging on S3");
        }
    }
    lines.push("#   level: DEBUG");
    lines.push("#");
    lines.push("# api:");
    lines.push("# ota:");
    lines.push("# wifi:");
    lines.push("#   # ... your wifi config here");

    if (isEpaper && layout.deepSleepEnabled) {
        lines.push("");
        lines.push("deep_sleep:");
        lines.push("  id: deep_sleep_control");
        lines.push("  run_duration: 120s # Stay awake 120s on boot for OTA");
        lines.push(`  sleep_duration: ${layout.deepSleepInterval || 600}s`);
    }

    lines.push("");
    return lines;
}

/**
 * @param {any} payload
 * @returns {string[]}
 */
export function generateStayAwakeSection(payload) {
    if (!payload.deepSleepEnabled || !payload.deepSleepStayAwakeSwitch) return [];
    const stayAwakeEntityId = getStayAwakeEntityId(payload);
    if (payload.deepSleepFirmwareGuard) {
        return [
            "binary_sensor:",
            "  - platform: homeassistant",
            "    id: stay_awake_switch",
            `    entity_id: ${stayAwakeEntityId}`,
            "    on_state:",
            "      - if:",
            "          condition:",
            "            binary_sensor.is_on: stay_awake_switch",
            "          then:",
            "            - logger.log: \"Deep Sleep PREVENTED by HA switch\"",
            "            - deep_sleep.prevent: deep_sleep_control",
            "          else:",
            "            - logger.log: \"Stay-awake switch OFF\"",
            "            - if:",
            "                condition:",
            "                  lambda: 'return id(is_new_flash);'",
            "                then:",
            "                  - logger.log: \"Deep sleep still prevented by firmware guard\"",
            "                  - deep_sleep.prevent: deep_sleep_control",
            "                else:",
            "                  - logger.log: \"Deep Sleep ALLOWED\"",
            "                  - deep_sleep.allow: deep_sleep_control"
        ];
    }

    return [
        "binary_sensor:",
        "  - platform: homeassistant",
        "    id: stay_awake_switch",
        `    entity_id: ${stayAwakeEntityId}`,
        "    on_state:",
        "      - if:",
        "          condition:",
        "            binary_sensor.is_on: stay_awake_switch",
        "          then:",
        "            - logger.log: \"Deep Sleep PREVENTED by HA switch\"",
        "            - deep_sleep.prevent: deep_sleep_control",
        "          else:",
        "            - logger.log: \"Deep Sleep ALLOWED\"",
        "            - deep_sleep.allow: deep_sleep_control"
    ];
}

/**
 * @param {any} payload
 * @returns {string[]}
 */
export function generateFirmwareGuardGlobals(payload) {
    if (!payload.deepSleepEnabled || !payload.deepSleepFirmwareGuard) return [];
    return [
        "  - id: firmware_fingerprint",
        "    type: uint32_t",
        "    restore_value: true",
        "    initial_value: '0'",
        "  - id: is_new_flash",
        "    type: bool",
        "    restore_value: false",
        "    initial_value: 'false'"
    ];
}

/**
 * Checks if the configuration uses GPIO19 or GPIO20.
 * These pins map to the native USB interface on ESP32-S3 and conflict with USB_CDC logging.
 * @param {any} obj
 * @returns {boolean}
 */
function usesUsbPins(obj) {
    if (!obj) return false;
    if (typeof obj === 'string') {
        return obj === 'GPIO19' || obj === 'GPIO20';
    }
    if (typeof obj === 'object') {
        for (const key in obj) {
            if (usesUsbPins(obj[key])) {
                return true;
            }
        }
    }
    return false;
}
