homeassistant:
  customize: {}

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:
  backup_running:
    name: Backup running
    icon: mdi:backup-restore
    initial: off
##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: Restore Samba Backup sensor on startup
    trigger:
    - event: start
      platform: homeassistant
    action:
    - service: hassio.addon_stdin
      data:
        addon: 15d21743_samba_backup
        input: restore-sensor
    mode: single

  - alias: Daily Backup at 3 AM
    id: daily_backup_at_3_am
    trigger:
      platform: time
      at: '3:00:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    action:
      - service: hassio.addon_stdin
        data:
          addon: 15d21743_samba_backup
          input:
            command: trigger
            exclude: [15d21743_samba_backup, a0d7b954_esphome, a0d7b954_grafana, a0d7b954_influxdb, a0d7b954_motioneye, a0d7b954_phpmyadmin, a0d7b954_portainer, a0d7b954_sonweb, a0d7b954_ssh, a0d7b954_tautulli, a0d7b954_vscode, ccab4aaf_frigate, ccab4aaf_frigate-fa-beta, core_rpc_shutdown, core_samba]
      - wait_for_trigger:
          - platform: state
            entity_id: sensor.samba_backup
            from: 'RUNNING'
      - service: notify.mobile_app_blokmeisterp9pro
        data:
          message: "Backup {{ states('sensor.samba_backup') }}!"
          title: "Home Assistant - Backup {{ states('sensor.samba_backup') }}!"
          data:
            sticky: "true"
            group: info
            tag: backup
            # icon_url: local/icons/file-check-outline.png
            notification_icon: mdi:file-check-outline
            clickAction: "/config/backup/backups?type=manual"
            timeout: 10800
      # - service: input_boolean.turn_on
      #   entity_id: input_boolean.backup_running
      # - service: auto_backup.backup_partial
      #   data:
      #     keep_days: 7

  - alias: Weekly Backup at 3 AM
    id: weekly_backup_at_3_am
    trigger:
      platform: time
      at: '3:00:00'
    condition:
      condition: time
      weekday:
        - sun
    action:
      - service: hassio.addon_stdin
        data:
          addon: 15d21743_samba_backup
          input:
            command: trigger
            exclude: [a0d7b954_influxdb]
      - wait_for_trigger:
          - platform: state
            entity_id: sensor.samba_backup
            from: 'RUNNING'
      - service: notify.mobile_app_blokmeisterp9pro
        data:
          message: "Backup {{ states('sensor.samba_backup') }}!"
          title: "Home Assistant - Backup {{ states('sensor.samba_backup') }}!"
          data:
            sticky: "true"
            group: info
            tag: backup
            #icon_url: local/icons/file-check-outline.png
            notification_icon: mdi:file-check-outline
            clickAction: "/config/backup/backups?type=manual"
            timeout: 10800
      # - service: input_boolean.turn_on
      #   entity_id: input_boolean.backup_running
      # - service: auto_backup.backup_full
      #   data:
      #     keep_days: 31

  - alias: Report successful backup
    id: report_successful_backup
    trigger:
      - platform: state
        entity_id: sensor.samba_backup
        to: 'SUCCEEDED'
      - platform: event
        event_type: auto_backup.backup_successful
    condition:
      condition: state
      entity_id: input_boolean.backup_running
      state: 'on'
    action:
      - service: notify.mobile_app_blokmeisterp9pro
        data:
          message: "Backup completed successfully"
          title: "Home Assistant - Backup successful"
          data:
            sticky: "true"
            clickAction: "/config/backup/backups?type=manual"
            group: info
            tag: backup
            #icon_url: local/icons/file-check-outline.png
            notification_icon: mdi:file-check-outline
      - service: system_log.write
        data:
          message: 'Scheduled backup successful.'
          level: warning
      - service: input_boolean.turn_off
        entity_id: input_boolean.backup_running

  - alias: Report failed backup
    id: report_failed_backup
    trigger:
      - platform: state
        entity_id: sensor.samba_backup
        to: 'FAILED'
      - platform: event
        event_type: auto_backup.backup_failed
    condition:
      condition: state
      entity_id: input_boolean.backup_running
      state: 'on'
    action:
      - service: notify.mobile_app_blokmeisterp9pro
        data:
          message: "Backup failed!"
          title: "Home Assistant - Backup failed"
          data:
            sticky: "true"
            clickAction: "/config/backup/backups?type=manual"
            group: info
            tag: backup
            #icon_url: local/icons/file-alert-outline.png
            notification_icon: mdi:file-alert-outline
      - service: system_log.write
        data:
          message: 'Scheduled backup failed!'
          level: error
      - service: input_boolean.turn_off
        entity_id: input_boolean.backup_running

  - alias: Restore Samba Backup sensor on startup
    mode: single
    trigger:
      - event: start
        platform: homeassistant
    action:
      - service: hassio.addon_stdin
        data:
          addon: 15d21743_samba_backup
          input: restore-sensor

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
