homeassistant:
  customize:

cloud:
  google_actions:
    # filter:
    #   include_entities:
    #     - light.kitchen
    #     - light.kitchen_left
    #   include_domains:
    #     - switch
    #   exclude_entities:
    #     - switch.outside
    entity_config:
      light.bedroom_lights:
        name: Bedroom lights
        aliases:
         - bedroom lights
         - all bedroom lights
         - lights in the bedroom
        room: bedroom
      light.bedside_left:
        name: Bedside left
        aliases:
         - bedside left
         - the left bed light
         - nachtkastlamp links
        room: bedroom
      light.bedside_right:
        name: Bedside right
        aliases:
          - bedside right
          - the left bed right
          - nachtkastlamp rechts
        room: bedroom

      switch.blokmeisternas:
        name: BlokmeisterNAS
        aliases:
          - nas
          - server
          - blokmeisternas
          - nas switch
          - servcer switch
          - blokmeisternas switch
        room: livingroom


#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
