homeassistant:
  customize:

cloud:
  google_actions:
    # filter:
    #   include_entities:
    #     - light.kitchen
    #     - light.kitchen_left
    #   include_domains:
    #     - switch
    #   exclude_entities:
    #     - switch.outside
    entity_config:
      light.bedroom_lights:
        name: Bedroom lights
        aliases:
          - bedroom lights
          - all bedroom lights
          - lights in the bedroom
        room: bedroom
      light.bedside_left:
        name: Bedside left
        aliases:
          - bedside left
          - the left bed light
          - nachtkastlamp links
        room: bedroom
      light.bedside_right:
        name: Bedside right
        aliases:
          - bedside right
          - the left bed right
          - nachtkastlamp rechts
        room: bedroom

      switch.blokmeisternas:
        name: BlokmeisterNAS
        aliases:
          - nas
          - server
          - blokmeisternas
          - nas switch
          - servcer switch
          - blokmeisternas switch
        room: livingroom
      switch.blitzwolf_3dprinter:
        name: 3D printer
        aliases:
          - Blitzwolf 3D printer
          - Blitzwolf Ender 3
          - Blitzwolf 3D printer plug
          - Blitzwolf Ender 3 plug
          - Ender 3 power
          - Ender 3
          - 3D printer power
          - 3D printer
          - The printer
          - The 3D printer
          - Three Dee printer
        room: study
      switch.blitzwolf_watercooker:
        name: Watercooker
        aliases:
          - Watercooker
          - Watercooker power
          - Watercooker plug
          - Blitzwolf Watercooker
          - Blitzwolf watercooker plug
        room: kitchen
      switch.blitzwolf_coffeeplant:
        name: Coffee Plant
        aliases:
          - Coffee Plant
          - Blitzwolf Coffee Plant
          - Coffee plant lamp
          - Blitzwolf coffee plant lamp
          - Plant lamp
          - Coffee light
          - Blitzwolf coffee light
        room: livingroom
      switch.blitzwolf_washingmachine:
        name: Washing Machine
        aliases:
          - Washing Machine
          - Blitzwolf Washing Machine
          - The Washing Machine
          - Laundry
          - The Laundry

      vacuum.xiaomi_vacuum_cleaner:
        name: Consuela
        aliases:
          - Robot vacuum
          - The Consuela
          - Consuela
          - Robotstofzuiger
          - Robot vacuum cleaner
          - Vacuum cleaner
        room: livingroom
      script.vacuum_goto_kitchen:
        name: Send Vacuum to Kitchen
        aliases:
          - Send vacuum to kitchen
          - Send vacuum to the kitchen
          - Drive vacuum to kitchen
          - Drive vacuum to the kitchen
        room: livingroom
      script.bed_preheating:
        name: Bed Preheating
        aliases:
          - Bed pre heating
          - Activate bed pre heating
          - Pre heat the bed
          - Turn on bed preheating
          - Turn on bed heater
        room: bedroom
      script.movie_time:
        name: Movie Time
        aliases:
          - Movie Time
          - Time for movie
          - Turn on movie mode
          - Movie time on
        room: livingroom
      script.activate_livingroom_camera_privacy_mode:
        name: Privacy Mode
        aliases:
          - Privacy Mode
          - Turn away the camera
          - Turn the camera away
          - Move the camera away
          - Move away the camera
          - Livingroom privacy mode
          - Deactivate the camera
          - Turn off the camera
          - Turn off camera
      script.deactivate_livingroom_camera_privacy_mode:
        name: Deactivate Privacy Mode
        aliases:
          - Turn off Privacy Mode
          - Turn the camera to the living room
          - Set the camera to normal
          - Arm the camera
          - deactivate livingroom camera privacy mode
          - Deactivate privacy mode
          - Turn on the camera
          - Activate the camera
          - The camera

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
