homeassistant:
  customize: {}

cloud:
  #google_actions:
    # filter:
    #   include_entities:
    #     - light.kitchen
    #     - light.kitchen_left
    #   include_domains:
    #     - switch
    #   exclude_entities:
    #     - switch.outside
    #entity_config:
      # light.bedroom_lights:
      #   name: Bedroom lights
      #   aliases:
      #     - bedroom lights
      #     - all bedroom lights
      #     - lights in the bedroom
      #   room: bedroom

#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
