homeassistant:
  customize_glob:
    "automation.test_*":
      icon: mdi:test-tube

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    interval_seconds: 30
    consider_home: 300
    username: !secret router_user
    password: !secret router_pass
    # new_device_defaults:
    #   track_new_devices: true
    #   hide_if_away: true
  - platform: google_maps
    username: !secret google_location_user
    max_gps_accuracy: 1000
    scan_interval: 60
      
#################
#    SENSORS    #
#################
sensor:
  - platform: history_stats
    name: Sander home yesterday
    entity_id: person.sander_blok
    state: 'home'
    type: time
    end: '{{ now().replace(hour=0, minute=0, second=0) }}'
    duration:
      hours: 24
  - platform: history_stats
    name: Sander home today
    entity_id: person.sander_blok
    state: 'home'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: