homeassistant:
  customize_glob:
    "automation.test_*":
      icon: mdi:test-tube

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    interval_seconds: 30
    consider_home: 300
    username: !secret router_user
    password: !secret router_pass
    # new_device_defaults:
    #   track_new_devices: true
    #   hide_if_away: true
  - platform: google_maps
    username: !secret google_location_user
    max_gps_accuracy: 1000
    scan_interval: 60
      
#################
#    SENSORS    #
#################
sensor:

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: 'Test person.sander_blok'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: person.sander_blok
    action:
      - service: system_log.write
        data_template:
          message: "person.sander_blok is {{states('person.sander_blok')}}."
          level: info

  - alias: 'Test device_tracker.ariela_blokmeister_op6'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.ariela_blokmeister_op6
    action:
      - service: system_log.write
        data_template:
          message: "device_tracker.ariela_blokmeister_op6 is {{states('device_tracker.ariela_blokmeister_op6')}}."
          level: info

  - alias: 'Test device_tracker.ariela_blokmeister_op6_2'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.ariela_blokmeister_op6_2
    action:
      - service: system_log.write
        data_template:
          message: "device_tracker.ariela_blokmeister_op6_2 is {{states('device_tracker.ariela_blokmeister_op6_2')}}."
          level: info

  - alias: 'Test device_tracker.a0d0023bbd4d48d0b1b6d86aff27fe6d'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.a0d0023bbd4d48d0b1b6d86aff27fe6d
    action:
      - service: system_log.write
        data_template:
          message: "device_tracker.a0d0023bbd4d48d0b1b6d86aff27fe6d is {{states('device_tracker.a0d0023bbd4d48d0b1b6d86aff27fe6d')}}."
          level: info

  - alias: 'Test device_tracker.blokmeister_op6'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.blokmeister_op6
    action:
      - service: system_log.write
        data_template:
          message: "device_tracker.blokmeister_op6 is {{states('device_tracker.blokmeister_op6')}}."
          level: info

  - alias: 'Test device_tracker.blokmeister_op6_2'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.blokmeister_op6_2
    action:
      - service: system_log.write
        data_template:
          message: "device_tracker.blokmeister_op6 is {{states('device_tracker.blokmeister_op6_2')}}."
          level: info

  - alias: 'Test device_tracker.desktop_m07fv8p'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.desktop_m07fv8p
    action:
      - service: system_log.write
        data_template:
          message: "device_tracker.desktop_m07fv8p is {{states('device_tracker.desktop_m07fv8p')}}."
          level: info
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:
  device_tracker_testing:
    entities:
      - automation.test_device_tracker_a0d0023bbd4d48d0b1b6d86aff27fe6d
      - automation.test_device_tracker_ariela_blokmeister_op6
      - automation.test_device_tracker_ariela_blokmeister_op6_2
      - automation.test_device_tracker_blokmeister_op6
      - automation.test_device_tracker_blokmeister_op6_2
      - automation.test_device_tracker_desktop_m07fv8p
      - automation.test_person_sander_blok

#################
#    SCRIPTS    #
#################
script: