homeassistant:
  customize:
    sensor.speedtest_download:
      templates:
        icon: >
          if (state > 800) return 'mdi:speedometer';
          if (state > 500) return 'mdi:speedometer-medium';
          return 'mdi:speedometer-slow'
        icon_color: >
          var maxval = 1000;
          var minval = 400;
          var maxhue = 120;
          var minhue = 0;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
          return 'hsl(' + hue.toString() + ',80%,50%)';
    sensor.speedtest_upload:
      icon: mdi:speedometer
      templates:
        icon: >
          if (state > 800) return 'mdi:speedometer';
          if (state > 500) return 'mdi:speedometer-medium';
          return 'mdi:speedometer-slow'
        icon_color: >
          var maxval = 1000;
          var minval = 400;
          var maxhue = 120;
          var minhue = 0;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
          return 'hsl(' + hue.toString() + ',80%,50%)';
    sensor.speedtest_ping:
      icon: mdi:speedometer
      templates:
        icon_color: >
          var maxval = 30;
          var minval = 1;
          var maxhue = 0;
          var minhue = 120;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );


#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      udmp_download_speed_mbs:
        value_template: "{{ (states('sensor.unifi_dream_machine_kib_s_received')|float/1024)|round(1) }}"
        unit_of_measurement: MB/s
        friendly_name: "Router Download Speed"
        availability_template: "{{ states('sensor.unifi_dream_machine_kib_s_received')|is_number }}"
      udmp_upload_speed_mbs:
        value_template: "{{ (states('sensor.unifi_dream_machine_kib_s_sent')|float/1024)|round(1) }}"
        unit_of_measurement: MB/s
        friendly_name: "Router Download Speed"
        availability_template: "{{ states('sensor.unifi_dream_machine_kib_s_sent')|is_number }}"
      udmp_download_gb:
        value_template: "{{ (states('sensor.unifi_dream_machine_b_received')|float/1024**3)|round(1) }}"
        unit_of_measurement: GB
        friendly_name: "Router Total Download"
        availability_template: "{{ states('sensor.unifi_dream_machine_b_received')|is_number }}"
      udmp_upload_gb:
        value_template: "{{ (states('sensor.unifi_dream_machine_b_sent')|float/1024**3)|round(1) }}"
        unit_of_measurement: GB
        friendly_name: "Router Total Upload"
        availability_template: "{{ states('sensor.unifi_dream_machine_b_sent')|is_number }}"

      ap_groundfloor_number_of_clients:
        value_template: "{{ states.device_tracker | selectattr('attributes.ap_mac','defined') | selectattr('attributes.ap_mac','eq','d0:21:f9:64:06:39') | list | count }}"
        friendly_name: "AP Ground Floor Number of Clients"
        unit_of_measurement: "Clients"
        availability_template: "{{ is_state('device_tracker.udmpro', 'home' ) }}"
      ap_firstfloor_number_of_clients:
        value_template: "{{ states.device_tracker | selectattr('attributes.ap_mac','defined') | selectattr('attributes.ap_mac','eq','d0:21:f9:b7:9c:88') | list | count }}"
        friendly_name: "AP First Floor Number of Clients"
        unit_of_measurement: "Clients"
        availability_template: "{{ is_state('device_tracker.udmpro', 'home' ) }}"
      ap_secondfloor_number_of_clients:
        value_template: "{{ states.device_tracker | selectattr('attributes.ap_mac','defined') | selectattr('attributes.ap_mac','eq','d0:21:f9:b7:ea:68') | list | count }}"
        friendly_name: "AP Second Floor Number of Clients"
        unit_of_measurement: "Clients"
        availability_template: "{{ is_state('device_tracker.udmpro', 'home' ) }}"
      number_of_guests_connected:
        value_template: "{{ states.device_tracker | selectattr('attributes.essid','defined') | selectattr('attributes.essid','eq','BlokmeisterWIFI_Guest') | list | count }}"
        friendly_name: "Number of Guests Connected"
        unit_of_measurement: "Clients"
        availability_template: "{{ is_state('device_tracker.udmpro', 'home' ) }}"

  - platform: min_max
    name: USW Lite 16 Total PoE Power
    entity_ids:
      - sensor.usw_pro_max_16_poe_port_1_poe_power
      - sensor.usw_pro_max_16_poe_port_2_poe_power
      - sensor.usw_pro_max_16_poe_port_3_poe_power
      - sensor.usw_pro_max_16_poe_port_4_poe_power
      - sensor.usw_pro_max_16_poe_port_5_poe_power
      - sensor.usw_pro_max_16_poe_port_6_poe_power
      - sensor.usw_pro_max_16_poe_port_7_poe_power
      - sensor.usw_pro_max_16_poe_port_8_poe_power
      - sensor.usw_pro_max_16_poe_port_9_poe_power
      - sensor.usw_pro_max_16_poe_port_10_poe_power
      - sensor.usw_pro_max_16_poe_port_11_poe_power
      - sensor.usw_pro_max_16_poe_port_12_poe_power
      - sensor.usw_pro_max_16_poe_port_13_poe_power
      - sensor.usw_pro_max_16_poe_port_14_poe_power
      - sensor.usw_pro_max_16_poe_port_15_poe_power
      - sensor.usw_pro_max_16_poe_port_16_poe_power
    type: sum
    round_digits: 2

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[network|notify]Alert phone when network speed is too low'
    trigger:
      - platform: numeric_state
        entity_id: sensor.speedtest_download
        below: 100
        for:
          minutes: 70
    action:
      service: notify.mobile_app_blokmeisters21u
      data:
        title: "Network speed 100mbit!"
        message: "Current network speed {{ states('sensor.speedtest_download') }} Mbit/s."
        data:
          group: reminder
          tag: networkspeed
          timeout: 1800


################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
