homeassistant:
  customize: {}
    # sensor.speedtest_download:
    #   templates:
    #     icon: >
    #       if (state > 800) return 'mdi:speedometer';
    #       if (state > 500) return 'mdi:speedometer-medium';
    #       return 'mdi:speedometer-slow'
    #     icon_color: >
    #       var maxval = 1000;
    #       var minval = 400;
    #       var maxhue = 120;
    #       var minhue = 0;
    #       if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
    #       if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
    #       var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
    #       return 'hsl(' + hue.toString() + ',80%,50%)';
    # sensor.speedtest_upload:
    #   icon: mdi:speedometer
    #   templates:
    #     icon: >
    #       if (state > 800) return 'mdi:speedometer';
    #       if (state > 500) return 'mdi:speedometer-medium';
    #       return 'mdi:speedometer-slow'
    #     icon_color: >
    #       var maxval = 1000;
    #       var minval = 400;
    #       var maxhue = 120;
    #       var minhue = 0;
    #       if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
    #       if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
    #       var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
    #       return 'hsl(' + hue.toString() + ',80%,50%)';
    # sensor.speedtest_ping:
    #   icon: mdi:speedometer
    #   templates:
    #     icon_color: >
    #       var maxval = 30;
    #       var minval = 1;
    #       var maxhue = 0;
    #       var minhue = 120;
    #       if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
    #       if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
    #       var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );

command_line:
  # - sensor:
  #     name: "UDM Speedtest Raw" #Doesn't work yet. No ssh key support for UDM pro.
  #     command: >-
  #       ssh -i /config/.ssh/NUC_id_rsa -o StrictHostKeyChecking=no -q
  #       root@10.0.0.1
  #       '/mnt/data/speedtest --accept-license --accept-gdpr -f json'
  #     unit_of_measurement: "ms"
  #     scan_interval: 3600
  #     command_timeout: 120
  #     icon: mdi:speedometer
  #     value_template: "{{ value_json.ping.latency | float | round(2) }}"
  #     json_attributes:
  #       - ping
  #       - download.bandwidth
  #       - upload.bandwidth
  #       - packetLoss
  #       - isp
  #       - interface
  #       - server

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      udmp_download_speed_mbs:
        value_template: "{{ (states('sensor.unifi_dream_machine_kib_s_received')|float/1024)|round(1) }}"
        unit_of_measurement: MB/s
        friendly_name: "Router Download Speed"
        availability_template: "{{ states('sensor.unifi_dream_machine_kib_s_received')|is_number }}"
      udmp_upload_speed_mbs:
        value_template: "{{ (states('sensor.unifi_dream_machine_kib_s_sent')|float/1024)|round(1) }}"
        unit_of_measurement: MB/s
        friendly_name: "Router Download Speed"
        availability_template: "{{ states('sensor.unifi_dream_machine_kib_s_sent')|is_number }}"
      udmp_download_gb:
        value_template: "{{ (states('sensor.unifi_dream_machine_b_received')|float/1024**3)|round(1) }}"
        unit_of_measurement: GB
        friendly_name: "Router Total Download"
        availability_template: "{{ states('sensor.unifi_dream_machine_b_received')|is_number }}"
      udmp_upload_gb:
        value_template: "{{ (states('sensor.unifi_dream_machine_b_sent')|float/1024**3)|round(1) }}"
        unit_of_measurement: GB
        friendly_name: "Router Total Upload"
        availability_template: "{{ states('sensor.unifi_dream_machine_b_sent')|is_number }}"

      number_of_guests_connected:
        friendly_name: "Number of Guests Wifi Clients Connected"
        unique_id: yaml_template_sensor_number_of_guests_connected
        icon_template: mdi:account-network
        value_template: "{{ states.device_tracker | selectattr('attributes.essid','defined') | selectattr('attributes.essid','eq','BlokmeisterWIFI_Guest') | list | count }}"
        unit_of_measurement: "Clients"
        availability_template: "{{ is_state('device_tracker.udmpro', 'home' ) }}"

  - platform: min_max
    name: USW Lite 16 Total PoE Power
    entity_ids:
      - sensor.usw_pro_max_16_poe_port_1_poe_power
      - sensor.usw_pro_max_16_poe_port_2_poe_power
      - sensor.usw_pro_max_16_poe_port_3_poe_power
      - sensor.usw_pro_max_16_poe_port_4_poe_power
      - sensor.usw_pro_max_16_poe_port_5_poe_power
      - sensor.usw_pro_max_16_poe_port_6_poe_power
      - sensor.usw_pro_max_16_poe_port_7_poe_power
      - sensor.usw_pro_max_16_poe_port_8_poe_power
      - sensor.usw_pro_max_16_poe_port_9_poe_power
      - sensor.usw_pro_max_16_poe_port_10_poe_power
      - sensor.usw_pro_max_16_poe_port_11_poe_power
      - sensor.usw_pro_max_16_poe_port_12_poe_power
      - sensor.usw_pro_max_16_poe_port_13_poe_power
      - sensor.usw_pro_max_16_poe_port_14_poe_power
      - sensor.usw_pro_max_16_poe_port_15_poe_power
      - sensor.usw_pro_max_16_poe_port_16_poe_power
    type: sum
    round_digits: 2

  - platform: min_max
    name: "Shelly Median Ping"
    type: median
    round_digits: 0
    entity_ids:
      - sensor.ping_shelly_closet_round_trip_time_average
      - sensor.ping_shelly_dinnertable_round_trip_time_average
      - sensor.ping_shelly_kitchen_round_trip_time_average
      - sensor.ping_shelly_livingroom_round_trip_time_average
      - sensor.ping_shelly_entry_round_trip_time_average
      - sensor.ping_shelly_porch_round_trip_time_average
      - sensor.ping_shelly_backgarden_round_trip_time_average
      - sensor.ping_shelly_bedroom_round_trip_time_average
      - sensor.ping_shelly_bathroom_round_trip_time_average
      - sensor.ping_shelly_baby_room_round_trip_time_average
      - sensor.ping_shelly_hallway_1st_floor_round_trip_time_average
      - sensor.ping_shelly_hallway_2nd_floor_round_trip_time_average
      - sensor.ping_shelly_guest_room_round_trip_time_average
      - sensor.ping_shelly_study_round_trip_time_average
      - sensor.ping_shelly_washroom_round_trip_time_average

  - platform: min_max
    name: "Shelly Max Ping"
    type: max
    round_digits: 0
    entity_ids:
      - sensor.ping_shelly_closet_round_trip_time_average
      - sensor.ping_shelly_dinnertable_round_trip_time_average
      - sensor.ping_shelly_kitchen_round_trip_time_average
      - sensor.ping_shelly_livingroom_round_trip_time_average
      - sensor.ping_shelly_entry_round_trip_time_average
      - sensor.ping_shelly_porch_round_trip_time_average
      - sensor.ping_shelly_backgarden_round_trip_time_average
      - sensor.ping_shelly_bedroom_round_trip_time_average
      - sensor.ping_shelly_bathroom_round_trip_time_average
      - sensor.ping_shelly_baby_room_round_trip_time_average
      - sensor.ping_shelly_hallway_1st_floor_round_trip_time_average
      - sensor.ping_shelly_hallway_2nd_floor_round_trip_time_average
      - sensor.ping_shelly_guest_room_round_trip_time_average
      - sensor.ping_shelly_study_round_trip_time_average
      - sensor.ping_shelly_washroom_round_trip_time_average

########################
#    BINARY SENSORS    #
########################
binary_sensor:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[network|notify]Alert phone when network speed is too low'
    trigger:
      - platform: numeric_state
        entity_id: sensor.speedtest_download
        below: 100
        for:
          minutes: 70
    action:
      service: notify.mobile_app_blokmeisterp9pro
      data:
        title: "Network speed 100mbit!"
        message: "Current network speed {{ states('sensor.speedtest_download') }} Mbit/s."
        data:
          sticky: "true"
          clickAction: "/config/devices/device/5339147a29211a8fe30012ef2f3b9fe1"
          group: reminder
          tag: networkspeed
          timeout: 1800


################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
