homeassistant:
  customize:
    sensor.speedtest_download:
      templates:
        icon: >
          if (state > 800) return 'mdi:speedometer';
          if (state > 500) return 'mdi:speedometer-medium';
          return 'mdi:speedometer-slow'
        icon_color: >
          var maxval = 1000;
          var minval = 400;
          var maxhue = 120;
          var minhue = 0;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
          return 'hsl(' + hue.toString() + ',80%,50%)';
    sensor.speedtest_upload:
      icon: mdi:speedometer
      templates:
        icon: >
          if (state > 800) return 'mdi:speedometer';
          if (state > 500) return 'mdi:speedometer-medium';
          return 'mdi:speedometer-slow'
        icon_color: >
          var maxval = 1000;
          var minval = 400;
          var maxhue = 120;
          var minhue = 0;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
          return 'hsl(' + hue.toString() + ',80%,50%)';
    sensor.speedtest_ping:
      icon: mdi:speedometer
      templates:
        icon_color: >
          var maxval = 30;
          var minval = 1;
          var maxhue = 0;
          var minhue = 120;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );

# speedtestdotnet:
#   server_id: 13883
#   scan_interval:
#     minutes: 60
#   monitored_conditions:
#     - ping
#     - download
#     - upload

# asuswrt:
#   host: 192.168.1.1
#   username: !secret router_user
#   password: !secret router_pass
#   sensors:
#     - upload
#     - download
#     - upload_speed
#     - download_speed

# transmission:
#   host: 192.168.1.11
#   username: !secret transmission_user
#   password: !secret transmission_pass
  # monitored_conditions:
  #   - current_status
  #   - download_speed
  #   - upload_speed
  #   - active_torrents
  #   - paused_torrents
  #   - total_torrents
  #   - started_torrents
  #   - completed_torrents

#################
#    SENSORS    #
#################
sensor:
  - platform: template
    sensors:
      ping_router_avg:
        value_template: "{{ state_attr('binary_sensor.router', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Router ping average"

      ping_blokmeisternas_avg:
        value_template: "{{ state_attr('binary_sensor.blokmeisternas', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "BlokmeisterNAS ping average"

      ping_phone_avg:
        value_template: "{{ state_attr('binary_sensor.phone', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Phone ping average"

      ping_odroid_c2_avg:
        value_template: "{{ state_attr('binary_sensor.odroid_c2', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Odroid C2 ping average"

      ping_ambilight_rpi_avg:
        value_template: "{{ state_attr('binary_sensor.ambilight_rpi', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Ambilight RPI ping average"

      ping_transmission_avg:
        value_template: "{{ state_attr('binary_sensor.transmission', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Transmission jail ping average"

      ping_plinq_avg:
        value_template: "{{ state_attr('binary_sensor.plinq', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Plinq ping average"

      ping_google_dns_avg:
        value_template: "{{ state_attr('binary_sensor.google_dns', 'round_trip_time_avg')|round(2) }}"
        unit_of_measurement: ms
        friendly_name: "Google DNS jail ping average"

  - platform: statistics
    entity_id: sensor.asuswrt_download_speed
    name: Average download
    precision: 2
    sampling_size: 60
    max_age:
      minutes: 60

  - platform: statistics
    entity_id: sensor.asuswrt_upload_speed
    name: Average upload
    precision: 2
    sampling_size: 60
    max_age:
      minutes: 60

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: ping
    name: BlokmeisterNAS
    host: 192.168.1.250
    count: 10
    scan_interval: 60
  - platform: ping
    name: Router
    host: 192.168.1.1
    count: 10
    scan_interval: 60
  - platform: ping
    name: Phone
    host: 192.168.1.100
    count: 10
    scan_interval: 60
  - platform: ping
    name: Odroid_C2
    host: 192.168.1.50
    count: 10
    scan_interval: 60
  - platform: ping
    name: Ambilight_RPI
    host: 192.168.1.51
    count: 10
    scan_interval: 60
  - platform: ping
    name: Transmission
    host: 192.168.1.11
    count: 10
    scan_interval: 60
  - platform: ping
    name: Plinq
    host: 82.150.155.66
    count: 10
    scan_interval: 60
  - platform: ping
    name: Google_DNS
    host: 8.8.8.8
    count: 10
    scan_interval: 60
  - platform: ping
    name: Blokmeisterdesktop
    host: 192.168.1.187
    count: 10
    scan_interval: 60

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:
#Send a notification to Ariela when the a torrent is completed
  - alias: 'Completed Torrent'
    trigger:
      platform: event
      event_type: transmission_downloaded_torrent
    action:
      service: notify.mobile_app_blokmeister_op6_haapp
      data:
        title: "Torrent completed!"
        message: "{{ trigger.event.data.name }} has finished downloading!"
        data:
          group: reminder
          tag: transmission
          icon_url: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Transmission_icon.png"
          timeout: 1800

  - alias: '[network|notify]Alert phone when network speed is too low'
    trigger:
      - platform: numeric_state
        entity_id: sensor.speedtest_download
        below: 100
        for:
          minutes: 70
    action:
      service: notify.mobile_app_blokmeister_op6_haapp
      data:
        title: "Network speed 100mbit!"
        message: "Current network speed {{ states('sensor.speedtest_download') }} Mbit/s."
        data:
          group: reminder
          tag: networkspeed
          timeout: 1800
################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script:
  transmission_message_download_completed:
      alias: "Message phone about completed torrent"
      sequence:
        - service: notify.mobile_app_blokmeister_op6_haapp
          data:
            message: "A torrent is done downloading"
            title: "Home Assistant - Transmission"
            data:
              group: reminder
              tag: transmission
              icon_url: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Transmission_icon.png"
              timeout: 1800

  # message_transmission_not_reachable:
  #     alias: "Contact to transmission lost"
  #     sequence:
  #       - service: notify.mobile_app_blokmeister_op6
  #         data:
  #           message: "The contact to Transmission has been lost"
  #           title: "Home Assistant - Transmission"
  #           data:
  #             icon: "http://wfarm2.dataknet.com/static/resources/icons/set92/b8ef5c32.png"
  #             image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Transmission_icon.png"

  # message_odroid_not_reachable:
  #     alias: "Contact to Odroid C2 lost"
  #     sequence:
  #       - service: notify.mobile_app_blokmeister_op6
  #         data:
  #           message: "The contact to the Odroid C2 has been lost"
  #           title: "Home Assistant - Odroid C2"
  #           data:
  #             icon: mdi:library-movie
  #             image: mdi_library-movie
