homeassistant:
  customize_glob:
    sensor.*db_size:
      icon: mdi:database
    sensor.mediacenter_cabinet_*:
      device_class: temperature
      unit_of_measurement: '°C'
      templates:
        icon_color: >-
          var maxval = 35;
          var minval = 15;
          var maxhue = 0;
          var minhue = 140;
          if (state > maxval) return 'hsl(' + maxhue.toString() + ',80%,50%)';
          if (state < minval) return 'hsl(' + minhue.toString() + ',80%,50%)';
          var hue = Math.round((Number(state) - minval) / (maxval - minval) * (maxhue - minhue) + minhue );
          return 'hsl(' + hue.toString() + ',80%,50%)';
    switch.*_mounted:
      templates:
        icon: >
          if (state === 'on' ) return 'mdi:check-network-outline'; else return 'mdi:close-network-outline';


breaking_changes:
  scan_interval: 3600

monitor_docker:
  - name: Docker
    url: tcp://192.168.1.252:2375
    containers:
      - addon_core_mariadb
      - addon_core_deconz
      - homeassistant
      - hassio_supervisor
      - addon_a0d7b954_vscode
      - addon_a0d7b954_tautulli
      - addon_a0d7b954_ssh
      - addon_a0d7b954_influxdb
      - addon_a0d7b954_portainer
      - addon_core_mosquitto
      - hassio_multicast
      - hassio_dns
      - hassio_cli
      - hassio_audio
    rename:
      addon_core_mariadb: MariaDB database
      addon_core_deconz: Deconz Zigbee
      homeassistant: Home Assistant
      hassio_supervisor: Supervisor
      addon_a0d7b954_vscode: VScode
      addon_a0d7b954_tautulli: Tautulli
      addon_a0d7b954_ssh: SSH
      addon_a0d7b954_influxdb: InfluxDB
      addon_a0d7b954_portainer: Portainer
      addon_core_mosquitto: Mosquitto
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - containers_cpu_percentage
      - cpu_percentage
      - status
      - memory
      - network_speed_up
      - network_speed_down

#################
#    SENSORS    #
#################
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: last_boot

  - platform: uptime
    unit_of_measurement: minutes

  - platform: version
    source: hassio

  - platform: sql
    db_url: !secret mariadb_URL
    queries:
      - name: MariaDB size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / POWER(1024,2), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB

  - platform: influxdb
    username: !secret influxdb_user
    password: !secret influxdb_pass
    queries:
      - name: InfluxDB Size
        unit_of_measurement: MB
        value_template: '{{ (value | float / 1024 /1024) | round(1) }}'
        group_function: sum
        measurement: '"monitor"."shard"'
        database: _internal
        where: 'time > now() - 10s'
        field: diskBytes
  - platform: template
    sensors:
      hassio_uptime_human_readable:
        entity_id: sensor.uptime
        friendly_name: "Home Assistant uptime"
        value_template: >
          {{ (states.sensor.uptime.state|float * 60 | int - 3600) | timestamp_custom(('%H:%M:%S')) }}
      uptime_seconds:
        entity_id: sensor.uptime
        device_class: timestamp
        value_template: >
          {{ states.sensor.uptime.state|float * 60 | float }}

########################
#    BINARY SENSORS    #
########################
binary_sensor:
  - platform: command_line
    name: 'Unrarredmovies mounted'
    scan_interval: 60
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      root@192.168.1.252
      '[ "$(ls -A /mnt/unrarred/unrarredmovies)" ] && echo "True" || echo "False"'
    payload_on: "True"
    payload_off: "False"
  - platform: command_line
    name: 'Unrarredseries mounted'
    scan_interval: 60
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      root@192.168.1.252
      '[ "$(ls -A /mnt/unrarred/unrarredseries)" ] && echo "True" || echo "False"'
    payload_on: "True"
    payload_off: "False"
  - platform: command_line
    name: 'Newstorage mounted'
    # friendly_name: 'CPU Core 1 temp'
    scan_interval: 60
    command: >-
      ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
      root@192.168.1.252
      '[ "$(ls -A /mnt/NewStorage)" ] && echo "True" || echo "False"'
    payload_on: "True"
    payload_off: "False"
    
##################
#    SWITCHES    #
##################
switch:
  - platform: command_line
    switches:
      newstorage_mounted:
        command_on: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          'mount -a'
        command_off: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          'umount /mnt/NewStorage'
        command_state: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          '[ "$(ls -A /mnt/NewStorage)" ] && echo "True" || echo "False"'
        value_template: '{{ value == "True" }}'
      unrarredseries_mounted:
        command_on: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          'rar2fs -o allow_other --seek-length=0 /mnt/NewStorage/Series /mnt/unrarred/unrarredseries'
        command_off: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          'fusermount -u /mnt/unrarred/unrarredseries'
        command_state: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          '[ "$(ls -A /mnt/unrarred/unrarredseries)" ] && echo "True" || echo "False"'
        value_template: '{{ value == "True" }}'
      unrarredmovies_mounted:
        command_on: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          'rar2fs -o allow_other --seek-length=0 /mnt/NewStorage/Movies /mnt/unrarred/unrarredmovies'
        command_off: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          'fusermount -u /mnt/unrarred/unrarredmovies'
        command_state: >-
          ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no -q
          root@192.168.1.252
          '[ "$(ls -A /mnt/unrarred/unrarredmovies)" ] && echo "True" || echo "False"'
        value_template: '{{ value == "True" }}'
#####################
#    AUTOMATIONS    #
#####################
automation:
  - alias: '[System] Hass Stopped'
    initial_state: on
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      - service: tts.google_say
        entity_id: media_player.living_room_speaker
        data:
          message: "Home Assistant shut down"
      - service: notify.mobile_app_blokmeister_op6
        data:
          message: "Hass.io was shut down!"
          title: "Hass.io Offline"
          data:
            icon: http://192.168.1.252:8123/local/icons/home-assistant.png
            tag: 1 #hassiostatus


  - alias: '[System] Hass Started'
    initial_state: on
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: notify.mobile_app_blokmeister_op6
        data:
          message: "Hass.io back online"
          title: "Hass.io Online"
          data:
            icon: http://192.168.1.252:8123/local/icons/home-assistant.png
            tag: 1 #hassiostatus
      - service: tts.google_say
        entity_id: media_player.living_room_speaker
        data:
          message: "Home Assistant back online"

  - alias: '[System] Hass Updater'
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.latest_version
      - platform: numeric_state
        entity_id: sensor.uptime
        above: 1
    condition:
      - condition: numeric_state
        entity_id: sensor.uptime
        above: 1
      - condition: template
        value_template: "{{ states('sensor.latest_version') != states('sensor.current_version') }}"
    action:
      - service: persistent_notification.create
        data:
          message: "Hass.io version {{ states('sensor.latest_version') }} is now available!"
          title: Upgrade time!
      - service: hassio.addon_start
        data:
          addon: core_check_config

  - alias: '[System] Breaking changes'
    trigger:
      - platform: numeric_state
        entity_id: sensor.potential_breaking_changes
        above: 0
    action:
      - service: persistent_notification.create
        data:
          message: "{{states.sensor.potential_breaking_changes.state}} potential breaking changes detected between version {{states.sensor.current_version.state}} and version {{states.sensor.latest_version.state}}"
          title: "Potential breaking changes"

  - alias: '[System] Mount NAS drives'
    initial_state: on
    trigger:
      - platform: state
        entity_id: switch.blokmeisternas
        from: 'off'
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.newstorage_mounted
            state: 'off'
          - condition: state
            entity_id: binary_sensor.unrarredmovies_mounted
            state: 'off'
          - condition: state
            entity_id: binary_sensor.unrarredseries_mounted
            state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.newstorage_mounted
      - delay:
          seconds: 10
      - wait_template: "{{ is_state('switch.newstorage_mounted', 'on')}}"
        timeout:
          minutes: 5
        continue_on_timeout: false
      - service: switch.turn_on
        entity_id: switch.unrarredmovies_mounted
      - service: switch.turn_on
        entity_id: switch.unrarredseries_mounted
      - delay:
          seconds: 10
      - wait_template: "{{ is_state('switch.unrarredmovies_mounted', 'on') and is_state('switch.unrarredseries_mounted', 'on') }}"
        timeout:
          minutes: 5
        continue_on_timeout: false
      - service: system_log.write
        data_template:
          message: 'BlokmeisterNAS directories mounted successfully'
          level: info
      - service: notify.mobile_app_blokmeister_op6
        data:
          message: "NAS bootup detected. NAS drives mounted successfully"
          title: "NAS drives mounted"
          data:
            icon: http://192.168.1.252:8123/local/icons/server-network.png
            tag: 2 #nasdrivesmount

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: