homeassistant:
  customize:

#################
#    SENSORS    #
#################
sensor:
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: memory_use
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot
      - type: network_in
        arg: eno1
      - type: network_out
        arg: eno1
      - type: ipv4_address
        arg: eno1

########################
#    BINARY SENSORS    #
########################
binary_sensor:

########################
#    INPUT BOOLEANS    #
########################
input_boolean:

##################
#    SWITCHES    #
##################
switch:

#####################
#    AUTOMATIONS    #
#####################
automation:

################
#    SCENES    #
################
scene:

################
#    GROUPS    #
################
group:

#################
#    SCRIPTS    #
#################
script: